#' LLM Pulse API
#'
#' REST API client for LLM Pulse AI visibility analytics.
#'
#' The version of the OpenAPI document: 1.22.0
#' Contact: info@llmpulse.ai
#' Generated by: https://openapi-generator.tech
#'
#' @docType class
#' @title AIModelInsights operations
#' @description AIModelInsightsApi
#' @format An \code{R6Class} generator object
#' @field api_client Handles the client-server communication.
#'
#' @examples
#' \dontrun{
#' ####################  GetAiModelInsightsSummary  ####################
#'
#' library(llmpulse)
#' var_project_id <- 56 # integer | Project ID
#' var_range <- 56 # integer | Number of days to look back (alternative to from/to) (Optional)
#' var_from <- "from_example" # character |  (Optional)
#' var_to <- "to_example" # character |  (Optional)
#' var_granularity <- "granularity_example" # character |  (Optional)
#' var_collection_id <- 56 # integer |  (Optional)
#' var_country_code <- "country_code_example" # character | ISO country code (e.g. US, GB, DE) (Optional)
#' var_language_code <- "language_code_example" # character | ISO language code (e.g. en, es, de) (Optional)
#' var_prompt_type <- "prompt_type_example" # character | Filter by prompt type (search intent) (Optional)
#' var_brand_kind <- "brand_kind_example" # character | Filter by brand kind: brand (own brand/products), brand_other (competitors/other brands), non_brand (generic, no brand named). For fair 1:1 brand-vs-competitor comparisons (visibility, share of voice), use non_brand: brand-focused prompts skew results toward the brand they name. The in-app Overview page applies non_brand by default. (Optional)
#' var_competitors <- "competitors_example" # character | Comma-separated competitor IDs (unknown IDs return ERR_INVALID_PARAM) (Optional)
#'
#' #AI Model Insights summary
#' api_instance <- AIModelInsightsApi$new()
#'
#' # Configure HTTP bearer authorization: BearerAuth
#' api_instance$api_client$bearer_token <- Sys.getenv("BEARER_TOKEN")
#'
#' api_instance$GetAiModelInsightsSummary(var_project_id, range = var_range, from = var_from, to = var_to, granularity = var_granularity, collection_id = var_collection_id, country_code = var_country_code, language_code = var_language_code, prompt_type = var_prompt_type, brand_kind = var_brand_kind, competitors = var_competitors)
#'
#'
#' ####################  GetAiModelPositionDistribution  ####################
#'
#' library(llmpulse)
#' var_project_id <- 56 # integer | Project ID
#' var_range <- 56 # integer | Number of days to look back (alternative to from/to) (Optional)
#' var_from <- "from_example" # character |  (Optional)
#' var_to <- "to_example" # character |  (Optional)
#' var_granularity <- "granularity_example" # character |  (Optional)
#' var_collection_id <- 56 # integer |  (Optional)
#' var_country_code <- "country_code_example" # character | ISO country code (e.g. US, GB, DE) (Optional)
#' var_language_code <- "language_code_example" # character | ISO language code (e.g. en, es, de) (Optional)
#' var_prompt_type <- "prompt_type_example" # character | Filter by prompt type (search intent) (Optional)
#' var_brand_kind <- "brand_kind_example" # character | Filter by brand kind: brand (own brand/products), brand_other (competitors/other brands), non_brand (generic, no brand named). For fair 1:1 brand-vs-competitor comparisons (visibility, share of voice), use non_brand: brand-focused prompts skew results toward the brand they name. The in-app Overview page applies non_brand by default. (Optional)
#' var_model <- "model_example" # character | Filter by AI model. Models the API key's user has not enabled are silently dropped. (Optional)
#' var_brand1 <- 56 # integer | Competitor ID for the first comparison brand (omit to compare project brand) (Optional)
#' var_brand2 <- 56 # integer |  (Optional)
#'
#' #Position distribution comparison
#' api_instance <- AIModelInsightsApi$new()
#'
#' # Configure HTTP bearer authorization: BearerAuth
#' api_instance$api_client$bearer_token <- Sys.getenv("BEARER_TOKEN")
#'
#' api_instance$GetAiModelPositionDistribution(var_project_id, range = var_range, from = var_from, to = var_to, granularity = var_granularity, collection_id = var_collection_id, country_code = var_country_code, language_code = var_language_code, prompt_type = var_prompt_type, brand_kind = var_brand_kind, model = var_model, brand1 = var_brand1, brand2 = var_brand2)
#'
#'
#' ####################  GetAiOverviewResults  ####################
#'
#' library(llmpulse)
#' var_project_id <- 56 # integer | Project ID
#' var_range <- 56 # integer | Number of days to look back (alternative to from/to) (Optional)
#' var_from <- "from_example" # character |  (Optional)
#' var_to <- "to_example" # character |  (Optional)
#' var_granularity <- "granularity_example" # character |  (Optional)
#' var_collection_id <- 56 # integer |  (Optional)
#' var_country_code <- "country_code_example" # character | ISO country code (e.g. US, GB, DE) (Optional)
#' var_language_code <- "language_code_example" # character | ISO language code (e.g. en, es, de) (Optional)
#' var_prompt_type <- "prompt_type_example" # character | Filter by prompt type (search intent) (Optional)
#' var_brand_kind <- "brand_kind_example" # character | Filter by brand kind: brand (own brand/products), brand_other (competitors/other brands), non_brand (generic, no brand named). For fair 1:1 brand-vs-competitor comparisons (visibility, share of voice), use non_brand: brand-focused prompts skew results toward the brand they name. The in-app Overview page applies non_brand by default. (Optional)
#' var_page <- 1 # integer |  (Optional)
#' var_per_page <- 20 # integer |  (Optional)
#'
#' #Google AI Overview result availability
#' api_instance <- AIModelInsightsApi$new()
#'
#' # Configure HTTP bearer authorization: BearerAuth
#' api_instance$api_client$bearer_token <- Sys.getenv("BEARER_TOKEN")
#'
#' api_instance$GetAiOverviewResults(var_project_id, range = var_range, from = var_from, to = var_to, granularity = var_granularity, collection_id = var_collection_id, country_code = var_country_code, language_code = var_language_code, prompt_type = var_prompt_type, brand_kind = var_brand_kind, page = var_page, per_page = var_per_page)
#'
#'
#' }
#' @importFrom R6 R6Class
#' @importFrom base64enc base64encode
#' @export
AIModelInsightsApi <- R6::R6Class(
  "AIModelInsightsApi",
  public = list(
    api_client = NULL,

    #' @description
    #' Initialize a new AIModelInsightsApi.
    #'
    #' @param api_client An instance of API client.
    initialize = function(api_client) {
      if (!missing(api_client)) {
        self$api_client <- api_client
      } else {
        self$api_client <- ApiClient$new()
      }
    },

    #' @description
    #' AI Model Insights summary
    #'
    #' @param project_id Project ID
    #' @param range (optional) Number of days to look back (alternative to from/to)
    #' @param from (optional) No description
    #' @param to (optional) No description
    #' @param granularity (optional) No description
    #' @param collection_id (optional) No description
    #' @param country_code (optional) ISO country code (e.g. US, GB, DE)
    #' @param language_code (optional) ISO language code (e.g. en, es, de)
    #' @param prompt_type (optional) Filter by prompt type (search intent)
    #' @param brand_kind (optional) Filter by brand kind: brand (own brand/products), brand_other (competitors/other brands), non_brand (generic, no brand named). For fair 1:1 brand-vs-competitor comparisons (visibility, share of voice), use non_brand: brand-focused prompts skew results toward the brand they name. The in-app Overview page applies non_brand by default.
    #' @param competitors (optional) Comma-separated competitor IDs (unknown IDs return ERR_INVALID_PARAM)
    #' @param ... Other optional arguments
    #'
    #' @return void
    GetAiModelInsightsSummary = function(project_id, range = NULL, from = NULL, to = NULL, granularity = NULL, collection_id = NULL, country_code = NULL, language_code = NULL, prompt_type = NULL, brand_kind = NULL, competitors = NULL, ...) {
      local_var_response <- self$GetAiModelInsightsSummaryWithHttpInfo(project_id, range, from, to, granularity, collection_id, country_code, language_code, prompt_type, brand_kind, competitors, ...)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        return(local_var_response$content)
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        return(local_var_response)
      }
    },

    #' @description
    #' AI Model Insights summary
    #'
    #' @param project_id Project ID
    #' @param range (optional) Number of days to look back (alternative to from/to)
    #' @param from (optional) No description
    #' @param to (optional) No description
    #' @param granularity (optional) No description
    #' @param collection_id (optional) No description
    #' @param country_code (optional) ISO country code (e.g. US, GB, DE)
    #' @param language_code (optional) ISO language code (e.g. en, es, de)
    #' @param prompt_type (optional) Filter by prompt type (search intent)
    #' @param brand_kind (optional) Filter by brand kind: brand (own brand/products), brand_other (competitors/other brands), non_brand (generic, no brand named). For fair 1:1 brand-vs-competitor comparisons (visibility, share of voice), use non_brand: brand-focused prompts skew results toward the brand they name. The in-app Overview page applies non_brand by default.
    #' @param competitors (optional) Comma-separated competitor IDs (unknown IDs return ERR_INVALID_PARAM)
    #' @param ... Other optional arguments
    #'
    #' @return API response (void) with additional information such as HTTP status code, headers
    GetAiModelInsightsSummaryWithHttpInfo = function(project_id, range = NULL, from = NULL, to = NULL, granularity = NULL, collection_id = NULL, country_code = NULL, language_code = NULL, prompt_type = NULL, brand_kind = NULL, competitors = NULL, ...) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE

      if (missing(`project_id`)) {
        stop("Missing required parameter `project_id`.")
      }

      if (!missing(`project_id`) && is.null(`project_id`)) {
        stop("Invalid value for `project_id` when calling AIModelInsightsApi$GetAiModelInsightsSummary, `project_id` is not nullable")
      }

      if (!missing(`range`) && is.null(`range`)) {
        stop("Invalid value for `range` when calling AIModelInsightsApi$GetAiModelInsightsSummary, `range` is not nullable")
      }

      if (!missing(`from`) && is.null(`from`)) {
        stop("Invalid value for `from` when calling AIModelInsightsApi$GetAiModelInsightsSummary, `from` is not nullable")
      }

      if (!missing(`to`) && is.null(`to`)) {
        stop("Invalid value for `to` when calling AIModelInsightsApi$GetAiModelInsightsSummary, `to` is not nullable")
      }

      if (!missing(`granularity`) && is.null(`granularity`)) {
        stop("Invalid value for `granularity` when calling AIModelInsightsApi$GetAiModelInsightsSummary, `granularity` is not nullable")
      }

      if (!missing(`collection_id`) && is.null(`collection_id`)) {
        stop("Invalid value for `collection_id` when calling AIModelInsightsApi$GetAiModelInsightsSummary, `collection_id` is not nullable")
      }

      if (!missing(`country_code`) && is.null(`country_code`)) {
        stop("Invalid value for `country_code` when calling AIModelInsightsApi$GetAiModelInsightsSummary, `country_code` is not nullable")
      }

      if (!missing(`language_code`) && is.null(`language_code`)) {
        stop("Invalid value for `language_code` when calling AIModelInsightsApi$GetAiModelInsightsSummary, `language_code` is not nullable")
      }

      if (!missing(`prompt_type`) && is.null(`prompt_type`)) {
        stop("Invalid value for `prompt_type` when calling AIModelInsightsApi$GetAiModelInsightsSummary, `prompt_type` is not nullable")
      }

      if (!missing(`brand_kind`) && is.null(`brand_kind`)) {
        stop("Invalid value for `brand_kind` when calling AIModelInsightsApi$GetAiModelInsightsSummary, `brand_kind` is not nullable")
      }

      if (!missing(`competitors`) && is.null(`competitors`)) {
        stop("Invalid value for `competitors` when calling AIModelInsightsApi$GetAiModelInsightsSummary, `competitors` is not nullable")
      }

      query_params[["project_id"]] <- `project_id`

      query_params[["range"]] <- `range`

      query_params[["from"]] <- `from`

      query_params[["to"]] <- `to`

      if (!is.null(`granularity`) && !(`granularity` %in% c("day", "week", "month"))) {
        stop("Invalid value for granularity when calling AIModelInsightsApi$GetAiModelInsightsSummary. Must be [day, week, month].")
      }
      query_params[["granularity"]] <- `granularity`

      query_params[["collection_id"]] <- `collection_id`

      query_params[["country_code"]] <- `country_code`

      query_params[["language_code"]] <- `language_code`

      if (!is.null(`prompt_type`) && !(`prompt_type` %in% c("informational", "navigational", "commercial", "transactional"))) {
        stop("Invalid value for prompt_type when calling AIModelInsightsApi$GetAiModelInsightsSummary. Must be [informational, navigational, commercial, transactional].")
      }
      query_params[["prompt_type"]] <- `prompt_type`

      if (!is.null(`brand_kind`) && !(`brand_kind` %in% c("brand", "brand_other", "non_brand"))) {
        stop("Invalid value for brand_kind when calling AIModelInsightsApi$GetAiModelInsightsSummary. Must be [brand, brand_other, non_brand].")
      }
      query_params[["brand_kind"]] <- `brand_kind`

      query_params[["competitors"]] <- `competitors`

      local_var_url_path <- "/reports/ai_model_insights/summary"
      # Bearer token
      if (!is.null(self$api_client$bearer_token)) {
        header_params["Authorization"] <- paste("Bearer", self$api_client$bearer_token, sep = " ")
      }

      # The Accept request HTTP header
      local_var_accepts <- list()

      # The Content-Type representation header
      local_var_content_types <- list()

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "GET",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        local_var_resp$content <- NULL
        return(local_var_resp)
      } 
      
      local_var_error_msg <- local_var_resp$response_as_text()      
      if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        ApiResponse$new(content = paste("Server returned ", local_var_resp$status_code, " response status code."),
                        response = local_var_resp,
                        status_code = local_var_resp$status_code)
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        ApiResponse$new(content = "API client error",
                        response = local_var_resp,
                        status_code = local_var_resp$status_code)
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        if (is.null(local_var_resp$response) || all(local_var_resp$response == "")) {
          local_var_resp$response <- "API server error"
        }
        return(local_var_resp)
      }
    },

    #' @description
    #' Position distribution comparison
    #'
    #' @param project_id Project ID
    #' @param range (optional) Number of days to look back (alternative to from/to)
    #' @param from (optional) No description
    #' @param to (optional) No description
    #' @param granularity (optional) No description
    #' @param collection_id (optional) No description
    #' @param country_code (optional) ISO country code (e.g. US, GB, DE)
    #' @param language_code (optional) ISO language code (e.g. en, es, de)
    #' @param prompt_type (optional) Filter by prompt type (search intent)
    #' @param brand_kind (optional) Filter by brand kind: brand (own brand/products), brand_other (competitors/other brands), non_brand (generic, no brand named). For fair 1:1 brand-vs-competitor comparisons (visibility, share of voice), use non_brand: brand-focused prompts skew results toward the brand they name. The in-app Overview page applies non_brand by default.
    #' @param model (optional) Filter by AI model. Models the API key's user has not enabled are silently dropped.
    #' @param brand1 (optional) Competitor ID for the first comparison brand (omit to compare project brand)
    #' @param brand2 (optional) No description
    #' @param ... Other optional arguments
    #'
    #' @return void
    GetAiModelPositionDistribution = function(project_id, range = NULL, from = NULL, to = NULL, granularity = NULL, collection_id = NULL, country_code = NULL, language_code = NULL, prompt_type = NULL, brand_kind = NULL, model = NULL, brand1 = NULL, brand2 = NULL, ...) {
      local_var_response <- self$GetAiModelPositionDistributionWithHttpInfo(project_id, range, from, to, granularity, collection_id, country_code, language_code, prompt_type, brand_kind, model, brand1, brand2, ...)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        return(local_var_response$content)
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        return(local_var_response)
      }
    },

    #' @description
    #' Position distribution comparison
    #'
    #' @param project_id Project ID
    #' @param range (optional) Number of days to look back (alternative to from/to)
    #' @param from (optional) No description
    #' @param to (optional) No description
    #' @param granularity (optional) No description
    #' @param collection_id (optional) No description
    #' @param country_code (optional) ISO country code (e.g. US, GB, DE)
    #' @param language_code (optional) ISO language code (e.g. en, es, de)
    #' @param prompt_type (optional) Filter by prompt type (search intent)
    #' @param brand_kind (optional) Filter by brand kind: brand (own brand/products), brand_other (competitors/other brands), non_brand (generic, no brand named). For fair 1:1 brand-vs-competitor comparisons (visibility, share of voice), use non_brand: brand-focused prompts skew results toward the brand they name. The in-app Overview page applies non_brand by default.
    #' @param model (optional) Filter by AI model. Models the API key's user has not enabled are silently dropped.
    #' @param brand1 (optional) Competitor ID for the first comparison brand (omit to compare project brand)
    #' @param brand2 (optional) No description
    #' @param ... Other optional arguments
    #'
    #' @return API response (void) with additional information such as HTTP status code, headers
    GetAiModelPositionDistributionWithHttpInfo = function(project_id, range = NULL, from = NULL, to = NULL, granularity = NULL, collection_id = NULL, country_code = NULL, language_code = NULL, prompt_type = NULL, brand_kind = NULL, model = NULL, brand1 = NULL, brand2 = NULL, ...) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE

      if (missing(`project_id`)) {
        stop("Missing required parameter `project_id`.")
      }

      if (!missing(`project_id`) && is.null(`project_id`)) {
        stop("Invalid value for `project_id` when calling AIModelInsightsApi$GetAiModelPositionDistribution, `project_id` is not nullable")
      }

      if (!missing(`range`) && is.null(`range`)) {
        stop("Invalid value for `range` when calling AIModelInsightsApi$GetAiModelPositionDistribution, `range` is not nullable")
      }

      if (!missing(`from`) && is.null(`from`)) {
        stop("Invalid value for `from` when calling AIModelInsightsApi$GetAiModelPositionDistribution, `from` is not nullable")
      }

      if (!missing(`to`) && is.null(`to`)) {
        stop("Invalid value for `to` when calling AIModelInsightsApi$GetAiModelPositionDistribution, `to` is not nullable")
      }

      if (!missing(`granularity`) && is.null(`granularity`)) {
        stop("Invalid value for `granularity` when calling AIModelInsightsApi$GetAiModelPositionDistribution, `granularity` is not nullable")
      }

      if (!missing(`collection_id`) && is.null(`collection_id`)) {
        stop("Invalid value for `collection_id` when calling AIModelInsightsApi$GetAiModelPositionDistribution, `collection_id` is not nullable")
      }

      if (!missing(`country_code`) && is.null(`country_code`)) {
        stop("Invalid value for `country_code` when calling AIModelInsightsApi$GetAiModelPositionDistribution, `country_code` is not nullable")
      }

      if (!missing(`language_code`) && is.null(`language_code`)) {
        stop("Invalid value for `language_code` when calling AIModelInsightsApi$GetAiModelPositionDistribution, `language_code` is not nullable")
      }

      if (!missing(`prompt_type`) && is.null(`prompt_type`)) {
        stop("Invalid value for `prompt_type` when calling AIModelInsightsApi$GetAiModelPositionDistribution, `prompt_type` is not nullable")
      }

      if (!missing(`brand_kind`) && is.null(`brand_kind`)) {
        stop("Invalid value for `brand_kind` when calling AIModelInsightsApi$GetAiModelPositionDistribution, `brand_kind` is not nullable")
      }

      if (!missing(`model`) && is.null(`model`)) {
        stop("Invalid value for `model` when calling AIModelInsightsApi$GetAiModelPositionDistribution, `model` is not nullable")
      }

      if (!missing(`brand1`) && is.null(`brand1`)) {
        stop("Invalid value for `brand1` when calling AIModelInsightsApi$GetAiModelPositionDistribution, `brand1` is not nullable")
      }

      if (!missing(`brand2`) && is.null(`brand2`)) {
        stop("Invalid value for `brand2` when calling AIModelInsightsApi$GetAiModelPositionDistribution, `brand2` is not nullable")
      }

      query_params[["project_id"]] <- `project_id`

      query_params[["range"]] <- `range`

      query_params[["from"]] <- `from`

      query_params[["to"]] <- `to`

      if (!is.null(`granularity`) && !(`granularity` %in% c("day", "week", "month"))) {
        stop("Invalid value for granularity when calling AIModelInsightsApi$GetAiModelPositionDistribution. Must be [day, week, month].")
      }
      query_params[["granularity"]] <- `granularity`

      query_params[["collection_id"]] <- `collection_id`

      query_params[["country_code"]] <- `country_code`

      query_params[["language_code"]] <- `language_code`

      if (!is.null(`prompt_type`) && !(`prompt_type` %in% c("informational", "navigational", "commercial", "transactional"))) {
        stop("Invalid value for prompt_type when calling AIModelInsightsApi$GetAiModelPositionDistribution. Must be [informational, navigational, commercial, transactional].")
      }
      query_params[["prompt_type"]] <- `prompt_type`

      if (!is.null(`brand_kind`) && !(`brand_kind` %in% c("brand", "brand_other", "non_brand"))) {
        stop("Invalid value for brand_kind when calling AIModelInsightsApi$GetAiModelPositionDistribution. Must be [brand, brand_other, non_brand].")
      }
      query_params[["brand_kind"]] <- `brand_kind`

      if (!is.null(`model`) && !(`model` %in% c("chatgpt", "perplexity", "gemini", "ai_overview", "ai_mode", "copilot", "claude", "grok", "deepseek", "meta_ai", "amazon_rufus"))) {
        stop("Invalid value for model when calling AIModelInsightsApi$GetAiModelPositionDistribution. Must be [chatgpt, perplexity, gemini, ai_overview, ai_mode, copilot, claude, grok, deepseek, meta_ai, amazon_rufus].")
      }
      query_params[["model"]] <- `model`

      query_params[["brand1"]] <- `brand1`

      query_params[["brand2"]] <- `brand2`

      local_var_url_path <- "/reports/ai_model_insights/position_distribution"
      # Bearer token
      if (!is.null(self$api_client$bearer_token)) {
        header_params["Authorization"] <- paste("Bearer", self$api_client$bearer_token, sep = " ")
      }

      # The Accept request HTTP header
      local_var_accepts <- list()

      # The Content-Type representation header
      local_var_content_types <- list()

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "GET",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        local_var_resp$content <- NULL
        return(local_var_resp)
      } 
      
      local_var_error_msg <- local_var_resp$response_as_text()      
      if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        ApiResponse$new(content = paste("Server returned ", local_var_resp$status_code, " response status code."),
                        response = local_var_resp,
                        status_code = local_var_resp$status_code)
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        ApiResponse$new(content = "API client error",
                        response = local_var_resp,
                        status_code = local_var_resp$status_code)
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        if (is.null(local_var_resp$response) || all(local_var_resp$response == "")) {
          local_var_resp$response <- "API server error"
        }
        return(local_var_resp)
      }
    },

    #' @description
    #' Google AI Overview result availability
    #'
    #' @param project_id Project ID
    #' @param range (optional) Number of days to look back (alternative to from/to)
    #' @param from (optional) No description
    #' @param to (optional) No description
    #' @param granularity (optional) No description
    #' @param collection_id (optional) No description
    #' @param country_code (optional) ISO country code (e.g. US, GB, DE)
    #' @param language_code (optional) ISO language code (e.g. en, es, de)
    #' @param prompt_type (optional) Filter by prompt type (search intent)
    #' @param brand_kind (optional) Filter by brand kind: brand (own brand/products), brand_other (competitors/other brands), non_brand (generic, no brand named). For fair 1:1 brand-vs-competitor comparisons (visibility, share of voice), use non_brand: brand-focused prompts skew results toward the brand they name. The in-app Overview page applies non_brand by default.
    #' @param page (optional) No description (default value: 1)
    #' @param per_page (optional) No description (default value: 20)
    #' @param ... Other optional arguments
    #'
    #' @return void
    GetAiOverviewResults = function(project_id, range = NULL, from = NULL, to = NULL, granularity = NULL, collection_id = NULL, country_code = NULL, language_code = NULL, prompt_type = NULL, brand_kind = NULL, page = 1, per_page = 20, ...) {
      local_var_response <- self$GetAiOverviewResultsWithHttpInfo(project_id, range, from, to, granularity, collection_id, country_code, language_code, prompt_type, brand_kind, page, per_page, ...)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        return(local_var_response$content)
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        return(local_var_response)
      }
    },

    #' @description
    #' Google AI Overview result availability
    #'
    #' @param project_id Project ID
    #' @param range (optional) Number of days to look back (alternative to from/to)
    #' @param from (optional) No description
    #' @param to (optional) No description
    #' @param granularity (optional) No description
    #' @param collection_id (optional) No description
    #' @param country_code (optional) ISO country code (e.g. US, GB, DE)
    #' @param language_code (optional) ISO language code (e.g. en, es, de)
    #' @param prompt_type (optional) Filter by prompt type (search intent)
    #' @param brand_kind (optional) Filter by brand kind: brand (own brand/products), brand_other (competitors/other brands), non_brand (generic, no brand named). For fair 1:1 brand-vs-competitor comparisons (visibility, share of voice), use non_brand: brand-focused prompts skew results toward the brand they name. The in-app Overview page applies non_brand by default.
    #' @param page (optional) No description (default value: 1)
    #' @param per_page (optional) No description (default value: 20)
    #' @param ... Other optional arguments
    #'
    #' @return API response (void) with additional information such as HTTP status code, headers
    GetAiOverviewResultsWithHttpInfo = function(project_id, range = NULL, from = NULL, to = NULL, granularity = NULL, collection_id = NULL, country_code = NULL, language_code = NULL, prompt_type = NULL, brand_kind = NULL, page = 1, per_page = 20, ...) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE

      if (missing(`project_id`)) {
        stop("Missing required parameter `project_id`.")
      }

      if (!missing(`project_id`) && is.null(`project_id`)) {
        stop("Invalid value for `project_id` when calling AIModelInsightsApi$GetAiOverviewResults, `project_id` is not nullable")
      }

      if (!missing(`range`) && is.null(`range`)) {
        stop("Invalid value for `range` when calling AIModelInsightsApi$GetAiOverviewResults, `range` is not nullable")
      }

      if (!missing(`from`) && is.null(`from`)) {
        stop("Invalid value for `from` when calling AIModelInsightsApi$GetAiOverviewResults, `from` is not nullable")
      }

      if (!missing(`to`) && is.null(`to`)) {
        stop("Invalid value for `to` when calling AIModelInsightsApi$GetAiOverviewResults, `to` is not nullable")
      }

      if (!missing(`granularity`) && is.null(`granularity`)) {
        stop("Invalid value for `granularity` when calling AIModelInsightsApi$GetAiOverviewResults, `granularity` is not nullable")
      }

      if (!missing(`collection_id`) && is.null(`collection_id`)) {
        stop("Invalid value for `collection_id` when calling AIModelInsightsApi$GetAiOverviewResults, `collection_id` is not nullable")
      }

      if (!missing(`country_code`) && is.null(`country_code`)) {
        stop("Invalid value for `country_code` when calling AIModelInsightsApi$GetAiOverviewResults, `country_code` is not nullable")
      }

      if (!missing(`language_code`) && is.null(`language_code`)) {
        stop("Invalid value for `language_code` when calling AIModelInsightsApi$GetAiOverviewResults, `language_code` is not nullable")
      }

      if (!missing(`prompt_type`) && is.null(`prompt_type`)) {
        stop("Invalid value for `prompt_type` when calling AIModelInsightsApi$GetAiOverviewResults, `prompt_type` is not nullable")
      }

      if (!missing(`brand_kind`) && is.null(`brand_kind`)) {
        stop("Invalid value for `brand_kind` when calling AIModelInsightsApi$GetAiOverviewResults, `brand_kind` is not nullable")
      }

      if (!missing(`page`) && is.null(`page`)) {
        stop("Invalid value for `page` when calling AIModelInsightsApi$GetAiOverviewResults, `page` is not nullable")
      }
      if (!is.null(`page`) && `page` <  1) {
        stop("Invalid value for `page` when calling AIModelInsightsApi$GetAiOverviewResults, must be bigger than or equal to 1.")
      }

      if (!missing(`per_page`) && is.null(`per_page`)) {
        stop("Invalid value for `per_page` when calling AIModelInsightsApi$GetAiOverviewResults, `per_page` is not nullable")
      }
      if (!is.null(`per_page`) && `per_page` >  100) {
        stop("Invalid value for `per_page` when calling AIModelInsightsApi$GetAiOverviewResults, must be smaller than or equal to 100.")
      }
      if (!is.null(`per_page`) && `per_page` <  1) {
        stop("Invalid value for `per_page` when calling AIModelInsightsApi$GetAiOverviewResults, must be bigger than or equal to 1.")
      }

      query_params[["project_id"]] <- `project_id`

      query_params[["range"]] <- `range`

      query_params[["from"]] <- `from`

      query_params[["to"]] <- `to`

      if (!is.null(`granularity`) && !(`granularity` %in% c("day", "week", "month"))) {
        stop("Invalid value for granularity when calling AIModelInsightsApi$GetAiOverviewResults. Must be [day, week, month].")
      }
      query_params[["granularity"]] <- `granularity`

      query_params[["collection_id"]] <- `collection_id`

      query_params[["country_code"]] <- `country_code`

      query_params[["language_code"]] <- `language_code`

      if (!is.null(`prompt_type`) && !(`prompt_type` %in% c("informational", "navigational", "commercial", "transactional"))) {
        stop("Invalid value for prompt_type when calling AIModelInsightsApi$GetAiOverviewResults. Must be [informational, navigational, commercial, transactional].")
      }
      query_params[["prompt_type"]] <- `prompt_type`

      if (!is.null(`brand_kind`) && !(`brand_kind` %in% c("brand", "brand_other", "non_brand"))) {
        stop("Invalid value for brand_kind when calling AIModelInsightsApi$GetAiOverviewResults. Must be [brand, brand_other, non_brand].")
      }
      query_params[["brand_kind"]] <- `brand_kind`

      query_params[["page"]] <- `page`

      query_params[["per_page"]] <- `per_page`

      local_var_url_path <- "/reports/ai_model_insights/ai_overview_results"
      # Bearer token
      if (!is.null(self$api_client$bearer_token)) {
        header_params["Authorization"] <- paste("Bearer", self$api_client$bearer_token, sep = " ")
      }

      # The Accept request HTTP header
      local_var_accepts <- list()

      # The Content-Type representation header
      local_var_content_types <- list()

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "GET",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        local_var_resp$content <- NULL
        return(local_var_resp)
      } 
      
      local_var_error_msg <- local_var_resp$response_as_text()      
      if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        ApiResponse$new(content = paste("Server returned ", local_var_resp$status_code, " response status code."),
                        response = local_var_resp,
                        status_code = local_var_resp$status_code)
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        ApiResponse$new(content = "API client error",
                        response = local_var_resp,
                        status_code = local_var_resp$status_code)
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        if (is.null(local_var_resp$response) || all(local_var_resp$response == "")) {
          local_var_resp$response <- "API server error"
        }
        return(local_var_resp)
      }
    }
  )
)
