#' LLM Pulse API
#'
#' REST API client for LLM Pulse AI visibility analytics.
#'
#' The version of the OpenAPI document: 1.22.0
#' Contact: info@llmpulse.ai
#' Generated by: https://openapi-generator.tech
#'
#' @docType class
#' @title Answers operations
#' @description AnswersApi
#' @format An \code{R6Class} generator object
#' @field api_client Handles the client-server communication.
#'
#' @examples
#' \dontrun{
#' ####################  GetAnswer  ####################
#'
#' library(llmpulse)
#' var_project_id <- 56 # integer | Project ID
#' var_id <- 56 # integer | 
#' var_include_source_page_details <- FALSE # character |  (Optional)
#'
#' #Get one AI response
#' api_instance <- AnswersApi$new()
#'
#' # Configure HTTP bearer authorization: BearerAuth
#' api_instance$api_client$bearer_token <- Sys.getenv("BEARER_TOKEN")
#'
#' # to save the result into a file, simply add the optional `data_file` parameter, e.g.
#' # result <- api_instance$GetAnswer(var_project_id, var_id, include_source_page_details = var_include_source_page_detailsdata_file = "result.txt")
#' result <- api_instance$GetAnswer(var_project_id, var_id, include_source_page_details = var_include_source_page_details)
#' dput(result)
#'
#'
#' ####################  ListAnswers  ####################
#'
#' library(llmpulse)
#' var_project_id <- 56 # integer | Project ID
#' var_model <- "model_example" # character | Filter by AI model. Models the API key's user has not enabled are silently dropped. (Optional)
#' var_collection_id <- 56 # integer |  (Optional)
#' var_country_code <- "country_code_example" # character | ISO country code (e.g. US, GB, DE) (Optional)
#' var_language_code <- "language_code_example" # character | ISO language code (e.g. en, es, de) (Optional)
#' var_prompt <- 56 # integer | Filter by prompt ID (Optional)
#' var_mention_filter <- "mention_filter_example" # character | Filter by which brands are mentioned, as a two-axis matrix (your brand x competitors): mentions_you / not_mentions_you, mentions_competitor / not_mentions_competitor, and the four combined cells you_and_competitor, competitor_not_you (a rival wins and you are absent), you_not_competitor, no_brands (no tracked brand appears, i.e. open space). Combine with 'competitors' to narrow the competitor side to specific rivals; on a negative cell that reads 'none of these'. On /dimensions/sources it applies to the crawled content of each cited page instead of the answer text. The legacy value 'competitors_only' is still accepted as an alias of competitor_not_you. (Optional)
#' var_citation_filter <- "citation_filter_example" # character | Same two-axis matrix applied to the domains cited in the answer instead of the brands named in it. Independent of mention_filter; pass both to intersect them (e.g. mentions_you + not_cites_you finds answers that talk about you without linking to you). (Optional)
#' var_competitors <- "competitors_example" # character | Comma-separated competitor IDs (unknown IDs return ERR_INVALID_PARAM) (Optional)
#' var_from <- "from_example" # character |  (Optional)
#' var_to <- "to_example" # character |  (Optional)
#' var_page <- 1 # integer |  (Optional)
#' var_per_page <- 20 # integer |  (Optional)
#' var_query <- "query_example" # character | Case-insensitive full-text search inside AI response texts. Switches items to snippet + match_count mode. (Optional)
#'
#' #List AI responses
#' api_instance <- AnswersApi$new()
#'
#' # Configure HTTP bearer authorization: BearerAuth
#' api_instance$api_client$bearer_token <- Sys.getenv("BEARER_TOKEN")
#'
#' api_instance$ListAnswers(var_project_id, model = var_model, collection_id = var_collection_id, country_code = var_country_code, language_code = var_language_code, prompt = var_prompt, mention_filter = var_mention_filter, citation_filter = var_citation_filter, competitors = var_competitors, from = var_from, to = var_to, page = var_page, per_page = var_per_page, query = var_query)
#'
#'
#' }
#' @importFrom R6 R6Class
#' @importFrom base64enc base64encode
#' @export
AnswersApi <- R6::R6Class(
  "AnswersApi",
  public = list(
    api_client = NULL,

    #' @description
    #' Initialize a new AnswersApi.
    #'
    #' @param api_client An instance of API client.
    initialize = function(api_client) {
      if (!missing(api_client)) {
        self$api_client <- api_client
      } else {
        self$api_client <- ApiClient$new()
      }
    },

    #' @description
    #' Get one AI response
    #'
    #' @param project_id Project ID
    #' @param id 
    #' @param include_source_page_details (optional) No description (default value: FALSE)
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @param .parse Logical. If \code{TRUE} then the response will be parsed to a generated type. If \code{FALSE} the response will be returned as unparsed text.
    #'
    #' @return AnswerDetails
    GetAnswer = function(project_id, id, include_source_page_details = FALSE, data_file = NULL, ..., .parse = TRUE) {
      local_var_response <- self$GetAnswerWithHttpInfo(project_id, id, include_source_page_details, data_file = data_file, ..., .parse = .parse)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        return(local_var_response$content)
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        return(local_var_response)
      }
    },

    #' @description
    #' Get one AI response
    #'
    #' @param project_id Project ID
    #' @param id 
    #' @param include_source_page_details (optional) No description (default value: FALSE)
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @param .parse Logical. If \code{TRUE} then the response will be parsed to a generated type. If \code{FALSE} the response will be returned as unparsed text.
    #'
    #' @return API response (AnswerDetails) with additional information such as HTTP status code, headers
    GetAnswerWithHttpInfo = function(project_id, id, include_source_page_details = FALSE, data_file = NULL, ..., .parse = TRUE) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE

      if (missing(`project_id`)) {
        stop("Missing required parameter `project_id`.")
      }

      if (missing(`id`)) {
        stop("Missing required parameter `id`.")
      }

      if (!missing(`project_id`) && is.null(`project_id`)) {
        stop("Invalid value for `project_id` when calling AnswersApi$GetAnswer, `project_id` is not nullable")
      }

      if (!missing(`id`) && is.null(`id`)) {
        stop("Invalid value for `id` when calling AnswersApi$GetAnswer, `id` is not nullable")
      }

      if (!missing(`include_source_page_details`) && is.null(`include_source_page_details`)) {
        stop("Invalid value for `include_source_page_details` when calling AnswersApi$GetAnswer, `include_source_page_details` is not nullable")
      }

      query_params[["project_id"]] <- `project_id`

      query_params[["include_source_page_details"]] <- `include_source_page_details`

      local_var_url_path <- "/answers/{id}"
      if (!missing(`id`)) {
        local_var_url_path <- gsub("\\{id\\}", URLencode(as.character(`id`), reserved = TRUE), local_var_url_path)
      }

      # Bearer token
      if (!is.null(self$api_client$bearer_token)) {
        header_params["Authorization"] <- paste("Bearer", self$api_client$bearer_token, sep = " ")
      }

      # The Accept request HTTP header
      local_var_accepts <- list("application/json")

      # The Content-Type representation header
      local_var_content_types <- list()

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "GET",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        # save response in a file
        if (!is.null(data_file)) {
          self$api_client$WriteFile(local_var_resp, data_file)
        }
        if (!.parse) {
          local_var_resp$content <- local_var_resp$response_as_text()
          return(local_var_resp)
        }

        deserialized_resp_obj <- tryCatch(
          self$api_client$DeserializeResponse(local_var_resp, "AnswerDetails"),
          error = function(e) {
            stop("Failed to deserialize response")
          }
        )
        local_var_resp$content <- deserialized_resp_obj
        return(local_var_resp)
      } 
      
      local_var_error_msg <- local_var_resp$response_as_text()      
      if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        ApiResponse$new(content = paste("Server returned ", local_var_resp$status_code, " response status code."),
                        response = local_var_resp,
                        status_code = local_var_resp$status_code)
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        ApiResponse$new(content = "API client error",
                        response = local_var_resp,
                        status_code = local_var_resp$status_code)
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        if (is.null(local_var_resp$response) || all(local_var_resp$response == "")) {
          local_var_resp$response <- "API server error"
        }
        return(local_var_resp)
      }
    },

    #' @description
    #' List AI responses
    #'
    #' @param project_id Project ID
    #' @param model (optional) Filter by AI model. Models the API key's user has not enabled are silently dropped.
    #' @param collection_id (optional) No description
    #' @param country_code (optional) ISO country code (e.g. US, GB, DE)
    #' @param language_code (optional) ISO language code (e.g. en, es, de)
    #' @param prompt (optional) Filter by prompt ID
    #' @param mention_filter (optional) Filter by which brands are mentioned, as a two-axis matrix (your brand x competitors): mentions_you / not_mentions_you, mentions_competitor / not_mentions_competitor, and the four combined cells you_and_competitor, competitor_not_you (a rival wins and you are absent), you_not_competitor, no_brands (no tracked brand appears, i.e. open space). Combine with 'competitors' to narrow the competitor side to specific rivals; on a negative cell that reads 'none of these'. On /dimensions/sources it applies to the crawled content of each cited page instead of the answer text. The legacy value 'competitors_only' is still accepted as an alias of competitor_not_you.
    #' @param citation_filter (optional) Same two-axis matrix applied to the domains cited in the answer instead of the brands named in it. Independent of mention_filter; pass both to intersect them (e.g. mentions_you + not_cites_you finds answers that talk about you without linking to you).
    #' @param competitors (optional) Comma-separated competitor IDs (unknown IDs return ERR_INVALID_PARAM)
    #' @param from (optional) No description
    #' @param to (optional) No description
    #' @param page (optional) No description (default value: 1)
    #' @param per_page (optional) No description (default value: 20)
    #' @param query (optional) Case-insensitive full-text search inside AI response texts. Switches items to snippet + match_count mode.
    #' @param ... Other optional arguments
    #'
    #' @return void
    ListAnswers = function(project_id, model = NULL, collection_id = NULL, country_code = NULL, language_code = NULL, prompt = NULL, mention_filter = NULL, citation_filter = NULL, competitors = NULL, from = NULL, to = NULL, page = 1, per_page = 20, query = NULL, ...) {
      local_var_response <- self$ListAnswersWithHttpInfo(project_id, model, collection_id, country_code, language_code, prompt, mention_filter, citation_filter, competitors, from, to, page, per_page, query, ...)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        return(local_var_response$content)
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        return(local_var_response)
      }
    },

    #' @description
    #' List AI responses
    #'
    #' @param project_id Project ID
    #' @param model (optional) Filter by AI model. Models the API key's user has not enabled are silently dropped.
    #' @param collection_id (optional) No description
    #' @param country_code (optional) ISO country code (e.g. US, GB, DE)
    #' @param language_code (optional) ISO language code (e.g. en, es, de)
    #' @param prompt (optional) Filter by prompt ID
    #' @param mention_filter (optional) Filter by which brands are mentioned, as a two-axis matrix (your brand x competitors): mentions_you / not_mentions_you, mentions_competitor / not_mentions_competitor, and the four combined cells you_and_competitor, competitor_not_you (a rival wins and you are absent), you_not_competitor, no_brands (no tracked brand appears, i.e. open space). Combine with 'competitors' to narrow the competitor side to specific rivals; on a negative cell that reads 'none of these'. On /dimensions/sources it applies to the crawled content of each cited page instead of the answer text. The legacy value 'competitors_only' is still accepted as an alias of competitor_not_you.
    #' @param citation_filter (optional) Same two-axis matrix applied to the domains cited in the answer instead of the brands named in it. Independent of mention_filter; pass both to intersect them (e.g. mentions_you + not_cites_you finds answers that talk about you without linking to you).
    #' @param competitors (optional) Comma-separated competitor IDs (unknown IDs return ERR_INVALID_PARAM)
    #' @param from (optional) No description
    #' @param to (optional) No description
    #' @param page (optional) No description (default value: 1)
    #' @param per_page (optional) No description (default value: 20)
    #' @param query (optional) Case-insensitive full-text search inside AI response texts. Switches items to snippet + match_count mode.
    #' @param ... Other optional arguments
    #'
    #' @return API response (void) with additional information such as HTTP status code, headers
    ListAnswersWithHttpInfo = function(project_id, model = NULL, collection_id = NULL, country_code = NULL, language_code = NULL, prompt = NULL, mention_filter = NULL, citation_filter = NULL, competitors = NULL, from = NULL, to = NULL, page = 1, per_page = 20, query = NULL, ...) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE

      if (missing(`project_id`)) {
        stop("Missing required parameter `project_id`.")
      }

      if (!missing(`project_id`) && is.null(`project_id`)) {
        stop("Invalid value for `project_id` when calling AnswersApi$ListAnswers, `project_id` is not nullable")
      }

      if (!missing(`model`) && is.null(`model`)) {
        stop("Invalid value for `model` when calling AnswersApi$ListAnswers, `model` is not nullable")
      }

      if (!missing(`collection_id`) && is.null(`collection_id`)) {
        stop("Invalid value for `collection_id` when calling AnswersApi$ListAnswers, `collection_id` is not nullable")
      }

      if (!missing(`country_code`) && is.null(`country_code`)) {
        stop("Invalid value for `country_code` when calling AnswersApi$ListAnswers, `country_code` is not nullable")
      }

      if (!missing(`language_code`) && is.null(`language_code`)) {
        stop("Invalid value for `language_code` when calling AnswersApi$ListAnswers, `language_code` is not nullable")
      }

      if (!missing(`prompt`) && is.null(`prompt`)) {
        stop("Invalid value for `prompt` when calling AnswersApi$ListAnswers, `prompt` is not nullable")
      }

      if (!missing(`mention_filter`) && is.null(`mention_filter`)) {
        stop("Invalid value for `mention_filter` when calling AnswersApi$ListAnswers, `mention_filter` is not nullable")
      }

      if (!missing(`citation_filter`) && is.null(`citation_filter`)) {
        stop("Invalid value for `citation_filter` when calling AnswersApi$ListAnswers, `citation_filter` is not nullable")
      }

      if (!missing(`competitors`) && is.null(`competitors`)) {
        stop("Invalid value for `competitors` when calling AnswersApi$ListAnswers, `competitors` is not nullable")
      }

      if (!missing(`from`) && is.null(`from`)) {
        stop("Invalid value for `from` when calling AnswersApi$ListAnswers, `from` is not nullable")
      }

      if (!missing(`to`) && is.null(`to`)) {
        stop("Invalid value for `to` when calling AnswersApi$ListAnswers, `to` is not nullable")
      }

      if (!missing(`page`) && is.null(`page`)) {
        stop("Invalid value for `page` when calling AnswersApi$ListAnswers, `page` is not nullable")
      }
      if (!is.null(`page`) && `page` <  1) {
        stop("Invalid value for `page` when calling AnswersApi$ListAnswers, must be bigger than or equal to 1.")
      }

      if (!missing(`per_page`) && is.null(`per_page`)) {
        stop("Invalid value for `per_page` when calling AnswersApi$ListAnswers, `per_page` is not nullable")
      }
      if (!is.null(`per_page`) && `per_page` >  100) {
        stop("Invalid value for `per_page` when calling AnswersApi$ListAnswers, must be smaller than or equal to 100.")
      }
      if (!is.null(`per_page`) && `per_page` <  1) {
        stop("Invalid value for `per_page` when calling AnswersApi$ListAnswers, must be bigger than or equal to 1.")
      }

      if (!missing(`query`) && is.null(`query`)) {
        stop("Invalid value for `query` when calling AnswersApi$ListAnswers, `query` is not nullable")
      }

      query_params[["project_id"]] <- `project_id`

      if (!is.null(`model`) && !(`model` %in% c("chatgpt", "perplexity", "gemini", "ai_overview", "ai_mode", "copilot", "claude", "grok", "deepseek", "meta_ai", "amazon_rufus"))) {
        stop("Invalid value for model when calling AnswersApi$ListAnswers. Must be [chatgpt, perplexity, gemini, ai_overview, ai_mode, copilot, claude, grok, deepseek, meta_ai, amazon_rufus].")
      }
      query_params[["model"]] <- `model`

      query_params[["collection_id"]] <- `collection_id`

      query_params[["country_code"]] <- `country_code`

      query_params[["language_code"]] <- `language_code`

      query_params[["prompt"]] <- `prompt`

      if (!is.null(`mention_filter`) && !(`mention_filter` %in% c("mentions_you", "not_mentions_you", "mentions_competitor", "not_mentions_competitor", "you_and_competitor", "competitor_not_you", "you_not_competitor", "no_brands"))) {
        stop("Invalid value for mention_filter when calling AnswersApi$ListAnswers. Must be [mentions_you, not_mentions_you, mentions_competitor, not_mentions_competitor, you_and_competitor, competitor_not_you, you_not_competitor, no_brands].")
      }
      query_params[["mention_filter"]] <- `mention_filter`

      if (!is.null(`citation_filter`) && !(`citation_filter` %in% c("cites_you", "not_cites_you", "cites_competitor", "not_cites_competitor", "you_and_competitor", "competitor_not_you", "you_not_competitor", "cites_no_brands"))) {
        stop("Invalid value for citation_filter when calling AnswersApi$ListAnswers. Must be [cites_you, not_cites_you, cites_competitor, not_cites_competitor, you_and_competitor, competitor_not_you, you_not_competitor, cites_no_brands].")
      }
      query_params[["citation_filter"]] <- `citation_filter`

      query_params[["competitors"]] <- `competitors`

      query_params[["from"]] <- `from`

      query_params[["to"]] <- `to`

      query_params[["page"]] <- `page`

      query_params[["per_page"]] <- `per_page`

      query_params[["query"]] <- `query`

      local_var_url_path <- "/answers"
      # Bearer token
      if (!is.null(self$api_client$bearer_token)) {
        header_params["Authorization"] <- paste("Bearer", self$api_client$bearer_token, sep = " ")
      }

      # The Accept request HTTP header
      local_var_accepts <- list("application/json")

      # The Content-Type representation header
      local_var_content_types <- list()

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "GET",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        local_var_resp$content <- NULL
        return(local_var_resp)
      } 
      
      local_var_error_msg <- local_var_resp$response_as_text()      
      if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        ApiResponse$new(content = paste("Server returned ", local_var_resp$status_code, " response status code."),
                        response = local_var_resp,
                        status_code = local_var_resp$status_code)
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        ApiResponse$new(content = "API client error",
                        response = local_var_resp,
                        status_code = local_var_resp$status_code)
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        if (is.null(local_var_resp$response) || all(local_var_resp$response == "")) {
          local_var_resp$response <- "API server error"
        }
        return(local_var_resp)
      }
    }
  )
)
