#' LLM Pulse API
#'
#' REST API client for LLM Pulse AI visibility analytics.
#'
#' The version of the OpenAPI document: 1.22.0
#' Contact: info@llmpulse.ai
#' Generated by: https://openapi-generator.tech
#'
#' @docType class
#' @title CitationIntelligence operations
#' @description CitationIntelligenceApi
#' @format An \code{R6Class} generator object
#' @field api_client Handles the client-server communication.
#'
#' @examples
#' \dontrun{
#' ####################  GetCitedUrlContent  ####################
#'
#' library(llmpulse)
#' var_project_id <- 56 # integer | Project ID
#' var_url_sha256 <- "url_sha256_example" # character | 64-character hex SHA-256 of the cited URL
#'
#' #Cited URL cached content
#' api_instance <- CitationIntelligenceApi$new()
#'
#' # Configure HTTP bearer authorization: BearerAuth
#' api_instance$api_client$bearer_token <- Sys.getenv("BEARER_TOKEN")
#'
#' api_instance$GetCitedUrlContent(var_project_id, var_url_sha256)
#'
#'
#' ####################  GetCitedUrlDetail  ####################
#'
#' library(llmpulse)
#' var_project_id <- 56 # integer | Project ID
#' var_url_sha256 <- "url_sha256_example" # character | 64-character hex SHA-256 of the cited URL
#'
#' #Cited URL detail
#' api_instance <- CitationIntelligenceApi$new()
#'
#' # Configure HTTP bearer authorization: BearerAuth
#' api_instance$api_client$bearer_token <- Sys.getenv("BEARER_TOKEN")
#'
#' api_instance$GetCitedUrlDetail(var_project_id, var_url_sha256)
#'
#'
#' ####################  GetMentionsByCitingDomain  ####################
#'
#' library(llmpulse)
#' var_project_id <- 56 # integer | Project ID
#' var_domains <- c("inner_example") # array[character] | Source domains to analyze, e.g. domains[]=gmac.com&domains[]=educaweb.com
#' var_model <- "model_example" # character | Filter by AI model. Models the API key's user has not enabled are silently dropped. (Optional)
#' var_collection_id <- 56 # integer |  (Optional)
#' var_country_code <- "country_code_example" # character | ISO country code (e.g. US, GB, DE) (Optional)
#' var_language_code <- "language_code_example" # character | ISO language code (e.g. en, es, de) (Optional)
#' var_prompt <- 56 # integer | Filter by prompt ID (Optional)
#' var_from <- "from_example" # character |  (Optional)
#' var_to <- "to_example" # character |  (Optional)
#'
#' #Mention share by citing domain
#' api_instance <- CitationIntelligenceApi$new()
#'
#' # Configure HTTP bearer authorization: BearerAuth
#' api_instance$api_client$bearer_token <- Sys.getenv("BEARER_TOKEN")
#'
#' api_instance$GetMentionsByCitingDomain(var_project_id, var_domains, model = var_model, collection_id = var_collection_id, country_code = var_country_code, language_code = var_language_code, prompt = var_prompt, from = var_from, to = var_to)
#'
#'
#' ####################  ListCitationGroups  ####################
#'
#' library(llmpulse)
#' var_project_id <- 56 # integer | Project ID
#' var_view <- "url" # character |  (Optional)
#' var_page <- 1 # integer |  (Optional)
#' var_per_page <- 20 # integer |  (Optional)
#' var_order <- "order_example" # character |  (Optional)
#' var_direction <- "direction_example" # character |  (Optional)
#' var_model <- "model_example" # character | Filter by AI model. Models the API key's user has not enabled are silently dropped. (Optional)
#' var_collection_id <- 56 # integer |  (Optional)
#' var_country_code <- "country_code_example" # character | ISO country code (e.g. US, GB, DE) (Optional)
#' var_language_code <- "language_code_example" # character | ISO language code (e.g. en, es, de) (Optional)
#' var_prompt <- 56 # integer | Filter by prompt ID (Optional)
#' var_from <- "from_example" # character |  (Optional)
#' var_to <- "to_example" # character |  (Optional)
#' var_query <- "query_example" # character |  (Optional)
#' var_source_type <- "source_type_example" # character |  (Optional)
#' var_sentiment <- "sentiment_example" # character |  (Optional)
#' var_content_gap <- "content_gap_example" # character |  (Optional)
#'
#' #Grouped citation intelligence
#' api_instance <- CitationIntelligenceApi$new()
#'
#' # Configure HTTP bearer authorization: BearerAuth
#' api_instance$api_client$bearer_token <- Sys.getenv("BEARER_TOKEN")
#'
#' api_instance$ListCitationGroups(var_project_id, view = var_view, page = var_page, per_page = var_per_page, order = var_order, direction = var_direction, model = var_model, collection_id = var_collection_id, country_code = var_country_code, language_code = var_language_code, prompt = var_prompt, from = var_from, to = var_to, query = var_query, source_type = var_source_type, sentiment = var_sentiment, content_gap = var_content_gap)
#'
#'
#' ####################  ListCitedUrlOccurrences  ####################
#'
#' library(llmpulse)
#' var_project_id <- 56 # integer | Project ID
#' var_url_sha256 <- "url_sha256_example" # character | 64-character hex SHA-256 of the cited URL
#' var_page <- 1 # integer |  (Optional)
#' var_per_page <- 20 # integer |  (Optional)
#'
#' #Cited URL occurrences
#' api_instance <- CitationIntelligenceApi$new()
#'
#' # Configure HTTP bearer authorization: BearerAuth
#' api_instance$api_client$bearer_token <- Sys.getenv("BEARER_TOKEN")
#'
#' api_instance$ListCitedUrlOccurrences(var_project_id, var_url_sha256, page = var_page, per_page = var_per_page)
#'
#'
#' }
#' @importFrom R6 R6Class
#' @importFrom base64enc base64encode
#' @export
CitationIntelligenceApi <- R6::R6Class(
  "CitationIntelligenceApi",
  public = list(
    api_client = NULL,

    #' @description
    #' Initialize a new CitationIntelligenceApi.
    #'
    #' @param api_client An instance of API client.
    initialize = function(api_client) {
      if (!missing(api_client)) {
        self$api_client <- api_client
      } else {
        self$api_client <- ApiClient$new()
      }
    },

    #' @description
    #' Cited URL cached content
    #'
    #' @param project_id Project ID
    #' @param url_sha256 64-character hex SHA-256 of the cited URL
    #' @param ... Other optional arguments
    #'
    #' @return void
    GetCitedUrlContent = function(project_id, url_sha256, ...) {
      local_var_response <- self$GetCitedUrlContentWithHttpInfo(project_id, url_sha256, ...)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        return(local_var_response$content)
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        return(local_var_response)
      }
    },

    #' @description
    #' Cited URL cached content
    #'
    #' @param project_id Project ID
    #' @param url_sha256 64-character hex SHA-256 of the cited URL
    #' @param ... Other optional arguments
    #'
    #' @return API response (void) with additional information such as HTTP status code, headers
    GetCitedUrlContentWithHttpInfo = function(project_id, url_sha256, ...) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE

      if (missing(`project_id`)) {
        stop("Missing required parameter `project_id`.")
      }

      if (missing(`url_sha256`)) {
        stop("Missing required parameter `url_sha256`.")
      }

      if (!missing(`project_id`) && is.null(`project_id`)) {
        stop("Invalid value for `project_id` when calling CitationIntelligenceApi$GetCitedUrlContent, `project_id` is not nullable")
      }

      if (!missing(`url_sha256`) && is.null(`url_sha256`)) {
        stop("Invalid value for `url_sha256` when calling CitationIntelligenceApi$GetCitedUrlContent, `url_sha256` is not nullable")
      }
      if (!is.null(`url_sha256`) && !stringr::str_detect(`url_sha256`, "^[a-f0-9]{64}$")) {
        stop("Invalid value for `url_sha256` when calling CitationIntelligenceApi$GetCitedUrlContent, must conform to the pattern ^[a-f0-9]{64}$.")
      }

      query_params[["project_id"]] <- `project_id`

      local_var_url_path <- "/citation_intelligence/urls/{url_sha256}/content"
      if (!missing(`url_sha256`)) {
        local_var_url_path <- gsub("\\{url_sha256\\}", URLencode(as.character(`url_sha256`), reserved = TRUE), local_var_url_path)
      }

      # Bearer token
      if (!is.null(self$api_client$bearer_token)) {
        header_params["Authorization"] <- paste("Bearer", self$api_client$bearer_token, sep = " ")
      }

      # The Accept request HTTP header
      local_var_accepts <- list("application/json")

      # The Content-Type representation header
      local_var_content_types <- list()

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "GET",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        local_var_resp$content <- NULL
        return(local_var_resp)
      } 
      
      local_var_error_msg <- local_var_resp$response_as_text()      
      if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        ApiResponse$new(content = paste("Server returned ", local_var_resp$status_code, " response status code."),
                        response = local_var_resp,
                        status_code = local_var_resp$status_code)
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        ApiResponse$new(content = "API client error",
                        response = local_var_resp,
                        status_code = local_var_resp$status_code)
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        if (is.null(local_var_resp$response) || all(local_var_resp$response == "")) {
          local_var_resp$response <- "API server error"
        }
        return(local_var_resp)
      }
    },

    #' @description
    #' Cited URL detail
    #'
    #' @param project_id Project ID
    #' @param url_sha256 64-character hex SHA-256 of the cited URL
    #' @param ... Other optional arguments
    #'
    #' @return void
    GetCitedUrlDetail = function(project_id, url_sha256, ...) {
      local_var_response <- self$GetCitedUrlDetailWithHttpInfo(project_id, url_sha256, ...)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        return(local_var_response$content)
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        return(local_var_response)
      }
    },

    #' @description
    #' Cited URL detail
    #'
    #' @param project_id Project ID
    #' @param url_sha256 64-character hex SHA-256 of the cited URL
    #' @param ... Other optional arguments
    #'
    #' @return API response (void) with additional information such as HTTP status code, headers
    GetCitedUrlDetailWithHttpInfo = function(project_id, url_sha256, ...) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE

      if (missing(`project_id`)) {
        stop("Missing required parameter `project_id`.")
      }

      if (missing(`url_sha256`)) {
        stop("Missing required parameter `url_sha256`.")
      }

      if (!missing(`project_id`) && is.null(`project_id`)) {
        stop("Invalid value for `project_id` when calling CitationIntelligenceApi$GetCitedUrlDetail, `project_id` is not nullable")
      }

      if (!missing(`url_sha256`) && is.null(`url_sha256`)) {
        stop("Invalid value for `url_sha256` when calling CitationIntelligenceApi$GetCitedUrlDetail, `url_sha256` is not nullable")
      }
      if (!is.null(`url_sha256`) && !stringr::str_detect(`url_sha256`, "^[a-f0-9]{64}$")) {
        stop("Invalid value for `url_sha256` when calling CitationIntelligenceApi$GetCitedUrlDetail, must conform to the pattern ^[a-f0-9]{64}$.")
      }

      query_params[["project_id"]] <- `project_id`

      local_var_url_path <- "/citation_intelligence/urls/{url_sha256}"
      if (!missing(`url_sha256`)) {
        local_var_url_path <- gsub("\\{url_sha256\\}", URLencode(as.character(`url_sha256`), reserved = TRUE), local_var_url_path)
      }

      # Bearer token
      if (!is.null(self$api_client$bearer_token)) {
        header_params["Authorization"] <- paste("Bearer", self$api_client$bearer_token, sep = " ")
      }

      # The Accept request HTTP header
      local_var_accepts <- list("application/json")

      # The Content-Type representation header
      local_var_content_types <- list()

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "GET",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        local_var_resp$content <- NULL
        return(local_var_resp)
      } 
      
      local_var_error_msg <- local_var_resp$response_as_text()      
      if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        ApiResponse$new(content = paste("Server returned ", local_var_resp$status_code, " response status code."),
                        response = local_var_resp,
                        status_code = local_var_resp$status_code)
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        ApiResponse$new(content = "API client error",
                        response = local_var_resp,
                        status_code = local_var_resp$status_code)
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        if (is.null(local_var_resp$response) || all(local_var_resp$response == "")) {
          local_var_resp$response <- "API server error"
        }
        return(local_var_resp)
      }
    },

    #' @description
    #' Mention share by citing domain
    #'
    #' @param project_id Project ID
    #' @param domains Source domains to analyze, e.g. domains[]=gmac.com&domains[]=educaweb.com
    #' @param model (optional) Filter by AI model. Models the API key's user has not enabled are silently dropped.
    #' @param collection_id (optional) No description
    #' @param country_code (optional) ISO country code (e.g. US, GB, DE)
    #' @param language_code (optional) ISO language code (e.g. en, es, de)
    #' @param prompt (optional) Filter by prompt ID
    #' @param from (optional) No description
    #' @param to (optional) No description
    #' @param ... Other optional arguments
    #'
    #' @return void
    GetMentionsByCitingDomain = function(project_id, domains, model = NULL, collection_id = NULL, country_code = NULL, language_code = NULL, prompt = NULL, from = NULL, to = NULL, ...) {
      local_var_response <- self$GetMentionsByCitingDomainWithHttpInfo(project_id, domains, model, collection_id, country_code, language_code, prompt, from, to, ...)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        return(local_var_response$content)
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        return(local_var_response)
      }
    },

    #' @description
    #' Mention share by citing domain
    #'
    #' @param project_id Project ID
    #' @param domains Source domains to analyze, e.g. domains[]=gmac.com&domains[]=educaweb.com
    #' @param model (optional) Filter by AI model. Models the API key's user has not enabled are silently dropped.
    #' @param collection_id (optional) No description
    #' @param country_code (optional) ISO country code (e.g. US, GB, DE)
    #' @param language_code (optional) ISO language code (e.g. en, es, de)
    #' @param prompt (optional) Filter by prompt ID
    #' @param from (optional) No description
    #' @param to (optional) No description
    #' @param ... Other optional arguments
    #'
    #' @return API response (void) with additional information such as HTTP status code, headers
    GetMentionsByCitingDomainWithHttpInfo = function(project_id, domains, model = NULL, collection_id = NULL, country_code = NULL, language_code = NULL, prompt = NULL, from = NULL, to = NULL, ...) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE

      if (missing(`project_id`)) {
        stop("Missing required parameter `project_id`.")
      }

      if (missing(`domains`)) {
        stop("Missing required parameter `domains`.")
      }

      if (!missing(`project_id`) && is.null(`project_id`)) {
        stop("Invalid value for `project_id` when calling CitationIntelligenceApi$GetMentionsByCitingDomain, `project_id` is not nullable")
      }

      if (!missing(`domains`) && is.null(`domains`)) {
        stop("Invalid value for `domains` when calling CitationIntelligenceApi$GetMentionsByCitingDomain, `domains` is not nullable")
      }

      if (!missing(`model`) && is.null(`model`)) {
        stop("Invalid value for `model` when calling CitationIntelligenceApi$GetMentionsByCitingDomain, `model` is not nullable")
      }

      if (!missing(`collection_id`) && is.null(`collection_id`)) {
        stop("Invalid value for `collection_id` when calling CitationIntelligenceApi$GetMentionsByCitingDomain, `collection_id` is not nullable")
      }

      if (!missing(`country_code`) && is.null(`country_code`)) {
        stop("Invalid value for `country_code` when calling CitationIntelligenceApi$GetMentionsByCitingDomain, `country_code` is not nullable")
      }

      if (!missing(`language_code`) && is.null(`language_code`)) {
        stop("Invalid value for `language_code` when calling CitationIntelligenceApi$GetMentionsByCitingDomain, `language_code` is not nullable")
      }

      if (!missing(`prompt`) && is.null(`prompt`)) {
        stop("Invalid value for `prompt` when calling CitationIntelligenceApi$GetMentionsByCitingDomain, `prompt` is not nullable")
      }

      if (!missing(`from`) && is.null(`from`)) {
        stop("Invalid value for `from` when calling CitationIntelligenceApi$GetMentionsByCitingDomain, `from` is not nullable")
      }

      if (!missing(`to`) && is.null(`to`)) {
        stop("Invalid value for `to` when calling CitationIntelligenceApi$GetMentionsByCitingDomain, `to` is not nullable")
      }

      query_params[["project_id"]] <- `project_id`

      # explore
      for (query_item in `domains`) {
        query_params[["domains"]] <- c(query_params[["domains"]], list(`domains` = query_item))
      }

      if (!is.null(`model`) && !(`model` %in% c("chatgpt", "perplexity", "gemini", "ai_overview", "ai_mode", "copilot", "claude", "grok", "deepseek", "meta_ai", "amazon_rufus"))) {
        stop("Invalid value for model when calling CitationIntelligenceApi$GetMentionsByCitingDomain. Must be [chatgpt, perplexity, gemini, ai_overview, ai_mode, copilot, claude, grok, deepseek, meta_ai, amazon_rufus].")
      }
      query_params[["model"]] <- `model`

      query_params[["collection_id"]] <- `collection_id`

      query_params[["country_code"]] <- `country_code`

      query_params[["language_code"]] <- `language_code`

      query_params[["prompt"]] <- `prompt`

      query_params[["from"]] <- `from`

      query_params[["to"]] <- `to`

      local_var_url_path <- "/citation_intelligence/mentions_by_domain"
      # Bearer token
      if (!is.null(self$api_client$bearer_token)) {
        header_params["Authorization"] <- paste("Bearer", self$api_client$bearer_token, sep = " ")
      }

      # The Accept request HTTP header
      local_var_accepts <- list("application/json")

      # The Content-Type representation header
      local_var_content_types <- list()

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "GET",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        local_var_resp$content <- NULL
        return(local_var_resp)
      } 
      
      local_var_error_msg <- local_var_resp$response_as_text()      
      if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        ApiResponse$new(content = paste("Server returned ", local_var_resp$status_code, " response status code."),
                        response = local_var_resp,
                        status_code = local_var_resp$status_code)
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        ApiResponse$new(content = "API client error",
                        response = local_var_resp,
                        status_code = local_var_resp$status_code)
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        if (is.null(local_var_resp$response) || all(local_var_resp$response == "")) {
          local_var_resp$response <- "API server error"
        }
        return(local_var_resp)
      }
    },

    #' @description
    #' Grouped citation intelligence
    #'
    #' @param project_id Project ID
    #' @param view (optional) No description (default value: "url")
    #' @param page (optional) No description (default value: 1)
    #' @param per_page (optional) No description (default value: 20)
    #' @param order (optional) No description
    #' @param direction (optional) No description
    #' @param model (optional) Filter by AI model. Models the API key's user has not enabled are silently dropped.
    #' @param collection_id (optional) No description
    #' @param country_code (optional) ISO country code (e.g. US, GB, DE)
    #' @param language_code (optional) ISO language code (e.g. en, es, de)
    #' @param prompt (optional) Filter by prompt ID
    #' @param from (optional) No description
    #' @param to (optional) No description
    #' @param query (optional) No description
    #' @param source_type (optional) No description
    #' @param sentiment (optional) No description
    #' @param content_gap (optional) No description
    #' @param ... Other optional arguments
    #'
    #' @return void
    ListCitationGroups = function(project_id, view = "url", page = 1, per_page = 20, order = NULL, direction = NULL, model = NULL, collection_id = NULL, country_code = NULL, language_code = NULL, prompt = NULL, from = NULL, to = NULL, query = NULL, source_type = NULL, sentiment = NULL, content_gap = NULL, ...) {
      local_var_response <- self$ListCitationGroupsWithHttpInfo(project_id, view, page, per_page, order, direction, model, collection_id, country_code, language_code, prompt, from, to, query, source_type, sentiment, content_gap, ...)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        return(local_var_response$content)
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        return(local_var_response)
      }
    },

    #' @description
    #' Grouped citation intelligence
    #'
    #' @param project_id Project ID
    #' @param view (optional) No description (default value: "url")
    #' @param page (optional) No description (default value: 1)
    #' @param per_page (optional) No description (default value: 20)
    #' @param order (optional) No description
    #' @param direction (optional) No description
    #' @param model (optional) Filter by AI model. Models the API key's user has not enabled are silently dropped.
    #' @param collection_id (optional) No description
    #' @param country_code (optional) ISO country code (e.g. US, GB, DE)
    #' @param language_code (optional) ISO language code (e.g. en, es, de)
    #' @param prompt (optional) Filter by prompt ID
    #' @param from (optional) No description
    #' @param to (optional) No description
    #' @param query (optional) No description
    #' @param source_type (optional) No description
    #' @param sentiment (optional) No description
    #' @param content_gap (optional) No description
    #' @param ... Other optional arguments
    #'
    #' @return API response (void) with additional information such as HTTP status code, headers
    ListCitationGroupsWithHttpInfo = function(project_id, view = "url", page = 1, per_page = 20, order = NULL, direction = NULL, model = NULL, collection_id = NULL, country_code = NULL, language_code = NULL, prompt = NULL, from = NULL, to = NULL, query = NULL, source_type = NULL, sentiment = NULL, content_gap = NULL, ...) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE

      if (missing(`project_id`)) {
        stop("Missing required parameter `project_id`.")
      }

      if (!missing(`project_id`) && is.null(`project_id`)) {
        stop("Invalid value for `project_id` when calling CitationIntelligenceApi$ListCitationGroups, `project_id` is not nullable")
      }

      if (!missing(`view`) && is.null(`view`)) {
        stop("Invalid value for `view` when calling CitationIntelligenceApi$ListCitationGroups, `view` is not nullable")
      }

      if (!missing(`page`) && is.null(`page`)) {
        stop("Invalid value for `page` when calling CitationIntelligenceApi$ListCitationGroups, `page` is not nullable")
      }
      if (!is.null(`page`) && `page` <  1) {
        stop("Invalid value for `page` when calling CitationIntelligenceApi$ListCitationGroups, must be bigger than or equal to 1.")
      }

      if (!missing(`per_page`) && is.null(`per_page`)) {
        stop("Invalid value for `per_page` when calling CitationIntelligenceApi$ListCitationGroups, `per_page` is not nullable")
      }
      if (!is.null(`per_page`) && `per_page` >  100) {
        stop("Invalid value for `per_page` when calling CitationIntelligenceApi$ListCitationGroups, must be smaller than or equal to 100.")
      }
      if (!is.null(`per_page`) && `per_page` <  1) {
        stop("Invalid value for `per_page` when calling CitationIntelligenceApi$ListCitationGroups, must be bigger than or equal to 1.")
      }

      if (!missing(`order`) && is.null(`order`)) {
        stop("Invalid value for `order` when calling CitationIntelligenceApi$ListCitationGroups, `order` is not nullable")
      }

      if (!missing(`direction`) && is.null(`direction`)) {
        stop("Invalid value for `direction` when calling CitationIntelligenceApi$ListCitationGroups, `direction` is not nullable")
      }

      if (!missing(`model`) && is.null(`model`)) {
        stop("Invalid value for `model` when calling CitationIntelligenceApi$ListCitationGroups, `model` is not nullable")
      }

      if (!missing(`collection_id`) && is.null(`collection_id`)) {
        stop("Invalid value for `collection_id` when calling CitationIntelligenceApi$ListCitationGroups, `collection_id` is not nullable")
      }

      if (!missing(`country_code`) && is.null(`country_code`)) {
        stop("Invalid value for `country_code` when calling CitationIntelligenceApi$ListCitationGroups, `country_code` is not nullable")
      }

      if (!missing(`language_code`) && is.null(`language_code`)) {
        stop("Invalid value for `language_code` when calling CitationIntelligenceApi$ListCitationGroups, `language_code` is not nullable")
      }

      if (!missing(`prompt`) && is.null(`prompt`)) {
        stop("Invalid value for `prompt` when calling CitationIntelligenceApi$ListCitationGroups, `prompt` is not nullable")
      }

      if (!missing(`from`) && is.null(`from`)) {
        stop("Invalid value for `from` when calling CitationIntelligenceApi$ListCitationGroups, `from` is not nullable")
      }

      if (!missing(`to`) && is.null(`to`)) {
        stop("Invalid value for `to` when calling CitationIntelligenceApi$ListCitationGroups, `to` is not nullable")
      }

      if (!missing(`query`) && is.null(`query`)) {
        stop("Invalid value for `query` when calling CitationIntelligenceApi$ListCitationGroups, `query` is not nullable")
      }

      if (!missing(`source_type`) && is.null(`source_type`)) {
        stop("Invalid value for `source_type` when calling CitationIntelligenceApi$ListCitationGroups, `source_type` is not nullable")
      }

      if (!missing(`sentiment`) && is.null(`sentiment`)) {
        stop("Invalid value for `sentiment` when calling CitationIntelligenceApi$ListCitationGroups, `sentiment` is not nullable")
      }

      if (!missing(`content_gap`) && is.null(`content_gap`)) {
        stop("Invalid value for `content_gap` when calling CitationIntelligenceApi$ListCitationGroups, `content_gap` is not nullable")
      }

      query_params[["project_id"]] <- `project_id`

      if (!is.null(`view`) && !(`view` %in% c("url", "domain", "host"))) {
        stop("Invalid value for view when calling CitationIntelligenceApi$ListCitationGroups. Must be [url, domain, host].")
      }
      query_params[["view"]] <- `view`

      query_params[["page"]] <- `page`

      query_params[["per_page"]] <- `per_page`

      if (!is.null(`order`) && !(`order` %in% c("group_key", "total_responses", "total_citations", "citation_rate", "avg_citation_position", "first_seen_at", "last_seen_at"))) {
        stop("Invalid value for order when calling CitationIntelligenceApi$ListCitationGroups. Must be [group_key, total_responses, total_citations, citation_rate, avg_citation_position, first_seen_at, last_seen_at].")
      }
      query_params[["order"]] <- `order`

      if (!is.null(`direction`) && !(`direction` %in% c("asc", "desc"))) {
        stop("Invalid value for direction when calling CitationIntelligenceApi$ListCitationGroups. Must be [asc, desc].")
      }
      query_params[["direction"]] <- `direction`

      if (!is.null(`model`) && !(`model` %in% c("chatgpt", "perplexity", "gemini", "ai_overview", "ai_mode", "copilot", "claude", "grok", "deepseek", "meta_ai", "amazon_rufus"))) {
        stop("Invalid value for model when calling CitationIntelligenceApi$ListCitationGroups. Must be [chatgpt, perplexity, gemini, ai_overview, ai_mode, copilot, claude, grok, deepseek, meta_ai, amazon_rufus].")
      }
      query_params[["model"]] <- `model`

      query_params[["collection_id"]] <- `collection_id`

      query_params[["country_code"]] <- `country_code`

      query_params[["language_code"]] <- `language_code`

      query_params[["prompt"]] <- `prompt`

      query_params[["from"]] <- `from`

      query_params[["to"]] <- `to`

      query_params[["query"]] <- `query`

      if (!is.null(`source_type`) && !(`source_type` %in% c("owned", "competitor", "third_party", "social_media", "own_domain", "ugc", "background"))) {
        stop("Invalid value for source_type when calling CitationIntelligenceApi$ListCitationGroups. Must be [owned, competitor, third_party, social_media, own_domain, ugc, background].")
      }
      query_params[["source_type"]] <- `source_type`

      if (!is.null(`sentiment`) && !(`sentiment` %in% c("negative"))) {
        stop("Invalid value for sentiment when calling CitationIntelligenceApi$ListCitationGroups. Must be [negative].")
      }
      query_params[["sentiment"]] <- `sentiment`

      if (!is.null(`content_gap`) && !(`content_gap` %in% c("mentioned", "gap"))) {
        stop("Invalid value for content_gap when calling CitationIntelligenceApi$ListCitationGroups. Must be [mentioned, gap].")
      }
      query_params[["content_gap"]] <- `content_gap`

      local_var_url_path <- "/citation_intelligence/groups"
      # Bearer token
      if (!is.null(self$api_client$bearer_token)) {
        header_params["Authorization"] <- paste("Bearer", self$api_client$bearer_token, sep = " ")
      }

      # The Accept request HTTP header
      local_var_accepts <- list("application/json")

      # The Content-Type representation header
      local_var_content_types <- list()

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "GET",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        local_var_resp$content <- NULL
        return(local_var_resp)
      } 
      
      local_var_error_msg <- local_var_resp$response_as_text()      
      if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        ApiResponse$new(content = paste("Server returned ", local_var_resp$status_code, " response status code."),
                        response = local_var_resp,
                        status_code = local_var_resp$status_code)
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        ApiResponse$new(content = "API client error",
                        response = local_var_resp,
                        status_code = local_var_resp$status_code)
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        if (is.null(local_var_resp$response) || all(local_var_resp$response == "")) {
          local_var_resp$response <- "API server error"
        }
        return(local_var_resp)
      }
    },

    #' @description
    #' Cited URL occurrences
    #'
    #' @param project_id Project ID
    #' @param url_sha256 64-character hex SHA-256 of the cited URL
    #' @param page (optional) No description (default value: 1)
    #' @param per_page (optional) No description (default value: 20)
    #' @param ... Other optional arguments
    #'
    #' @return void
    ListCitedUrlOccurrences = function(project_id, url_sha256, page = 1, per_page = 20, ...) {
      local_var_response <- self$ListCitedUrlOccurrencesWithHttpInfo(project_id, url_sha256, page, per_page, ...)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        return(local_var_response$content)
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        return(local_var_response)
      }
    },

    #' @description
    #' Cited URL occurrences
    #'
    #' @param project_id Project ID
    #' @param url_sha256 64-character hex SHA-256 of the cited URL
    #' @param page (optional) No description (default value: 1)
    #' @param per_page (optional) No description (default value: 20)
    #' @param ... Other optional arguments
    #'
    #' @return API response (void) with additional information such as HTTP status code, headers
    ListCitedUrlOccurrencesWithHttpInfo = function(project_id, url_sha256, page = 1, per_page = 20, ...) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE

      if (missing(`project_id`)) {
        stop("Missing required parameter `project_id`.")
      }

      if (missing(`url_sha256`)) {
        stop("Missing required parameter `url_sha256`.")
      }

      if (!missing(`project_id`) && is.null(`project_id`)) {
        stop("Invalid value for `project_id` when calling CitationIntelligenceApi$ListCitedUrlOccurrences, `project_id` is not nullable")
      }

      if (!missing(`url_sha256`) && is.null(`url_sha256`)) {
        stop("Invalid value for `url_sha256` when calling CitationIntelligenceApi$ListCitedUrlOccurrences, `url_sha256` is not nullable")
      }
      if (!is.null(`url_sha256`) && !stringr::str_detect(`url_sha256`, "^[a-f0-9]{64}$")) {
        stop("Invalid value for `url_sha256` when calling CitationIntelligenceApi$ListCitedUrlOccurrences, must conform to the pattern ^[a-f0-9]{64}$.")
      }

      if (!missing(`page`) && is.null(`page`)) {
        stop("Invalid value for `page` when calling CitationIntelligenceApi$ListCitedUrlOccurrences, `page` is not nullable")
      }
      if (!is.null(`page`) && `page` <  1) {
        stop("Invalid value for `page` when calling CitationIntelligenceApi$ListCitedUrlOccurrences, must be bigger than or equal to 1.")
      }

      if (!missing(`per_page`) && is.null(`per_page`)) {
        stop("Invalid value for `per_page` when calling CitationIntelligenceApi$ListCitedUrlOccurrences, `per_page` is not nullable")
      }
      if (!is.null(`per_page`) && `per_page` >  100) {
        stop("Invalid value for `per_page` when calling CitationIntelligenceApi$ListCitedUrlOccurrences, must be smaller than or equal to 100.")
      }
      if (!is.null(`per_page`) && `per_page` <  1) {
        stop("Invalid value for `per_page` when calling CitationIntelligenceApi$ListCitedUrlOccurrences, must be bigger than or equal to 1.")
      }

      query_params[["project_id"]] <- `project_id`

      query_params[["page"]] <- `page`

      query_params[["per_page"]] <- `per_page`

      local_var_url_path <- "/citation_intelligence/urls/{url_sha256}/occurrences"
      if (!missing(`url_sha256`)) {
        local_var_url_path <- gsub("\\{url_sha256\\}", URLencode(as.character(`url_sha256`), reserved = TRUE), local_var_url_path)
      }

      # Bearer token
      if (!is.null(self$api_client$bearer_token)) {
        header_params["Authorization"] <- paste("Bearer", self$api_client$bearer_token, sep = " ")
      }

      # The Accept request HTTP header
      local_var_accepts <- list("application/json")

      # The Content-Type representation header
      local_var_content_types <- list()

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "GET",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        local_var_resp$content <- NULL
        return(local_var_resp)
      } 
      
      local_var_error_msg <- local_var_resp$response_as_text()      
      if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        ApiResponse$new(content = paste("Server returned ", local_var_resp$status_code, " response status code."),
                        response = local_var_resp,
                        status_code = local_var_resp$status_code)
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        ApiResponse$new(content = "API client error",
                        response = local_var_resp,
                        status_code = local_var_resp$status_code)
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        if (is.null(local_var_resp$response) || all(local_var_resp$response == "")) {
          local_var_resp$response <- "API server error"
        }
        return(local_var_resp)
      }
    }
  )
)
