#' LLM Pulse API
#'
#' REST API client for LLM Pulse AI visibility analytics.
#'
#' The version of the OpenAPI document: 1.46.0
#' Contact: info@llmpulse.ai
#' Generated by: https://openapi-generator.tech
#'
#' @docType class
#' @title CollectionsTags operations
#' @description CollectionsTagsApi
#' @format An \code{R6Class} generator object
#' @field api_client Handles the client-server communication.
#'
#' @examples
#' \dontrun{
#' ####################  AssignPromptTags  ####################
#'
#' library(llmpulse)
#' var_assign_prompt_tags_request <- assignPromptTags_request$new(123, c(123), c(123), c("tag_names_example"), "create_missing_example") # AssignPromptTagsRequest | 
#'
#' #Bulk-attach tags to prompts
#' api_instance <- CollectionsTagsApi$new()
#'
#' # Configure HTTP bearer authorization: BearerAuth
#' api_instance$api_client$bearer_token <- Sys.getenv("BEARER_TOKEN")
#'
#' api_instance$AssignPromptTags(var_assign_prompt_tags_request)
#'
#'
#' ####################  CreateCollection  ####################
#'
#' library(llmpulse)
#' var_create_collection_request <- createCollection_request$new(123, "name_example", "description_example", c(123)) # CreateCollectionRequest | 
#'
#' #Create a tag
#' api_instance <- CollectionsTagsApi$new()
#'
#' # Configure HTTP bearer authorization: BearerAuth
#' api_instance$api_client$bearer_token <- Sys.getenv("BEARER_TOKEN")
#'
#' api_instance$CreateCollection(var_create_collection_request)
#'
#'
#' ####################  DeleteCollection  ####################
#'
#' library(llmpulse)
#' var_project_id <- 56 # integer | Project ID
#' var_id <- 56 # integer | 
#'
#' #Delete a tag
#' api_instance <- CollectionsTagsApi$new()
#'
#' # Configure HTTP bearer authorization: BearerAuth
#' api_instance$api_client$bearer_token <- Sys.getenv("BEARER_TOKEN")
#'
#' api_instance$DeleteCollection(var_project_id, var_id)
#'
#'
#' ####################  ListCollections  ####################
#'
#' library(llmpulse)
#' var_project_id <- 56 # integer | Project ID
#' var_output <- "output_example" # character | Rectangular output for BI tools (Tableau, Excel, Sheets, ELT). Omit for the default nested JSON. 'flat' returns the same metadata plus 'columns' and 'rows'; 'csv' returns those rows as text/csv. Errors are always returned as JSON. (Optional)
#'
#' #List tags/collections
#' api_instance <- CollectionsTagsApi$new()
#'
#' # Configure HTTP bearer authorization: BearerAuth
#' api_instance$api_client$bearer_token <- Sys.getenv("BEARER_TOKEN")
#'
#' api_instance$ListCollections(var_project_id, output = var_output)
#'
#'
#' ####################  ListTags  ####################
#'
#' library(llmpulse)
#' var_project_id <- 56 # integer | Project ID
#' var_output <- "output_example" # character | Rectangular output for BI tools (Tableau, Excel, Sheets, ELT). Omit for the default nested JSON. 'flat' returns the same metadata plus 'columns' and 'rows'; 'csv' returns those rows as text/csv. Errors are always returned as JSON. (Optional)
#'
#' #List tags (alias for /collections)
#' api_instance <- CollectionsTagsApi$new()
#'
#' # Configure HTTP bearer authorization: BearerAuth
#' api_instance$api_client$bearer_token <- Sys.getenv("BEARER_TOKEN")
#'
#' api_instance$ListTags(var_project_id, output = var_output)
#'
#'
#' ####################  UpdateCollection  ####################
#'
#' library(llmpulse)
#' var_id <- 56 # integer | 
#' var_update_collection_request <- updateCollection_request$new(123, "name_example", "description_example") # UpdateCollectionRequest | 
#'
#' #Update a tag
#' api_instance <- CollectionsTagsApi$new()
#'
#' # Configure HTTP bearer authorization: BearerAuth
#' api_instance$api_client$bearer_token <- Sys.getenv("BEARER_TOKEN")
#'
#' api_instance$UpdateCollection(var_id, var_update_collection_request)
#'
#'
#' }
#' @importFrom R6 R6Class
#' @importFrom base64enc base64encode
#' @export
CollectionsTagsApi <- R6::R6Class(
  "CollectionsTagsApi",
  public = list(
    api_client = NULL,

    #' @description
    #' Initialize a new CollectionsTagsApi.
    #'
    #' @param api_client An instance of API client.
    initialize = function(api_client) {
      if (!missing(api_client)) {
        self$api_client <- api_client
      } else {
        self$api_client <- ApiClient$new()
      }
    },

    #' @description
    #' Bulk-attach tags to prompts
    #'
    #' @param assign_prompt_tags_request 
    #' @param ... Other optional arguments
    #'
    #' @return void
    AssignPromptTags = function(assign_prompt_tags_request, ...) {
      local_var_response <- self$AssignPromptTagsWithHttpInfo(assign_prompt_tags_request, ...)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        return(local_var_response$content)
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        return(local_var_response)
      }
    },

    #' @description
    #' Bulk-attach tags to prompts
    #'
    #' @param assign_prompt_tags_request 
    #' @param ... Other optional arguments
    #'
    #' @return API response (void) with additional information such as HTTP status code, headers
    AssignPromptTagsWithHttpInfo = function(assign_prompt_tags_request, ...) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE

      if (missing(`assign_prompt_tags_request`)) {
        stop("Missing required parameter `assign_prompt_tags_request`.")
      }

      if (!missing(`assign_prompt_tags_request`) && is.null(`assign_prompt_tags_request`)) {
        stop("Invalid value for `assign_prompt_tags_request` when calling CollectionsTagsApi$AssignPromptTags, `assign_prompt_tags_request` is not nullable")
      }

      if (!is.null(`assign_prompt_tags_request`)) {
        local_var_body <- `assign_prompt_tags_request`$toJSONString()
      } else {
        local_var_body <- NULL
      }

      local_var_url_path <- "/prompts/assign_tags"
      # Bearer token
      if (!is.null(self$api_client$bearer_token)) {
        header_params["Authorization"] <- paste("Bearer", self$api_client$bearer_token, sep = " ")
      }

      # The Accept request HTTP header
      local_var_accepts <- list("application/json")

      # The Content-Type representation header
      local_var_content_types <- list("application/json")

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "POST",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        local_var_resp$content <- NULL
        return(local_var_resp)
      } 
      
      local_var_error_msg <- local_var_resp$response_as_text()      
      if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        ApiResponse$new(content = paste("Server returned ", local_var_resp$status_code, " response status code."),
                        response = local_var_resp,
                        status_code = local_var_resp$status_code)
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        ApiResponse$new(content = "API client error",
                        response = local_var_resp,
                        status_code = local_var_resp$status_code)
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        if (is.null(local_var_resp$response) || all(local_var_resp$response == "")) {
          local_var_resp$response <- "API server error"
        }
        return(local_var_resp)
      }
    },

    #' @description
    #' Create a tag
    #'
    #' @param create_collection_request 
    #' @param ... Other optional arguments
    #'
    #' @return void
    CreateCollection = function(create_collection_request, ...) {
      local_var_response <- self$CreateCollectionWithHttpInfo(create_collection_request, ...)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        return(local_var_response$content)
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        return(local_var_response)
      }
    },

    #' @description
    #' Create a tag
    #'
    #' @param create_collection_request 
    #' @param ... Other optional arguments
    #'
    #' @return API response (void) with additional information such as HTTP status code, headers
    CreateCollectionWithHttpInfo = function(create_collection_request, ...) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE

      if (missing(`create_collection_request`)) {
        stop("Missing required parameter `create_collection_request`.")
      }

      if (!missing(`create_collection_request`) && is.null(`create_collection_request`)) {
        stop("Invalid value for `create_collection_request` when calling CollectionsTagsApi$CreateCollection, `create_collection_request` is not nullable")
      }

      if (!is.null(`create_collection_request`)) {
        local_var_body <- `create_collection_request`$toJSONString()
      } else {
        local_var_body <- NULL
      }

      local_var_url_path <- "/collections"
      # Bearer token
      if (!is.null(self$api_client$bearer_token)) {
        header_params["Authorization"] <- paste("Bearer", self$api_client$bearer_token, sep = " ")
      }

      # The Accept request HTTP header
      local_var_accepts <- list("application/json")

      # The Content-Type representation header
      local_var_content_types <- list("application/json")

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "POST",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        local_var_resp$content <- NULL
        return(local_var_resp)
      } 
      
      local_var_error_msg <- local_var_resp$response_as_text()      
      if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        ApiResponse$new(content = paste("Server returned ", local_var_resp$status_code, " response status code."),
                        response = local_var_resp,
                        status_code = local_var_resp$status_code)
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        ApiResponse$new(content = "API client error",
                        response = local_var_resp,
                        status_code = local_var_resp$status_code)
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        if (is.null(local_var_resp$response) || all(local_var_resp$response == "")) {
          local_var_resp$response <- "API server error"
        }
        return(local_var_resp)
      }
    },

    #' @description
    #' Delete a tag
    #'
    #' @param project_id Project ID
    #' @param id 
    #' @param ... Other optional arguments
    #'
    #' @return void
    DeleteCollection = function(project_id, id, ...) {
      local_var_response <- self$DeleteCollectionWithHttpInfo(project_id, id, ...)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        return(local_var_response$content)
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        return(local_var_response)
      }
    },

    #' @description
    #' Delete a tag
    #'
    #' @param project_id Project ID
    #' @param id 
    #' @param ... Other optional arguments
    #'
    #' @return API response (void) with additional information such as HTTP status code, headers
    DeleteCollectionWithHttpInfo = function(project_id, id, ...) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE

      if (missing(`project_id`)) {
        stop("Missing required parameter `project_id`.")
      }

      if (missing(`id`)) {
        stop("Missing required parameter `id`.")
      }

      if (!missing(`project_id`) && is.null(`project_id`)) {
        stop("Invalid value for `project_id` when calling CollectionsTagsApi$DeleteCollection, `project_id` is not nullable")
      }

      if (!missing(`id`) && is.null(`id`)) {
        stop("Invalid value for `id` when calling CollectionsTagsApi$DeleteCollection, `id` is not nullable")
      }

      query_params[["project_id"]] <- `project_id`

      local_var_url_path <- "/collections/{id}"
      if (!missing(`id`)) {
        local_var_url_path <- gsub("\\{id\\}", URLencode(as.character(`id`), reserved = TRUE), local_var_url_path)
      }

      # Bearer token
      if (!is.null(self$api_client$bearer_token)) {
        header_params["Authorization"] <- paste("Bearer", self$api_client$bearer_token, sep = " ")
      }

      # The Accept request HTTP header
      local_var_accepts <- list("application/json")

      # The Content-Type representation header
      local_var_content_types <- list()

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "DELETE",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        local_var_resp$content <- NULL
        return(local_var_resp)
      } 
      
      local_var_error_msg <- local_var_resp$response_as_text()      
      if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        ApiResponse$new(content = paste("Server returned ", local_var_resp$status_code, " response status code."),
                        response = local_var_resp,
                        status_code = local_var_resp$status_code)
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        ApiResponse$new(content = "API client error",
                        response = local_var_resp,
                        status_code = local_var_resp$status_code)
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        if (is.null(local_var_resp$response) || all(local_var_resp$response == "")) {
          local_var_resp$response <- "API server error"
        }
        return(local_var_resp)
      }
    },

    #' @description
    #' List tags/collections
    #'
    #' @param project_id Project ID
    #' @param output (optional) Rectangular output for BI tools (Tableau, Excel, Sheets, ELT). Omit for the default nested JSON. 'flat' returns the same metadata plus 'columns' and 'rows'; 'csv' returns those rows as text/csv. Errors are always returned as JSON.
    #' @param ... Other optional arguments
    #'
    #' @return void
    ListCollections = function(project_id, output = NULL, ...) {
      local_var_response <- self$ListCollectionsWithHttpInfo(project_id, output, ...)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        return(local_var_response$content)
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        return(local_var_response)
      }
    },

    #' @description
    #' List tags/collections
    #'
    #' @param project_id Project ID
    #' @param output (optional) Rectangular output for BI tools (Tableau, Excel, Sheets, ELT). Omit for the default nested JSON. 'flat' returns the same metadata plus 'columns' and 'rows'; 'csv' returns those rows as text/csv. Errors are always returned as JSON.
    #' @param ... Other optional arguments
    #'
    #' @return API response (void) with additional information such as HTTP status code, headers
    ListCollectionsWithHttpInfo = function(project_id, output = NULL, ...) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE

      if (missing(`project_id`)) {
        stop("Missing required parameter `project_id`.")
      }

      if (!missing(`project_id`) && is.null(`project_id`)) {
        stop("Invalid value for `project_id` when calling CollectionsTagsApi$ListCollections, `project_id` is not nullable")
      }

      if (!missing(`output`) && is.null(`output`)) {
        stop("Invalid value for `output` when calling CollectionsTagsApi$ListCollections, `output` is not nullable")
      }

      query_params[["project_id"]] <- `project_id`

      if (!is.null(`output`) && !(`output` %in% c("flat", "csv"))) {
        stop("Invalid value for output when calling CollectionsTagsApi$ListCollections. Must be [flat, csv].")
      }
      query_params[["output"]] <- `output`

      local_var_url_path <- "/dimensions/collections"
      # Bearer token
      if (!is.null(self$api_client$bearer_token)) {
        header_params["Authorization"] <- paste("Bearer", self$api_client$bearer_token, sep = " ")
      }

      # The Accept request HTTP header
      local_var_accepts <- list()

      # The Content-Type representation header
      local_var_content_types <- list()

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "GET",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        local_var_resp$content <- NULL
        return(local_var_resp)
      } 
      
      local_var_error_msg <- local_var_resp$response_as_text()      
      if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        ApiResponse$new(content = paste("Server returned ", local_var_resp$status_code, " response status code."),
                        response = local_var_resp,
                        status_code = local_var_resp$status_code)
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        ApiResponse$new(content = "API client error",
                        response = local_var_resp,
                        status_code = local_var_resp$status_code)
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        if (is.null(local_var_resp$response) || all(local_var_resp$response == "")) {
          local_var_resp$response <- "API server error"
        }
        return(local_var_resp)
      }
    },

    #' @description
    #' List tags (alias for /collections)
    #'
    #' @param project_id Project ID
    #' @param output (optional) Rectangular output for BI tools (Tableau, Excel, Sheets, ELT). Omit for the default nested JSON. 'flat' returns the same metadata plus 'columns' and 'rows'; 'csv' returns those rows as text/csv. Errors are always returned as JSON.
    #' @param ... Other optional arguments
    #'
    #' @return void
    ListTags = function(project_id, output = NULL, ...) {
      local_var_response <- self$ListTagsWithHttpInfo(project_id, output, ...)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        return(local_var_response$content)
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        return(local_var_response)
      }
    },

    #' @description
    #' List tags (alias for /collections)
    #'
    #' @param project_id Project ID
    #' @param output (optional) Rectangular output for BI tools (Tableau, Excel, Sheets, ELT). Omit for the default nested JSON. 'flat' returns the same metadata plus 'columns' and 'rows'; 'csv' returns those rows as text/csv. Errors are always returned as JSON.
    #' @param ... Other optional arguments
    #'
    #' @return API response (void) with additional information such as HTTP status code, headers
    ListTagsWithHttpInfo = function(project_id, output = NULL, ...) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE

      if (missing(`project_id`)) {
        stop("Missing required parameter `project_id`.")
      }

      if (!missing(`project_id`) && is.null(`project_id`)) {
        stop("Invalid value for `project_id` when calling CollectionsTagsApi$ListTags, `project_id` is not nullable")
      }

      if (!missing(`output`) && is.null(`output`)) {
        stop("Invalid value for `output` when calling CollectionsTagsApi$ListTags, `output` is not nullable")
      }

      query_params[["project_id"]] <- `project_id`

      if (!is.null(`output`) && !(`output` %in% c("flat", "csv"))) {
        stop("Invalid value for output when calling CollectionsTagsApi$ListTags. Must be [flat, csv].")
      }
      query_params[["output"]] <- `output`

      local_var_url_path <- "/dimensions/tags"
      # Bearer token
      if (!is.null(self$api_client$bearer_token)) {
        header_params["Authorization"] <- paste("Bearer", self$api_client$bearer_token, sep = " ")
      }

      # The Accept request HTTP header
      local_var_accepts <- list()

      # The Content-Type representation header
      local_var_content_types <- list()

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "GET",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        local_var_resp$content <- NULL
        return(local_var_resp)
      } 
      
      local_var_error_msg <- local_var_resp$response_as_text()      
      if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        ApiResponse$new(content = paste("Server returned ", local_var_resp$status_code, " response status code."),
                        response = local_var_resp,
                        status_code = local_var_resp$status_code)
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        ApiResponse$new(content = "API client error",
                        response = local_var_resp,
                        status_code = local_var_resp$status_code)
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        if (is.null(local_var_resp$response) || all(local_var_resp$response == "")) {
          local_var_resp$response <- "API server error"
        }
        return(local_var_resp)
      }
    },

    #' @description
    #' Update a tag
    #'
    #' @param id 
    #' @param update_collection_request 
    #' @param ... Other optional arguments
    #'
    #' @return void
    UpdateCollection = function(id, update_collection_request, ...) {
      local_var_response <- self$UpdateCollectionWithHttpInfo(id, update_collection_request, ...)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        return(local_var_response$content)
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        return(local_var_response)
      }
    },

    #' @description
    #' Update a tag
    #'
    #' @param id 
    #' @param update_collection_request 
    #' @param ... Other optional arguments
    #'
    #' @return API response (void) with additional information such as HTTP status code, headers
    UpdateCollectionWithHttpInfo = function(id, update_collection_request, ...) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE

      if (missing(`id`)) {
        stop("Missing required parameter `id`.")
      }

      if (missing(`update_collection_request`)) {
        stop("Missing required parameter `update_collection_request`.")
      }

      if (!missing(`id`) && is.null(`id`)) {
        stop("Invalid value for `id` when calling CollectionsTagsApi$UpdateCollection, `id` is not nullable")
      }

      if (!missing(`update_collection_request`) && is.null(`update_collection_request`)) {
        stop("Invalid value for `update_collection_request` when calling CollectionsTagsApi$UpdateCollection, `update_collection_request` is not nullable")
      }

      if (!is.null(`update_collection_request`)) {
        local_var_body <- `update_collection_request`$toJSONString()
      } else {
        local_var_body <- NULL
      }

      local_var_url_path <- "/collections/{id}"
      if (!missing(`id`)) {
        local_var_url_path <- gsub("\\{id\\}", URLencode(as.character(`id`), reserved = TRUE), local_var_url_path)
      }

      # Bearer token
      if (!is.null(self$api_client$bearer_token)) {
        header_params["Authorization"] <- paste("Bearer", self$api_client$bearer_token, sep = " ")
      }

      # The Accept request HTTP header
      local_var_accepts <- list("application/json")

      # The Content-Type representation header
      local_var_content_types <- list("application/json")

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "PATCH",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        local_var_resp$content <- NULL
        return(local_var_resp)
      } 
      
      local_var_error_msg <- local_var_resp$response_as_text()      
      if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        ApiResponse$new(content = paste("Server returned ", local_var_resp$status_code, " response status code."),
                        response = local_var_resp,
                        status_code = local_var_resp$status_code)
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        ApiResponse$new(content = "API client error",
                        response = local_var_resp,
                        status_code = local_var_resp$status_code)
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        if (is.null(local_var_resp$response) || all(local_var_resp$response == "")) {
          local_var_resp$response <- "API server error"
        }
        return(local_var_resp)
      }
    }
  )
)
