#' LLM Pulse API
#'
#' REST API client for LLM Pulse AI visibility analytics.
#'
#' The version of the OpenAPI document: 1.56.0
#' Contact: info@llmpulse.ai
#' Generated by: https://openapi-generator.tech
#'
#' @docType class
#' @title GEOAudits operations
#' @description GEOAuditsApi
#' @format An \code{R6Class} generator object
#' @field api_client Handles the client-server communication.
#'
#' @examples
#' \dontrun{
#' ####################  CompareGeoAuditRuns  ####################
#'
#' library(llmpulse)
#' var_project_id <- 56 # integer | Project ID
#' var_id <- "id_example" # character | Audit id
#' var_from_run <- 56 # integer | Run number to compare from (default the run before to_run) (Optional)
#' var_to_run <- 56 # integer | Run number to compare to (default the latest completed run) (Optional)
#'
#' #Compare two GEO audit runs
#' api_instance <- GEOAuditsApi$new()
#'
#' # Configure HTTP bearer authorization: BearerAuth
#' api_instance$api_client$bearer_token <- Sys.getenv("BEARER_TOKEN")
#'
#' # to save the result into a file, simply add the optional `data_file` parameter, e.g.
#' # result <- api_instance$CompareGeoAuditRuns(var_project_id, var_id, from_run = var_from_run, to_run = var_to_rundata_file = "result.txt")
#' result <- api_instance$CompareGeoAuditRuns(var_project_id, var_id, from_run = var_from_run, to_run = var_to_run)
#' dput(result)
#'
#'
#' ####################  CreateGeoAudits  ####################
#'
#' library(llmpulse)
#' var_geo_audit_create_request <- GeoAuditCreateRequest$new(123, "target_example", c("agent_readiness"), "once") # GeoAuditCreateRequest | 
#'
#' #Create GEO audits
#' api_instance <- GEOAuditsApi$new()
#'
#' # Configure HTTP bearer authorization: BearerAuth
#' api_instance$api_client$bearer_token <- Sys.getenv("BEARER_TOKEN")
#'
#' # to save the result into a file, simply add the optional `data_file` parameter, e.g.
#' # result <- api_instance$CreateGeoAudits(var_geo_audit_create_requestdata_file = "result.txt")
#' result <- api_instance$CreateGeoAudits(var_geo_audit_create_request)
#' dput(result)
#'
#'
#' ####################  DeleteGeoAudit  ####################
#'
#' library(llmpulse)
#' var_project_id <- 56 # integer | Project ID
#' var_id <- "id_example" # character | Audit id
#'
#' #Delete (archive) a GEO audit
#' api_instance <- GEOAuditsApi$new()
#'
#' # Configure HTTP bearer authorization: BearerAuth
#' api_instance$api_client$bearer_token <- Sys.getenv("BEARER_TOKEN")
#'
#' # to save the result into a file, simply add the optional `data_file` parameter, e.g.
#' # result <- api_instance$DeleteGeoAudit(var_project_id, var_iddata_file = "result.txt")
#' result <- api_instance$DeleteGeoAudit(var_project_id, var_id)
#' dput(result)
#'
#'
#' ####################  GetGeoAudit  ####################
#'
#' library(llmpulse)
#' var_project_id <- 56 # integer | Project ID
#' var_id <- "id_example" # character | Audit id
#'
#' #Get a GEO audit
#' api_instance <- GEOAuditsApi$new()
#'
#' # Configure HTTP bearer authorization: BearerAuth
#' api_instance$api_client$bearer_token <- Sys.getenv("BEARER_TOKEN")
#'
#' # to save the result into a file, simply add the optional `data_file` parameter, e.g.
#' # result <- api_instance$GetGeoAudit(var_project_id, var_iddata_file = "result.txt")
#' result <- api_instance$GetGeoAudit(var_project_id, var_id)
#' dput(result)
#'
#'
#' ####################  GetGeoAuditRun  ####################
#'
#' library(llmpulse)
#' var_project_id <- 56 # integer | Project ID
#' var_geo_audit_id <- "geo_audit_id_example" # character | Audit id
#' var_sequence <- 56 # integer | Run number within the audit
#'
#' #Get a GEO audit run
#' api_instance <- GEOAuditsApi$new()
#'
#' # Configure HTTP bearer authorization: BearerAuth
#' api_instance$api_client$bearer_token <- Sys.getenv("BEARER_TOKEN")
#'
#' # to save the result into a file, simply add the optional `data_file` parameter, e.g.
#' # result <- api_instance$GetGeoAuditRun(var_project_id, var_geo_audit_id, var_sequencedata_file = "result.txt")
#' result <- api_instance$GetGeoAuditRun(var_project_id, var_geo_audit_id, var_sequence)
#' dput(result)
#'
#'
#' ####################  ListGeoAlerts  ####################
#'
#' library(llmpulse)
#' var_project_id <- 56 # integer | Project ID
#' var_audit_id <- "audit_id_example" # character | Only alerts of this audit (Optional)
#' var_page <- 1 # integer |  (Optional)
#' var_per_page <- 20 # integer |  (Optional)
#'
#' #List GEO audit alerts
#' api_instance <- GEOAuditsApi$new()
#'
#' # Configure HTTP bearer authorization: BearerAuth
#' api_instance$api_client$bearer_token <- Sys.getenv("BEARER_TOKEN")
#'
#' # to save the result into a file, simply add the optional `data_file` parameter, e.g.
#' # result <- api_instance$ListGeoAlerts(var_project_id, audit_id = var_audit_id, page = var_page, per_page = var_per_pagedata_file = "result.txt")
#' result <- api_instance$ListGeoAlerts(var_project_id, audit_id = var_audit_id, page = var_page, per_page = var_per_page)
#' dput(result)
#'
#'
#' ####################  ListGeoAuditFindings  ####################
#'
#' library(llmpulse)
#' var_project_id <- 56 # integer | Project ID
#' var_geo_audit_id <- "geo_audit_id_example" # character | Audit id
#' var_sequence <- 56 # integer | Run number within the audit
#' var_page <- 1 # integer |  (Optional)
#' var_per_page <- 20 # integer |  (Optional)
#' var_output <- "output_example" # character | Rectangular output for BI tools (Tableau, Excel, Sheets, ELT). Omit for the default nested JSON. 'flat' returns the same metadata plus 'columns' and 'rows'; 'csv' returns those rows as text/csv. Errors are always returned as JSON. (Optional)
#'
#' #List the findings of a GEO audit run
#' api_instance <- GEOAuditsApi$new()
#'
#' # Configure HTTP bearer authorization: BearerAuth
#' api_instance$api_client$bearer_token <- Sys.getenv("BEARER_TOKEN")
#'
#' # to save the result into a file, simply add the optional `data_file` parameter, e.g.
#' # result <- api_instance$ListGeoAuditFindings(var_project_id, var_geo_audit_id, var_sequence, page = var_page, per_page = var_per_page, output = var_outputdata_file = "result.txt")
#' result <- api_instance$ListGeoAuditFindings(var_project_id, var_geo_audit_id, var_sequence, page = var_page, per_page = var_per_page, output = var_output)
#' dput(result)
#'
#'
#' ####################  ListGeoAuditIssues  ####################
#'
#' library(llmpulse)
#' var_project_id <- 56 # integer | Project ID
#' var_geo_audit_id <- "geo_audit_id_example" # character | Audit id
#' var_state <- "state_example" # character | open means open and not accepted; default all (Optional)
#' var_page <- 1 # integer |  (Optional)
#' var_per_page <- 20 # integer |  (Optional)
#'
#' #List the issues of a GEO audit
#' api_instance <- GEOAuditsApi$new()
#'
#' # Configure HTTP bearer authorization: BearerAuth
#' api_instance$api_client$bearer_token <- Sys.getenv("BEARER_TOKEN")
#'
#' # to save the result into a file, simply add the optional `data_file` parameter, e.g.
#' # result <- api_instance$ListGeoAuditIssues(var_project_id, var_geo_audit_id, state = var_state, page = var_page, per_page = var_per_pagedata_file = "result.txt")
#' result <- api_instance$ListGeoAuditIssues(var_project_id, var_geo_audit_id, state = var_state, page = var_page, per_page = var_per_page)
#' dput(result)
#'
#'
#' ####################  ListGeoAuditRuns  ####################
#'
#' library(llmpulse)
#' var_project_id <- 56 # integer | Project ID
#' var_geo_audit_id <- "geo_audit_id_example" # character | Audit id
#' var_page <- 1 # integer |  (Optional)
#' var_per_page <- 20 # integer |  (Optional)
#' var_output <- "output_example" # character | Rectangular output for BI tools (Tableau, Excel, Sheets, ELT). Omit for the default nested JSON. 'flat' returns the same metadata plus 'columns' and 'rows'; 'csv' returns those rows as text/csv. Errors are always returned as JSON. (Optional)
#'
#' #List the runs of a GEO audit
#' api_instance <- GEOAuditsApi$new()
#'
#' # Configure HTTP bearer authorization: BearerAuth
#' api_instance$api_client$bearer_token <- Sys.getenv("BEARER_TOKEN")
#'
#' # to save the result into a file, simply add the optional `data_file` parameter, e.g.
#' # result <- api_instance$ListGeoAuditRuns(var_project_id, var_geo_audit_id, page = var_page, per_page = var_per_page, output = var_outputdata_file = "result.txt")
#' result <- api_instance$ListGeoAuditRuns(var_project_id, var_geo_audit_id, page = var_page, per_page = var_per_page, output = var_output)
#' dput(result)
#'
#'
#' ####################  ListGeoAudits  ####################
#'
#' library(llmpulse)
#' var_project_id <- 56 # integer | Project ID
#' var_audit_type <- "audit_type_example" # character |  (Optional)
#' var_status <- "status_example" # character |  (Optional)
#' var_cadence <- "cadence_example" # character |  (Optional)
#' var_page <- 1 # integer |  (Optional)
#' var_per_page <- 20 # integer |  (Optional)
#'
#' #List GEO audits
#' api_instance <- GEOAuditsApi$new()
#'
#' # Configure HTTP bearer authorization: BearerAuth
#' api_instance$api_client$bearer_token <- Sys.getenv("BEARER_TOKEN")
#'
#' # to save the result into a file, simply add the optional `data_file` parameter, e.g.
#' # result <- api_instance$ListGeoAudits(var_project_id, audit_type = var_audit_type, status = var_status, cadence = var_cadence, page = var_page, per_page = var_per_pagedata_file = "result.txt")
#' result <- api_instance$ListGeoAudits(var_project_id, audit_type = var_audit_type, status = var_status, cadence = var_cadence, page = var_page, per_page = var_per_page)
#' dput(result)
#'
#'
#' ####################  RunGeoAudit  ####################
#'
#' library(llmpulse)
#' var_project_id <- 56 # integer | Project ID
#' var_geo_audit_id <- "geo_audit_id_example" # character | Audit id
#'
#' #Run a GEO audit now
#' api_instance <- GEOAuditsApi$new()
#'
#' # Configure HTTP bearer authorization: BearerAuth
#' api_instance$api_client$bearer_token <- Sys.getenv("BEARER_TOKEN")
#'
#' # to save the result into a file, simply add the optional `data_file` parameter, e.g.
#' # result <- api_instance$RunGeoAudit(var_project_id, var_geo_audit_iddata_file = "result.txt")
#' result <- api_instance$RunGeoAudit(var_project_id, var_geo_audit_id)
#' dput(result)
#'
#'
#' ####################  UpdateGeoAudit  ####################
#'
#' library(llmpulse)
#' var_id <- "id_example" # character | Audit id
#' var_geo_audit_update_request <- GeoAuditUpdateRequest$new(123, "once", 123, 123, "active", "email_alerts_example") # GeoAuditUpdateRequest | 
#'
#' #Update a GEO audit
#' api_instance <- GEOAuditsApi$new()
#'
#' # Configure HTTP bearer authorization: BearerAuth
#' api_instance$api_client$bearer_token <- Sys.getenv("BEARER_TOKEN")
#'
#' # to save the result into a file, simply add the optional `data_file` parameter, e.g.
#' # result <- api_instance$UpdateGeoAudit(var_id, var_geo_audit_update_requestdata_file = "result.txt")
#' result <- api_instance$UpdateGeoAudit(var_id, var_geo_audit_update_request)
#' dput(result)
#'
#'
#' ####################  UpdateGeoAuditIssue  ####################
#'
#' library(llmpulse)
#' var_geo_audit_id <- "geo_audit_id_example" # character | Audit id
#' var_id <- 56 # integer | Issue id
#' var_geo_audit_issue_update_request <- GeoAuditIssueUpdateRequest$new("accepted_example", 123) # GeoAuditIssueUpdateRequest | 
#'
#' #Accept or reopen a GEO audit issue
#' api_instance <- GEOAuditsApi$new()
#'
#' # Configure HTTP bearer authorization: BearerAuth
#' api_instance$api_client$bearer_token <- Sys.getenv("BEARER_TOKEN")
#'
#' # to save the result into a file, simply add the optional `data_file` parameter, e.g.
#' # result <- api_instance$UpdateGeoAuditIssue(var_geo_audit_id, var_id, var_geo_audit_issue_update_requestdata_file = "result.txt")
#' result <- api_instance$UpdateGeoAuditIssue(var_geo_audit_id, var_id, var_geo_audit_issue_update_request)
#' dput(result)
#'
#'
#' }
#' @importFrom R6 R6Class
#' @importFrom base64enc base64encode
#' @export
GEOAuditsApi <- R6::R6Class(
  "GEOAuditsApi",
  public = list(
    api_client = NULL,

    #' @description
    #' Initialize a new GEOAuditsApi.
    #'
    #' @param api_client An instance of API client.
    initialize = function(api_client) {
      if (!missing(api_client)) {
        self$api_client <- api_client
      } else {
        self$api_client <- ApiClient$new()
      }
    },

    #' @description
    #' Compare two GEO audit runs
    #'
    #' @param project_id Project ID
    #' @param id Audit id
    #' @param from_run (optional) Run number to compare from (default the run before to_run)
    #' @param to_run (optional) Run number to compare to (default the latest completed run)
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @param .parse Logical. If \code{TRUE} then the response will be parsed to a generated type. If \code{FALSE} the response will be returned as unparsed text.
    #'
    #' @return GeoAuditComparison
    CompareGeoAuditRuns = function(project_id, id, from_run = NULL, to_run = NULL, data_file = NULL, ..., .parse = TRUE) {
      local_var_response <- self$CompareGeoAuditRunsWithHttpInfo(project_id, id, from_run, to_run, data_file = data_file, ..., .parse = .parse)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        return(local_var_response$content)
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        return(local_var_response)
      }
    },

    #' @description
    #' Compare two GEO audit runs
    #'
    #' @param project_id Project ID
    #' @param id Audit id
    #' @param from_run (optional) Run number to compare from (default the run before to_run)
    #' @param to_run (optional) Run number to compare to (default the latest completed run)
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @param .parse Logical. If \code{TRUE} then the response will be parsed to a generated type. If \code{FALSE} the response will be returned as unparsed text.
    #'
    #' @return API response (GeoAuditComparison) with additional information such as HTTP status code, headers
    CompareGeoAuditRunsWithHttpInfo = function(project_id, id, from_run = NULL, to_run = NULL, data_file = NULL, ..., .parse = TRUE) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE

      if (missing(`project_id`)) {
        stop("Missing required parameter `project_id`.")
      }

      if (missing(`id`)) {
        stop("Missing required parameter `id`.")
      }

      if (!missing(`project_id`) && is.null(`project_id`)) {
        stop("Invalid value for `project_id` when calling GEOAuditsApi$CompareGeoAuditRuns, `project_id` is not nullable")
      }

      if (!missing(`id`) && is.null(`id`)) {
        stop("Invalid value for `id` when calling GEOAuditsApi$CompareGeoAuditRuns, `id` is not nullable")
      }

      if (!missing(`from_run`) && is.null(`from_run`)) {
        stop("Invalid value for `from_run` when calling GEOAuditsApi$CompareGeoAuditRuns, `from_run` is not nullable")
      }

      if (!missing(`to_run`) && is.null(`to_run`)) {
        stop("Invalid value for `to_run` when calling GEOAuditsApi$CompareGeoAuditRuns, `to_run` is not nullable")
      }

      query_params[["project_id"]] <- `project_id`

      query_params[["from_run"]] <- `from_run`

      query_params[["to_run"]] <- `to_run`

      local_var_url_path <- "/geo_audits/{id}/comparison"
      if (!missing(`id`)) {
        local_var_url_path <- gsub("\\{id\\}", URLencode(as.character(`id`), reserved = TRUE), local_var_url_path)
      }

      # Bearer token
      if (!is.null(self$api_client$bearer_token)) {
        header_params["Authorization"] <- paste("Bearer", self$api_client$bearer_token, sep = " ")
      }

      # The Accept request HTTP header
      local_var_accepts <- list("application/json")

      # The Content-Type representation header
      local_var_content_types <- list()

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "GET",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        # save response in a file
        if (!is.null(data_file)) {
          self$api_client$WriteFile(local_var_resp, data_file)
        }
        if (!.parse) {
          local_var_resp$content <- local_var_resp$response_as_text()
          return(local_var_resp)
        }

        deserialized_resp_obj <- tryCatch(
          self$api_client$DeserializeResponse(local_var_resp, "GeoAuditComparison"),
          error = function(e) {
            stop("Failed to deserialize response")
          }
        )
        local_var_resp$content <- deserialized_resp_obj
        return(local_var_resp)
      } 
      
      local_var_error_msg <- local_var_resp$response_as_text()      
      if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        ApiResponse$new(content = paste("Server returned ", local_var_resp$status_code, " response status code."),
                        response = local_var_resp,
                        status_code = local_var_resp$status_code)
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        ApiResponse$new(content = "API client error",
                        response = local_var_resp,
                        status_code = local_var_resp$status_code)
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        if (is.null(local_var_resp$response) || all(local_var_resp$response == "")) {
          local_var_resp$response <- "API server error"
        }
        return(local_var_resp)
      }
    },

    #' @description
    #' Create GEO audits
    #'
    #' @param geo_audit_create_request 
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @param .parse Logical. If \code{TRUE} then the response will be parsed to a generated type. If \code{FALSE} the response will be returned as unparsed text.
    #'
    #' @return GeoAuditCreateResponse
    CreateGeoAudits = function(geo_audit_create_request, data_file = NULL, ..., .parse = TRUE) {
      local_var_response <- self$CreateGeoAuditsWithHttpInfo(geo_audit_create_request, data_file = data_file, ..., .parse = .parse)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        return(local_var_response$content)
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        return(local_var_response)
      }
    },

    #' @description
    #' Create GEO audits
    #'
    #' @param geo_audit_create_request 
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @param .parse Logical. If \code{TRUE} then the response will be parsed to a generated type. If \code{FALSE} the response will be returned as unparsed text.
    #'
    #' @return API response (GeoAuditCreateResponse) with additional information such as HTTP status code, headers
    CreateGeoAuditsWithHttpInfo = function(geo_audit_create_request, data_file = NULL, ..., .parse = TRUE) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE

      if (missing(`geo_audit_create_request`)) {
        stop("Missing required parameter `geo_audit_create_request`.")
      }

      if (!missing(`geo_audit_create_request`) && is.null(`geo_audit_create_request`)) {
        stop("Invalid value for `geo_audit_create_request` when calling GEOAuditsApi$CreateGeoAudits, `geo_audit_create_request` is not nullable")
      }

      if (!is.null(`geo_audit_create_request`)) {
        local_var_body <- `geo_audit_create_request`$toJSONString()
      } else {
        local_var_body <- NULL
      }

      local_var_url_path <- "/geo_audits"
      # Bearer token
      if (!is.null(self$api_client$bearer_token)) {
        header_params["Authorization"] <- paste("Bearer", self$api_client$bearer_token, sep = " ")
      }

      # The Accept request HTTP header
      local_var_accepts <- list("application/json")

      # The Content-Type representation header
      local_var_content_types <- list("application/json")

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "POST",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        # save response in a file
        if (!is.null(data_file)) {
          self$api_client$WriteFile(local_var_resp, data_file)
        }
        if (!.parse) {
          local_var_resp$content <- local_var_resp$response_as_text()
          return(local_var_resp)
        }

        deserialized_resp_obj <- tryCatch(
          self$api_client$DeserializeResponse(local_var_resp, "GeoAuditCreateResponse"),
          error = function(e) {
            stop("Failed to deserialize response")
          }
        )
        local_var_resp$content <- deserialized_resp_obj
        return(local_var_resp)
      } 
      
      local_var_error_msg <- local_var_resp$response_as_text()      
      if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        ApiResponse$new(content = paste("Server returned ", local_var_resp$status_code, " response status code."),
                        response = local_var_resp,
                        status_code = local_var_resp$status_code)
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        ApiResponse$new(content = "API client error",
                        response = local_var_resp,
                        status_code = local_var_resp$status_code)
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        if (is.null(local_var_resp$response) || all(local_var_resp$response == "")) {
          local_var_resp$response <- "API server error"
        }
        return(local_var_resp)
      }
    },

    #' @description
    #' Delete (archive) a GEO audit
    #'
    #' @param project_id Project ID
    #' @param id Audit id
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @param .parse Logical. If \code{TRUE} then the response will be parsed to a generated type. If \code{FALSE} the response will be returned as unparsed text.
    #'
    #' @return GeoAuditArchived
    DeleteGeoAudit = function(project_id, id, data_file = NULL, ..., .parse = TRUE) {
      local_var_response <- self$DeleteGeoAuditWithHttpInfo(project_id, id, data_file = data_file, ..., .parse = .parse)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        return(local_var_response$content)
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        return(local_var_response)
      }
    },

    #' @description
    #' Delete (archive) a GEO audit
    #'
    #' @param project_id Project ID
    #' @param id Audit id
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @param .parse Logical. If \code{TRUE} then the response will be parsed to a generated type. If \code{FALSE} the response will be returned as unparsed text.
    #'
    #' @return API response (GeoAuditArchived) with additional information such as HTTP status code, headers
    DeleteGeoAuditWithHttpInfo = function(project_id, id, data_file = NULL, ..., .parse = TRUE) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE

      if (missing(`project_id`)) {
        stop("Missing required parameter `project_id`.")
      }

      if (missing(`id`)) {
        stop("Missing required parameter `id`.")
      }

      if (!missing(`project_id`) && is.null(`project_id`)) {
        stop("Invalid value for `project_id` when calling GEOAuditsApi$DeleteGeoAudit, `project_id` is not nullable")
      }

      if (!missing(`id`) && is.null(`id`)) {
        stop("Invalid value for `id` when calling GEOAuditsApi$DeleteGeoAudit, `id` is not nullable")
      }

      query_params[["project_id"]] <- `project_id`

      local_var_url_path <- "/geo_audits/{id}"
      if (!missing(`id`)) {
        local_var_url_path <- gsub("\\{id\\}", URLencode(as.character(`id`), reserved = TRUE), local_var_url_path)
      }

      # Bearer token
      if (!is.null(self$api_client$bearer_token)) {
        header_params["Authorization"] <- paste("Bearer", self$api_client$bearer_token, sep = " ")
      }

      # The Accept request HTTP header
      local_var_accepts <- list("application/json")

      # The Content-Type representation header
      local_var_content_types <- list()

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "DELETE",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        # save response in a file
        if (!is.null(data_file)) {
          self$api_client$WriteFile(local_var_resp, data_file)
        }
        if (!.parse) {
          local_var_resp$content <- local_var_resp$response_as_text()
          return(local_var_resp)
        }

        deserialized_resp_obj <- tryCatch(
          self$api_client$DeserializeResponse(local_var_resp, "GeoAuditArchived"),
          error = function(e) {
            stop("Failed to deserialize response")
          }
        )
        local_var_resp$content <- deserialized_resp_obj
        return(local_var_resp)
      } 
      
      local_var_error_msg <- local_var_resp$response_as_text()      
      if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        ApiResponse$new(content = paste("Server returned ", local_var_resp$status_code, " response status code."),
                        response = local_var_resp,
                        status_code = local_var_resp$status_code)
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        ApiResponse$new(content = "API client error",
                        response = local_var_resp,
                        status_code = local_var_resp$status_code)
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        if (is.null(local_var_resp$response) || all(local_var_resp$response == "")) {
          local_var_resp$response <- "API server error"
        }
        return(local_var_resp)
      }
    },

    #' @description
    #' Get a GEO audit
    #'
    #' @param project_id Project ID
    #' @param id Audit id
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @param .parse Logical. If \code{TRUE} then the response will be parsed to a generated type. If \code{FALSE} the response will be returned as unparsed text.
    #'
    #' @return GeoAuditResponse
    GetGeoAudit = function(project_id, id, data_file = NULL, ..., .parse = TRUE) {
      local_var_response <- self$GetGeoAuditWithHttpInfo(project_id, id, data_file = data_file, ..., .parse = .parse)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        return(local_var_response$content)
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        return(local_var_response)
      }
    },

    #' @description
    #' Get a GEO audit
    #'
    #' @param project_id Project ID
    #' @param id Audit id
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @param .parse Logical. If \code{TRUE} then the response will be parsed to a generated type. If \code{FALSE} the response will be returned as unparsed text.
    #'
    #' @return API response (GeoAuditResponse) with additional information such as HTTP status code, headers
    GetGeoAuditWithHttpInfo = function(project_id, id, data_file = NULL, ..., .parse = TRUE) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE

      if (missing(`project_id`)) {
        stop("Missing required parameter `project_id`.")
      }

      if (missing(`id`)) {
        stop("Missing required parameter `id`.")
      }

      if (!missing(`project_id`) && is.null(`project_id`)) {
        stop("Invalid value for `project_id` when calling GEOAuditsApi$GetGeoAudit, `project_id` is not nullable")
      }

      if (!missing(`id`) && is.null(`id`)) {
        stop("Invalid value for `id` when calling GEOAuditsApi$GetGeoAudit, `id` is not nullable")
      }

      query_params[["project_id"]] <- `project_id`

      local_var_url_path <- "/geo_audits/{id}"
      if (!missing(`id`)) {
        local_var_url_path <- gsub("\\{id\\}", URLencode(as.character(`id`), reserved = TRUE), local_var_url_path)
      }

      # Bearer token
      if (!is.null(self$api_client$bearer_token)) {
        header_params["Authorization"] <- paste("Bearer", self$api_client$bearer_token, sep = " ")
      }

      # The Accept request HTTP header
      local_var_accepts <- list("application/json")

      # The Content-Type representation header
      local_var_content_types <- list()

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "GET",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        # save response in a file
        if (!is.null(data_file)) {
          self$api_client$WriteFile(local_var_resp, data_file)
        }
        if (!.parse) {
          local_var_resp$content <- local_var_resp$response_as_text()
          return(local_var_resp)
        }

        deserialized_resp_obj <- tryCatch(
          self$api_client$DeserializeResponse(local_var_resp, "GeoAuditResponse"),
          error = function(e) {
            stop("Failed to deserialize response")
          }
        )
        local_var_resp$content <- deserialized_resp_obj
        return(local_var_resp)
      } 
      
      local_var_error_msg <- local_var_resp$response_as_text()      
      if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        ApiResponse$new(content = paste("Server returned ", local_var_resp$status_code, " response status code."),
                        response = local_var_resp,
                        status_code = local_var_resp$status_code)
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        ApiResponse$new(content = "API client error",
                        response = local_var_resp,
                        status_code = local_var_resp$status_code)
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        if (is.null(local_var_resp$response) || all(local_var_resp$response == "")) {
          local_var_resp$response <- "API server error"
        }
        return(local_var_resp)
      }
    },

    #' @description
    #' Get a GEO audit run
    #'
    #' @param project_id Project ID
    #' @param geo_audit_id Audit id
    #' @param sequence Run number within the audit
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @param .parse Logical. If \code{TRUE} then the response will be parsed to a generated type. If \code{FALSE} the response will be returned as unparsed text.
    #'
    #' @return GeoAuditRunDetail
    GetGeoAuditRun = function(project_id, geo_audit_id, sequence, data_file = NULL, ..., .parse = TRUE) {
      local_var_response <- self$GetGeoAuditRunWithHttpInfo(project_id, geo_audit_id, sequence, data_file = data_file, ..., .parse = .parse)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        return(local_var_response$content)
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        return(local_var_response)
      }
    },

    #' @description
    #' Get a GEO audit run
    #'
    #' @param project_id Project ID
    #' @param geo_audit_id Audit id
    #' @param sequence Run number within the audit
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @param .parse Logical. If \code{TRUE} then the response will be parsed to a generated type. If \code{FALSE} the response will be returned as unparsed text.
    #'
    #' @return API response (GeoAuditRunDetail) with additional information such as HTTP status code, headers
    GetGeoAuditRunWithHttpInfo = function(project_id, geo_audit_id, sequence, data_file = NULL, ..., .parse = TRUE) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE

      if (missing(`project_id`)) {
        stop("Missing required parameter `project_id`.")
      }

      if (missing(`geo_audit_id`)) {
        stop("Missing required parameter `geo_audit_id`.")
      }

      if (missing(`sequence`)) {
        stop("Missing required parameter `sequence`.")
      }

      if (!missing(`project_id`) && is.null(`project_id`)) {
        stop("Invalid value for `project_id` when calling GEOAuditsApi$GetGeoAuditRun, `project_id` is not nullable")
      }

      if (!missing(`geo_audit_id`) && is.null(`geo_audit_id`)) {
        stop("Invalid value for `geo_audit_id` when calling GEOAuditsApi$GetGeoAuditRun, `geo_audit_id` is not nullable")
      }

      if (!missing(`sequence`) && is.null(`sequence`)) {
        stop("Invalid value for `sequence` when calling GEOAuditsApi$GetGeoAuditRun, `sequence` is not nullable")
      }

      query_params[["project_id"]] <- `project_id`

      local_var_url_path <- "/geo_audits/{geo_audit_id}/runs/{sequence}"
      if (!missing(`geo_audit_id`)) {
        local_var_url_path <- gsub("\\{geo_audit_id\\}", URLencode(as.character(`geo_audit_id`), reserved = TRUE), local_var_url_path)
      }

      if (!missing(`sequence`)) {
        local_var_url_path <- gsub("\\{sequence\\}", URLencode(as.character(`sequence`), reserved = TRUE), local_var_url_path)
      }

      # Bearer token
      if (!is.null(self$api_client$bearer_token)) {
        header_params["Authorization"] <- paste("Bearer", self$api_client$bearer_token, sep = " ")
      }

      # The Accept request HTTP header
      local_var_accepts <- list("application/json")

      # The Content-Type representation header
      local_var_content_types <- list()

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "GET",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        # save response in a file
        if (!is.null(data_file)) {
          self$api_client$WriteFile(local_var_resp, data_file)
        }
        if (!.parse) {
          local_var_resp$content <- local_var_resp$response_as_text()
          return(local_var_resp)
        }

        deserialized_resp_obj <- tryCatch(
          self$api_client$DeserializeResponse(local_var_resp, "GeoAuditRunDetail"),
          error = function(e) {
            stop("Failed to deserialize response")
          }
        )
        local_var_resp$content <- deserialized_resp_obj
        return(local_var_resp)
      } 
      
      local_var_error_msg <- local_var_resp$response_as_text()      
      if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        ApiResponse$new(content = paste("Server returned ", local_var_resp$status_code, " response status code."),
                        response = local_var_resp,
                        status_code = local_var_resp$status_code)
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        ApiResponse$new(content = "API client error",
                        response = local_var_resp,
                        status_code = local_var_resp$status_code)
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        if (is.null(local_var_resp$response) || all(local_var_resp$response == "")) {
          local_var_resp$response <- "API server error"
        }
        return(local_var_resp)
      }
    },

    #' @description
    #' List GEO audit alerts
    #'
    #' @param project_id Project ID
    #' @param audit_id (optional) Only alerts of this audit
    #' @param page (optional) No description (default value: 1)
    #' @param per_page (optional) No description (default value: 20)
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @param .parse Logical. If \code{TRUE} then the response will be parsed to a generated type. If \code{FALSE} the response will be returned as unparsed text.
    #'
    #' @return GeoAlertList
    ListGeoAlerts = function(project_id, audit_id = NULL, page = 1, per_page = 20, data_file = NULL, ..., .parse = TRUE) {
      local_var_response <- self$ListGeoAlertsWithHttpInfo(project_id, audit_id, page, per_page, data_file = data_file, ..., .parse = .parse)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        return(local_var_response$content)
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        return(local_var_response)
      }
    },

    #' @description
    #' List GEO audit alerts
    #'
    #' @param project_id Project ID
    #' @param audit_id (optional) Only alerts of this audit
    #' @param page (optional) No description (default value: 1)
    #' @param per_page (optional) No description (default value: 20)
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @param .parse Logical. If \code{TRUE} then the response will be parsed to a generated type. If \code{FALSE} the response will be returned as unparsed text.
    #'
    #' @return API response (GeoAlertList) with additional information such as HTTP status code, headers
    ListGeoAlertsWithHttpInfo = function(project_id, audit_id = NULL, page = 1, per_page = 20, data_file = NULL, ..., .parse = TRUE) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE

      if (missing(`project_id`)) {
        stop("Missing required parameter `project_id`.")
      }

      if (!missing(`project_id`) && is.null(`project_id`)) {
        stop("Invalid value for `project_id` when calling GEOAuditsApi$ListGeoAlerts, `project_id` is not nullable")
      }

      if (!missing(`audit_id`) && is.null(`audit_id`)) {
        stop("Invalid value for `audit_id` when calling GEOAuditsApi$ListGeoAlerts, `audit_id` is not nullable")
      }

      if (!missing(`page`) && is.null(`page`)) {
        stop("Invalid value for `page` when calling GEOAuditsApi$ListGeoAlerts, `page` is not nullable")
      }
      if (!is.null(`page`) && `page` <  1) {
        stop("Invalid value for `page` when calling GEOAuditsApi$ListGeoAlerts, must be bigger than or equal to 1.")
      }

      if (!missing(`per_page`) && is.null(`per_page`)) {
        stop("Invalid value for `per_page` when calling GEOAuditsApi$ListGeoAlerts, `per_page` is not nullable")
      }
      if (!is.null(`per_page`) && `per_page` >  100) {
        stop("Invalid value for `per_page` when calling GEOAuditsApi$ListGeoAlerts, must be smaller than or equal to 100.")
      }
      if (!is.null(`per_page`) && `per_page` <  1) {
        stop("Invalid value for `per_page` when calling GEOAuditsApi$ListGeoAlerts, must be bigger than or equal to 1.")
      }

      query_params[["project_id"]] <- `project_id`

      query_params[["audit_id"]] <- `audit_id`

      query_params[["page"]] <- `page`

      query_params[["per_page"]] <- `per_page`

      local_var_url_path <- "/geo_alerts"
      # Bearer token
      if (!is.null(self$api_client$bearer_token)) {
        header_params["Authorization"] <- paste("Bearer", self$api_client$bearer_token, sep = " ")
      }

      # The Accept request HTTP header
      local_var_accepts <- list("application/json")

      # The Content-Type representation header
      local_var_content_types <- list()

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "GET",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        # save response in a file
        if (!is.null(data_file)) {
          self$api_client$WriteFile(local_var_resp, data_file)
        }
        if (!.parse) {
          local_var_resp$content <- local_var_resp$response_as_text()
          return(local_var_resp)
        }

        deserialized_resp_obj <- tryCatch(
          self$api_client$DeserializeResponse(local_var_resp, "GeoAlertList"),
          error = function(e) {
            stop("Failed to deserialize response")
          }
        )
        local_var_resp$content <- deserialized_resp_obj
        return(local_var_resp)
      } 
      
      local_var_error_msg <- local_var_resp$response_as_text()      
      if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        ApiResponse$new(content = paste("Server returned ", local_var_resp$status_code, " response status code."),
                        response = local_var_resp,
                        status_code = local_var_resp$status_code)
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        ApiResponse$new(content = "API client error",
                        response = local_var_resp,
                        status_code = local_var_resp$status_code)
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        if (is.null(local_var_resp$response) || all(local_var_resp$response == "")) {
          local_var_resp$response <- "API server error"
        }
        return(local_var_resp)
      }
    },

    #' @description
    #' List the findings of a GEO audit run
    #'
    #' @param project_id Project ID
    #' @param geo_audit_id Audit id
    #' @param sequence Run number within the audit
    #' @param page (optional) No description (default value: 1)
    #' @param per_page (optional) No description (default value: 20)
    #' @param output (optional) Rectangular output for BI tools (Tableau, Excel, Sheets, ELT). Omit for the default nested JSON. 'flat' returns the same metadata plus 'columns' and 'rows'; 'csv' returns those rows as text/csv. Errors are always returned as JSON.
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @param .parse Logical. If \code{TRUE} then the response will be parsed to a generated type. If \code{FALSE} the response will be returned as unparsed text.
    #'
    #' @return GeoAuditFindingList
    ListGeoAuditFindings = function(project_id, geo_audit_id, sequence, page = 1, per_page = 20, output = NULL, data_file = NULL, ..., .parse = TRUE) {
      local_var_response <- self$ListGeoAuditFindingsWithHttpInfo(project_id, geo_audit_id, sequence, page, per_page, output, data_file = data_file, ..., .parse = .parse)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        return(local_var_response$content)
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        return(local_var_response)
      }
    },

    #' @description
    #' List the findings of a GEO audit run
    #'
    #' @param project_id Project ID
    #' @param geo_audit_id Audit id
    #' @param sequence Run number within the audit
    #' @param page (optional) No description (default value: 1)
    #' @param per_page (optional) No description (default value: 20)
    #' @param output (optional) Rectangular output for BI tools (Tableau, Excel, Sheets, ELT). Omit for the default nested JSON. 'flat' returns the same metadata plus 'columns' and 'rows'; 'csv' returns those rows as text/csv. Errors are always returned as JSON.
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @param .parse Logical. If \code{TRUE} then the response will be parsed to a generated type. If \code{FALSE} the response will be returned as unparsed text.
    #'
    #' @return API response (GeoAuditFindingList) with additional information such as HTTP status code, headers
    ListGeoAuditFindingsWithHttpInfo = function(project_id, geo_audit_id, sequence, page = 1, per_page = 20, output = NULL, data_file = NULL, ..., .parse = TRUE) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE

      if (missing(`project_id`)) {
        stop("Missing required parameter `project_id`.")
      }

      if (missing(`geo_audit_id`)) {
        stop("Missing required parameter `geo_audit_id`.")
      }

      if (missing(`sequence`)) {
        stop("Missing required parameter `sequence`.")
      }

      if (!missing(`project_id`) && is.null(`project_id`)) {
        stop("Invalid value for `project_id` when calling GEOAuditsApi$ListGeoAuditFindings, `project_id` is not nullable")
      }

      if (!missing(`geo_audit_id`) && is.null(`geo_audit_id`)) {
        stop("Invalid value for `geo_audit_id` when calling GEOAuditsApi$ListGeoAuditFindings, `geo_audit_id` is not nullable")
      }

      if (!missing(`sequence`) && is.null(`sequence`)) {
        stop("Invalid value for `sequence` when calling GEOAuditsApi$ListGeoAuditFindings, `sequence` is not nullable")
      }

      if (!missing(`page`) && is.null(`page`)) {
        stop("Invalid value for `page` when calling GEOAuditsApi$ListGeoAuditFindings, `page` is not nullable")
      }
      if (!is.null(`page`) && `page` <  1) {
        stop("Invalid value for `page` when calling GEOAuditsApi$ListGeoAuditFindings, must be bigger than or equal to 1.")
      }

      if (!missing(`per_page`) && is.null(`per_page`)) {
        stop("Invalid value for `per_page` when calling GEOAuditsApi$ListGeoAuditFindings, `per_page` is not nullable")
      }
      if (!is.null(`per_page`) && `per_page` >  100) {
        stop("Invalid value for `per_page` when calling GEOAuditsApi$ListGeoAuditFindings, must be smaller than or equal to 100.")
      }
      if (!is.null(`per_page`) && `per_page` <  1) {
        stop("Invalid value for `per_page` when calling GEOAuditsApi$ListGeoAuditFindings, must be bigger than or equal to 1.")
      }

      if (!missing(`output`) && is.null(`output`)) {
        stop("Invalid value for `output` when calling GEOAuditsApi$ListGeoAuditFindings, `output` is not nullable")
      }

      query_params[["project_id"]] <- `project_id`

      query_params[["page"]] <- `page`

      query_params[["per_page"]] <- `per_page`

      if (!is.null(`output`) && !(`output` %in% c("flat", "csv"))) {
        stop("Invalid value for output when calling GEOAuditsApi$ListGeoAuditFindings. Must be [flat, csv].")
      }
      query_params[["output"]] <- `output`

      local_var_url_path <- "/geo_audits/{geo_audit_id}/runs/{sequence}/findings"
      if (!missing(`geo_audit_id`)) {
        local_var_url_path <- gsub("\\{geo_audit_id\\}", URLencode(as.character(`geo_audit_id`), reserved = TRUE), local_var_url_path)
      }

      if (!missing(`sequence`)) {
        local_var_url_path <- gsub("\\{sequence\\}", URLencode(as.character(`sequence`), reserved = TRUE), local_var_url_path)
      }

      # Bearer token
      if (!is.null(self$api_client$bearer_token)) {
        header_params["Authorization"] <- paste("Bearer", self$api_client$bearer_token, sep = " ")
      }

      # The Accept request HTTP header
      local_var_accepts <- list("application/json")

      # The Content-Type representation header
      local_var_content_types <- list()

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "GET",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        # save response in a file
        if (!is.null(data_file)) {
          self$api_client$WriteFile(local_var_resp, data_file)
        }
        if (!.parse) {
          local_var_resp$content <- local_var_resp$response_as_text()
          return(local_var_resp)
        }

        deserialized_resp_obj <- tryCatch(
          self$api_client$DeserializeResponse(local_var_resp, "GeoAuditFindingList"),
          error = function(e) {
            stop("Failed to deserialize response")
          }
        )
        local_var_resp$content <- deserialized_resp_obj
        return(local_var_resp)
      } 
      
      local_var_error_msg <- local_var_resp$response_as_text()      
      if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        ApiResponse$new(content = paste("Server returned ", local_var_resp$status_code, " response status code."),
                        response = local_var_resp,
                        status_code = local_var_resp$status_code)
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        ApiResponse$new(content = "API client error",
                        response = local_var_resp,
                        status_code = local_var_resp$status_code)
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        if (is.null(local_var_resp$response) || all(local_var_resp$response == "")) {
          local_var_resp$response <- "API server error"
        }
        return(local_var_resp)
      }
    },

    #' @description
    #' List the issues of a GEO audit
    #'
    #' @param project_id Project ID
    #' @param geo_audit_id Audit id
    #' @param state (optional) open means open and not accepted; default all
    #' @param page (optional) No description (default value: 1)
    #' @param per_page (optional) No description (default value: 20)
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @param .parse Logical. If \code{TRUE} then the response will be parsed to a generated type. If \code{FALSE} the response will be returned as unparsed text.
    #'
    #' @return GeoAuditIssueList
    ListGeoAuditIssues = function(project_id, geo_audit_id, state = NULL, page = 1, per_page = 20, data_file = NULL, ..., .parse = TRUE) {
      local_var_response <- self$ListGeoAuditIssuesWithHttpInfo(project_id, geo_audit_id, state, page, per_page, data_file = data_file, ..., .parse = .parse)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        return(local_var_response$content)
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        return(local_var_response)
      }
    },

    #' @description
    #' List the issues of a GEO audit
    #'
    #' @param project_id Project ID
    #' @param geo_audit_id Audit id
    #' @param state (optional) open means open and not accepted; default all
    #' @param page (optional) No description (default value: 1)
    #' @param per_page (optional) No description (default value: 20)
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @param .parse Logical. If \code{TRUE} then the response will be parsed to a generated type. If \code{FALSE} the response will be returned as unparsed text.
    #'
    #' @return API response (GeoAuditIssueList) with additional information such as HTTP status code, headers
    ListGeoAuditIssuesWithHttpInfo = function(project_id, geo_audit_id, state = NULL, page = 1, per_page = 20, data_file = NULL, ..., .parse = TRUE) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE

      if (missing(`project_id`)) {
        stop("Missing required parameter `project_id`.")
      }

      if (missing(`geo_audit_id`)) {
        stop("Missing required parameter `geo_audit_id`.")
      }

      if (!missing(`project_id`) && is.null(`project_id`)) {
        stop("Invalid value for `project_id` when calling GEOAuditsApi$ListGeoAuditIssues, `project_id` is not nullable")
      }

      if (!missing(`geo_audit_id`) && is.null(`geo_audit_id`)) {
        stop("Invalid value for `geo_audit_id` when calling GEOAuditsApi$ListGeoAuditIssues, `geo_audit_id` is not nullable")
      }

      if (!missing(`state`) && is.null(`state`)) {
        stop("Invalid value for `state` when calling GEOAuditsApi$ListGeoAuditIssues, `state` is not nullable")
      }

      if (!missing(`page`) && is.null(`page`)) {
        stop("Invalid value for `page` when calling GEOAuditsApi$ListGeoAuditIssues, `page` is not nullable")
      }
      if (!is.null(`page`) && `page` <  1) {
        stop("Invalid value for `page` when calling GEOAuditsApi$ListGeoAuditIssues, must be bigger than or equal to 1.")
      }

      if (!missing(`per_page`) && is.null(`per_page`)) {
        stop("Invalid value for `per_page` when calling GEOAuditsApi$ListGeoAuditIssues, `per_page` is not nullable")
      }
      if (!is.null(`per_page`) && `per_page` >  100) {
        stop("Invalid value for `per_page` when calling GEOAuditsApi$ListGeoAuditIssues, must be smaller than or equal to 100.")
      }
      if (!is.null(`per_page`) && `per_page` <  1) {
        stop("Invalid value for `per_page` when calling GEOAuditsApi$ListGeoAuditIssues, must be bigger than or equal to 1.")
      }

      query_params[["project_id"]] <- `project_id`

      if (!is.null(`state`) && !(`state` %in% c("open", "accepted", "fixed", "gone"))) {
        stop("Invalid value for state when calling GEOAuditsApi$ListGeoAuditIssues. Must be [open, accepted, fixed, gone].")
      }
      query_params[["state"]] <- `state`

      query_params[["page"]] <- `page`

      query_params[["per_page"]] <- `per_page`

      local_var_url_path <- "/geo_audits/{geo_audit_id}/issues"
      if (!missing(`geo_audit_id`)) {
        local_var_url_path <- gsub("\\{geo_audit_id\\}", URLencode(as.character(`geo_audit_id`), reserved = TRUE), local_var_url_path)
      }

      # Bearer token
      if (!is.null(self$api_client$bearer_token)) {
        header_params["Authorization"] <- paste("Bearer", self$api_client$bearer_token, sep = " ")
      }

      # The Accept request HTTP header
      local_var_accepts <- list("application/json")

      # The Content-Type representation header
      local_var_content_types <- list()

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "GET",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        # save response in a file
        if (!is.null(data_file)) {
          self$api_client$WriteFile(local_var_resp, data_file)
        }
        if (!.parse) {
          local_var_resp$content <- local_var_resp$response_as_text()
          return(local_var_resp)
        }

        deserialized_resp_obj <- tryCatch(
          self$api_client$DeserializeResponse(local_var_resp, "GeoAuditIssueList"),
          error = function(e) {
            stop("Failed to deserialize response")
          }
        )
        local_var_resp$content <- deserialized_resp_obj
        return(local_var_resp)
      } 
      
      local_var_error_msg <- local_var_resp$response_as_text()      
      if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        ApiResponse$new(content = paste("Server returned ", local_var_resp$status_code, " response status code."),
                        response = local_var_resp,
                        status_code = local_var_resp$status_code)
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        ApiResponse$new(content = "API client error",
                        response = local_var_resp,
                        status_code = local_var_resp$status_code)
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        if (is.null(local_var_resp$response) || all(local_var_resp$response == "")) {
          local_var_resp$response <- "API server error"
        }
        return(local_var_resp)
      }
    },

    #' @description
    #' List the runs of a GEO audit
    #'
    #' @param project_id Project ID
    #' @param geo_audit_id Audit id
    #' @param page (optional) No description (default value: 1)
    #' @param per_page (optional) No description (default value: 20)
    #' @param output (optional) Rectangular output for BI tools (Tableau, Excel, Sheets, ELT). Omit for the default nested JSON. 'flat' returns the same metadata plus 'columns' and 'rows'; 'csv' returns those rows as text/csv. Errors are always returned as JSON.
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @param .parse Logical. If \code{TRUE} then the response will be parsed to a generated type. If \code{FALSE} the response will be returned as unparsed text.
    #'
    #' @return GeoAuditRunList
    ListGeoAuditRuns = function(project_id, geo_audit_id, page = 1, per_page = 20, output = NULL, data_file = NULL, ..., .parse = TRUE) {
      local_var_response <- self$ListGeoAuditRunsWithHttpInfo(project_id, geo_audit_id, page, per_page, output, data_file = data_file, ..., .parse = .parse)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        return(local_var_response$content)
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        return(local_var_response)
      }
    },

    #' @description
    #' List the runs of a GEO audit
    #'
    #' @param project_id Project ID
    #' @param geo_audit_id Audit id
    #' @param page (optional) No description (default value: 1)
    #' @param per_page (optional) No description (default value: 20)
    #' @param output (optional) Rectangular output for BI tools (Tableau, Excel, Sheets, ELT). Omit for the default nested JSON. 'flat' returns the same metadata plus 'columns' and 'rows'; 'csv' returns those rows as text/csv. Errors are always returned as JSON.
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @param .parse Logical. If \code{TRUE} then the response will be parsed to a generated type. If \code{FALSE} the response will be returned as unparsed text.
    #'
    #' @return API response (GeoAuditRunList) with additional information such as HTTP status code, headers
    ListGeoAuditRunsWithHttpInfo = function(project_id, geo_audit_id, page = 1, per_page = 20, output = NULL, data_file = NULL, ..., .parse = TRUE) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE

      if (missing(`project_id`)) {
        stop("Missing required parameter `project_id`.")
      }

      if (missing(`geo_audit_id`)) {
        stop("Missing required parameter `geo_audit_id`.")
      }

      if (!missing(`project_id`) && is.null(`project_id`)) {
        stop("Invalid value for `project_id` when calling GEOAuditsApi$ListGeoAuditRuns, `project_id` is not nullable")
      }

      if (!missing(`geo_audit_id`) && is.null(`geo_audit_id`)) {
        stop("Invalid value for `geo_audit_id` when calling GEOAuditsApi$ListGeoAuditRuns, `geo_audit_id` is not nullable")
      }

      if (!missing(`page`) && is.null(`page`)) {
        stop("Invalid value for `page` when calling GEOAuditsApi$ListGeoAuditRuns, `page` is not nullable")
      }
      if (!is.null(`page`) && `page` <  1) {
        stop("Invalid value for `page` when calling GEOAuditsApi$ListGeoAuditRuns, must be bigger than or equal to 1.")
      }

      if (!missing(`per_page`) && is.null(`per_page`)) {
        stop("Invalid value for `per_page` when calling GEOAuditsApi$ListGeoAuditRuns, `per_page` is not nullable")
      }
      if (!is.null(`per_page`) && `per_page` >  100) {
        stop("Invalid value for `per_page` when calling GEOAuditsApi$ListGeoAuditRuns, must be smaller than or equal to 100.")
      }
      if (!is.null(`per_page`) && `per_page` <  1) {
        stop("Invalid value for `per_page` when calling GEOAuditsApi$ListGeoAuditRuns, must be bigger than or equal to 1.")
      }

      if (!missing(`output`) && is.null(`output`)) {
        stop("Invalid value for `output` when calling GEOAuditsApi$ListGeoAuditRuns, `output` is not nullable")
      }

      query_params[["project_id"]] <- `project_id`

      query_params[["page"]] <- `page`

      query_params[["per_page"]] <- `per_page`

      if (!is.null(`output`) && !(`output` %in% c("flat", "csv"))) {
        stop("Invalid value for output when calling GEOAuditsApi$ListGeoAuditRuns. Must be [flat, csv].")
      }
      query_params[["output"]] <- `output`

      local_var_url_path <- "/geo_audits/{geo_audit_id}/runs"
      if (!missing(`geo_audit_id`)) {
        local_var_url_path <- gsub("\\{geo_audit_id\\}", URLencode(as.character(`geo_audit_id`), reserved = TRUE), local_var_url_path)
      }

      # Bearer token
      if (!is.null(self$api_client$bearer_token)) {
        header_params["Authorization"] <- paste("Bearer", self$api_client$bearer_token, sep = " ")
      }

      # The Accept request HTTP header
      local_var_accepts <- list("application/json")

      # The Content-Type representation header
      local_var_content_types <- list()

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "GET",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        # save response in a file
        if (!is.null(data_file)) {
          self$api_client$WriteFile(local_var_resp, data_file)
        }
        if (!.parse) {
          local_var_resp$content <- local_var_resp$response_as_text()
          return(local_var_resp)
        }

        deserialized_resp_obj <- tryCatch(
          self$api_client$DeserializeResponse(local_var_resp, "GeoAuditRunList"),
          error = function(e) {
            stop("Failed to deserialize response")
          }
        )
        local_var_resp$content <- deserialized_resp_obj
        return(local_var_resp)
      } 
      
      local_var_error_msg <- local_var_resp$response_as_text()      
      if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        ApiResponse$new(content = paste("Server returned ", local_var_resp$status_code, " response status code."),
                        response = local_var_resp,
                        status_code = local_var_resp$status_code)
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        ApiResponse$new(content = "API client error",
                        response = local_var_resp,
                        status_code = local_var_resp$status_code)
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        if (is.null(local_var_resp$response) || all(local_var_resp$response == "")) {
          local_var_resp$response <- "API server error"
        }
        return(local_var_resp)
      }
    },

    #' @description
    #' List GEO audits
    #'
    #' @param project_id Project ID
    #' @param audit_type (optional) No description
    #' @param status (optional) No description
    #' @param cadence (optional) No description
    #' @param page (optional) No description (default value: 1)
    #' @param per_page (optional) No description (default value: 20)
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @param .parse Logical. If \code{TRUE} then the response will be parsed to a generated type. If \code{FALSE} the response will be returned as unparsed text.
    #'
    #' @return GeoAuditList
    ListGeoAudits = function(project_id, audit_type = NULL, status = NULL, cadence = NULL, page = 1, per_page = 20, data_file = NULL, ..., .parse = TRUE) {
      local_var_response <- self$ListGeoAuditsWithHttpInfo(project_id, audit_type, status, cadence, page, per_page, data_file = data_file, ..., .parse = .parse)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        return(local_var_response$content)
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        return(local_var_response)
      }
    },

    #' @description
    #' List GEO audits
    #'
    #' @param project_id Project ID
    #' @param audit_type (optional) No description
    #' @param status (optional) No description
    #' @param cadence (optional) No description
    #' @param page (optional) No description (default value: 1)
    #' @param per_page (optional) No description (default value: 20)
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @param .parse Logical. If \code{TRUE} then the response will be parsed to a generated type. If \code{FALSE} the response will be returned as unparsed text.
    #'
    #' @return API response (GeoAuditList) with additional information such as HTTP status code, headers
    ListGeoAuditsWithHttpInfo = function(project_id, audit_type = NULL, status = NULL, cadence = NULL, page = 1, per_page = 20, data_file = NULL, ..., .parse = TRUE) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE

      if (missing(`project_id`)) {
        stop("Missing required parameter `project_id`.")
      }

      if (!missing(`project_id`) && is.null(`project_id`)) {
        stop("Invalid value for `project_id` when calling GEOAuditsApi$ListGeoAudits, `project_id` is not nullable")
      }

      if (!missing(`audit_type`) && is.null(`audit_type`)) {
        stop("Invalid value for `audit_type` when calling GEOAuditsApi$ListGeoAudits, `audit_type` is not nullable")
      }

      if (!missing(`status`) && is.null(`status`)) {
        stop("Invalid value for `status` when calling GEOAuditsApi$ListGeoAudits, `status` is not nullable")
      }

      if (!missing(`cadence`) && is.null(`cadence`)) {
        stop("Invalid value for `cadence` when calling GEOAuditsApi$ListGeoAudits, `cadence` is not nullable")
      }

      if (!missing(`page`) && is.null(`page`)) {
        stop("Invalid value for `page` when calling GEOAuditsApi$ListGeoAudits, `page` is not nullable")
      }
      if (!is.null(`page`) && `page` <  1) {
        stop("Invalid value for `page` when calling GEOAuditsApi$ListGeoAudits, must be bigger than or equal to 1.")
      }

      if (!missing(`per_page`) && is.null(`per_page`)) {
        stop("Invalid value for `per_page` when calling GEOAuditsApi$ListGeoAudits, `per_page` is not nullable")
      }
      if (!is.null(`per_page`) && `per_page` >  100) {
        stop("Invalid value for `per_page` when calling GEOAuditsApi$ListGeoAudits, must be smaller than or equal to 100.")
      }
      if (!is.null(`per_page`) && `per_page` <  1) {
        stop("Invalid value for `per_page` when calling GEOAuditsApi$ListGeoAudits, must be bigger than or equal to 1.")
      }

      query_params[["project_id"]] <- `project_id`

      if (!is.null(`audit_type`) && !(`audit_type` %in% c("agent_readiness", "robots_txt", "crawlability", "schema", "content_readiness", "discoverability", "site_structure"))) {
        stop("Invalid value for audit_type when calling GEOAuditsApi$ListGeoAudits. Must be [agent_readiness, robots_txt, crawlability, schema, content_readiness, discoverability, site_structure].")
      }
      query_params[["audit_type"]] <- `audit_type`

      if (!is.null(`status`) && !(`status` %in% c("active", "paused", "archived"))) {
        stop("Invalid value for status when calling GEOAuditsApi$ListGeoAudits. Must be [active, paused, archived].")
      }
      query_params[["status"]] <- `status`

      if (!is.null(`cadence`) && !(`cadence` %in% c("once", "weekly", "monthly"))) {
        stop("Invalid value for cadence when calling GEOAuditsApi$ListGeoAudits. Must be [once, weekly, monthly].")
      }
      query_params[["cadence"]] <- `cadence`

      query_params[["page"]] <- `page`

      query_params[["per_page"]] <- `per_page`

      local_var_url_path <- "/geo_audits"
      # Bearer token
      if (!is.null(self$api_client$bearer_token)) {
        header_params["Authorization"] <- paste("Bearer", self$api_client$bearer_token, sep = " ")
      }

      # The Accept request HTTP header
      local_var_accepts <- list("application/json")

      # The Content-Type representation header
      local_var_content_types <- list()

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "GET",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        # save response in a file
        if (!is.null(data_file)) {
          self$api_client$WriteFile(local_var_resp, data_file)
        }
        if (!.parse) {
          local_var_resp$content <- local_var_resp$response_as_text()
          return(local_var_resp)
        }

        deserialized_resp_obj <- tryCatch(
          self$api_client$DeserializeResponse(local_var_resp, "GeoAuditList"),
          error = function(e) {
            stop("Failed to deserialize response")
          }
        )
        local_var_resp$content <- deserialized_resp_obj
        return(local_var_resp)
      } 
      
      local_var_error_msg <- local_var_resp$response_as_text()      
      if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        ApiResponse$new(content = paste("Server returned ", local_var_resp$status_code, " response status code."),
                        response = local_var_resp,
                        status_code = local_var_resp$status_code)
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        ApiResponse$new(content = "API client error",
                        response = local_var_resp,
                        status_code = local_var_resp$status_code)
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        if (is.null(local_var_resp$response) || all(local_var_resp$response == "")) {
          local_var_resp$response <- "API server error"
        }
        return(local_var_resp)
      }
    },

    #' @description
    #' Run a GEO audit now
    #'
    #' @param project_id Project ID
    #' @param geo_audit_id Audit id
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @param .parse Logical. If \code{TRUE} then the response will be parsed to a generated type. If \code{FALSE} the response will be returned as unparsed text.
    #'
    #' @return GeoAuditRunResponse
    RunGeoAudit = function(project_id, geo_audit_id, data_file = NULL, ..., .parse = TRUE) {
      local_var_response <- self$RunGeoAuditWithHttpInfo(project_id, geo_audit_id, data_file = data_file, ..., .parse = .parse)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        return(local_var_response$content)
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        return(local_var_response)
      }
    },

    #' @description
    #' Run a GEO audit now
    #'
    #' @param project_id Project ID
    #' @param geo_audit_id Audit id
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @param .parse Logical. If \code{TRUE} then the response will be parsed to a generated type. If \code{FALSE} the response will be returned as unparsed text.
    #'
    #' @return API response (GeoAuditRunResponse) with additional information such as HTTP status code, headers
    RunGeoAuditWithHttpInfo = function(project_id, geo_audit_id, data_file = NULL, ..., .parse = TRUE) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE

      if (missing(`project_id`)) {
        stop("Missing required parameter `project_id`.")
      }

      if (missing(`geo_audit_id`)) {
        stop("Missing required parameter `geo_audit_id`.")
      }

      if (!missing(`project_id`) && is.null(`project_id`)) {
        stop("Invalid value for `project_id` when calling GEOAuditsApi$RunGeoAudit, `project_id` is not nullable")
      }

      if (!missing(`geo_audit_id`) && is.null(`geo_audit_id`)) {
        stop("Invalid value for `geo_audit_id` when calling GEOAuditsApi$RunGeoAudit, `geo_audit_id` is not nullable")
      }

      query_params[["project_id"]] <- `project_id`

      local_var_url_path <- "/geo_audits/{geo_audit_id}/runs"
      if (!missing(`geo_audit_id`)) {
        local_var_url_path <- gsub("\\{geo_audit_id\\}", URLencode(as.character(`geo_audit_id`), reserved = TRUE), local_var_url_path)
      }

      # Bearer token
      if (!is.null(self$api_client$bearer_token)) {
        header_params["Authorization"] <- paste("Bearer", self$api_client$bearer_token, sep = " ")
      }

      # The Accept request HTTP header
      local_var_accepts <- list("application/json")

      # The Content-Type representation header
      local_var_content_types <- list()

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "POST",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        # save response in a file
        if (!is.null(data_file)) {
          self$api_client$WriteFile(local_var_resp, data_file)
        }
        if (!.parse) {
          local_var_resp$content <- local_var_resp$response_as_text()
          return(local_var_resp)
        }

        deserialized_resp_obj <- tryCatch(
          self$api_client$DeserializeResponse(local_var_resp, "GeoAuditRunResponse"),
          error = function(e) {
            stop("Failed to deserialize response")
          }
        )
        local_var_resp$content <- deserialized_resp_obj
        return(local_var_resp)
      } 
      
      local_var_error_msg <- local_var_resp$response_as_text()      
      if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        ApiResponse$new(content = paste("Server returned ", local_var_resp$status_code, " response status code."),
                        response = local_var_resp,
                        status_code = local_var_resp$status_code)
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        ApiResponse$new(content = "API client error",
                        response = local_var_resp,
                        status_code = local_var_resp$status_code)
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        if (is.null(local_var_resp$response) || all(local_var_resp$response == "")) {
          local_var_resp$response <- "API server error"
        }
        return(local_var_resp)
      }
    },

    #' @description
    #' Update a GEO audit
    #'
    #' @param id Audit id
    #' @param geo_audit_update_request 
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @param .parse Logical. If \code{TRUE} then the response will be parsed to a generated type. If \code{FALSE} the response will be returned as unparsed text.
    #'
    #' @return GeoAuditResponse
    UpdateGeoAudit = function(id, geo_audit_update_request, data_file = NULL, ..., .parse = TRUE) {
      local_var_response <- self$UpdateGeoAuditWithHttpInfo(id, geo_audit_update_request, data_file = data_file, ..., .parse = .parse)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        return(local_var_response$content)
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        return(local_var_response)
      }
    },

    #' @description
    #' Update a GEO audit
    #'
    #' @param id Audit id
    #' @param geo_audit_update_request 
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @param .parse Logical. If \code{TRUE} then the response will be parsed to a generated type. If \code{FALSE} the response will be returned as unparsed text.
    #'
    #' @return API response (GeoAuditResponse) with additional information such as HTTP status code, headers
    UpdateGeoAuditWithHttpInfo = function(id, geo_audit_update_request, data_file = NULL, ..., .parse = TRUE) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE

      if (missing(`id`)) {
        stop("Missing required parameter `id`.")
      }

      if (missing(`geo_audit_update_request`)) {
        stop("Missing required parameter `geo_audit_update_request`.")
      }

      if (!missing(`id`) && is.null(`id`)) {
        stop("Invalid value for `id` when calling GEOAuditsApi$UpdateGeoAudit, `id` is not nullable")
      }

      if (!missing(`geo_audit_update_request`) && is.null(`geo_audit_update_request`)) {
        stop("Invalid value for `geo_audit_update_request` when calling GEOAuditsApi$UpdateGeoAudit, `geo_audit_update_request` is not nullable")
      }

      if (!is.null(`geo_audit_update_request`)) {
        local_var_body <- `geo_audit_update_request`$toJSONString()
      } else {
        local_var_body <- NULL
      }

      local_var_url_path <- "/geo_audits/{id}"
      if (!missing(`id`)) {
        local_var_url_path <- gsub("\\{id\\}", URLencode(as.character(`id`), reserved = TRUE), local_var_url_path)
      }

      # Bearer token
      if (!is.null(self$api_client$bearer_token)) {
        header_params["Authorization"] <- paste("Bearer", self$api_client$bearer_token, sep = " ")
      }

      # The Accept request HTTP header
      local_var_accepts <- list("application/json")

      # The Content-Type representation header
      local_var_content_types <- list("application/json")

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "PATCH",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        # save response in a file
        if (!is.null(data_file)) {
          self$api_client$WriteFile(local_var_resp, data_file)
        }
        if (!.parse) {
          local_var_resp$content <- local_var_resp$response_as_text()
          return(local_var_resp)
        }

        deserialized_resp_obj <- tryCatch(
          self$api_client$DeserializeResponse(local_var_resp, "GeoAuditResponse"),
          error = function(e) {
            stop("Failed to deserialize response")
          }
        )
        local_var_resp$content <- deserialized_resp_obj
        return(local_var_resp)
      } 
      
      local_var_error_msg <- local_var_resp$response_as_text()      
      if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        ApiResponse$new(content = paste("Server returned ", local_var_resp$status_code, " response status code."),
                        response = local_var_resp,
                        status_code = local_var_resp$status_code)
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        ApiResponse$new(content = "API client error",
                        response = local_var_resp,
                        status_code = local_var_resp$status_code)
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        if (is.null(local_var_resp$response) || all(local_var_resp$response == "")) {
          local_var_resp$response <- "API server error"
        }
        return(local_var_resp)
      }
    },

    #' @description
    #' Accept or reopen a GEO audit issue
    #'
    #' @param geo_audit_id Audit id
    #' @param id Issue id
    #' @param geo_audit_issue_update_request 
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @param .parse Logical. If \code{TRUE} then the response will be parsed to a generated type. If \code{FALSE} the response will be returned as unparsed text.
    #'
    #' @return GeoAuditIssueResponse
    UpdateGeoAuditIssue = function(geo_audit_id, id, geo_audit_issue_update_request, data_file = NULL, ..., .parse = TRUE) {
      local_var_response <- self$UpdateGeoAuditIssueWithHttpInfo(geo_audit_id, id, geo_audit_issue_update_request, data_file = data_file, ..., .parse = .parse)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        return(local_var_response$content)
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        return(local_var_response)
      }
    },

    #' @description
    #' Accept or reopen a GEO audit issue
    #'
    #' @param geo_audit_id Audit id
    #' @param id Issue id
    #' @param geo_audit_issue_update_request 
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @param .parse Logical. If \code{TRUE} then the response will be parsed to a generated type. If \code{FALSE} the response will be returned as unparsed text.
    #'
    #' @return API response (GeoAuditIssueResponse) with additional information such as HTTP status code, headers
    UpdateGeoAuditIssueWithHttpInfo = function(geo_audit_id, id, geo_audit_issue_update_request, data_file = NULL, ..., .parse = TRUE) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE

      if (missing(`geo_audit_id`)) {
        stop("Missing required parameter `geo_audit_id`.")
      }

      if (missing(`id`)) {
        stop("Missing required parameter `id`.")
      }

      if (missing(`geo_audit_issue_update_request`)) {
        stop("Missing required parameter `geo_audit_issue_update_request`.")
      }

      if (!missing(`geo_audit_id`) && is.null(`geo_audit_id`)) {
        stop("Invalid value for `geo_audit_id` when calling GEOAuditsApi$UpdateGeoAuditIssue, `geo_audit_id` is not nullable")
      }

      if (!missing(`id`) && is.null(`id`)) {
        stop("Invalid value for `id` when calling GEOAuditsApi$UpdateGeoAuditIssue, `id` is not nullable")
      }

      if (!missing(`geo_audit_issue_update_request`) && is.null(`geo_audit_issue_update_request`)) {
        stop("Invalid value for `geo_audit_issue_update_request` when calling GEOAuditsApi$UpdateGeoAuditIssue, `geo_audit_issue_update_request` is not nullable")
      }

      if (!is.null(`geo_audit_issue_update_request`)) {
        local_var_body <- `geo_audit_issue_update_request`$toJSONString()
      } else {
        local_var_body <- NULL
      }

      local_var_url_path <- "/geo_audits/{geo_audit_id}/issues/{id}"
      if (!missing(`geo_audit_id`)) {
        local_var_url_path <- gsub("\\{geo_audit_id\\}", URLencode(as.character(`geo_audit_id`), reserved = TRUE), local_var_url_path)
      }

      if (!missing(`id`)) {
        local_var_url_path <- gsub("\\{id\\}", URLencode(as.character(`id`), reserved = TRUE), local_var_url_path)
      }

      # Bearer token
      if (!is.null(self$api_client$bearer_token)) {
        header_params["Authorization"] <- paste("Bearer", self$api_client$bearer_token, sep = " ")
      }

      # The Accept request HTTP header
      local_var_accepts <- list("application/json")

      # The Content-Type representation header
      local_var_content_types <- list("application/json")

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "PATCH",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        # save response in a file
        if (!is.null(data_file)) {
          self$api_client$WriteFile(local_var_resp, data_file)
        }
        if (!.parse) {
          local_var_resp$content <- local_var_resp$response_as_text()
          return(local_var_resp)
        }

        deserialized_resp_obj <- tryCatch(
          self$api_client$DeserializeResponse(local_var_resp, "GeoAuditIssueResponse"),
          error = function(e) {
            stop("Failed to deserialize response")
          }
        )
        local_var_resp$content <- deserialized_resp_obj
        return(local_var_resp)
      } 
      
      local_var_error_msg <- local_var_resp$response_as_text()      
      if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        ApiResponse$new(content = paste("Server returned ", local_var_resp$status_code, " response status code."),
                        response = local_var_resp,
                        status_code = local_var_resp$status_code)
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        ApiResponse$new(content = "API client error",
                        response = local_var_resp,
                        status_code = local_var_resp$status_code)
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        if (is.null(local_var_resp$response) || all(local_var_resp$response == "")) {
          local_var_resp$response <- "API server error"
        }
        return(local_var_resp)
      }
    }
  )
)
