#' LLM Pulse API
#'
#' REST API client for LLM Pulse AI visibility analytics.
#'
#' The version of the OpenAPI document: 1.48.0
#' Contact: info@llmpulse.ai
#' Generated by: https://openapi-generator.tech
#'
#' @docType class
#' @title MentionsCitations operations
#' @description MentionsCitationsApi
#' @format An \code{R6Class} generator object
#' @field api_client Handles the client-server communication.
#'
#' @examples
#' \dontrun{
#' ####################  ListAllCitations  ####################
#'
#' library(llmpulse)
#' var_project_id <- 56 # integer | Project ID
#' var_competitors <- "competitors_example" # character | Comma-separated competitor IDs (unknown IDs return ERR_INVALID_PARAM) (Optional)
#' var_page <- 1 # integer |  (Optional)
#' var_per_page <- 20 # integer |  (Optional)
#' var_model <- "model_example" # character | Filter by AI model. Models the API key's user has not enabled are silently dropped. (Optional)
#' var_collection_id <- "12,34" # character | One collection/tag ID or a comma-separated list of IDs. A query value is always a string on the wire, so it is typed as one: the previous integer-or-string union made generators emit a wrapper type they could not serialize. (Optional)
#' var_prompt <- 56 # integer | Filter by prompt ID (Optional)
#' var_from <- "from_example" # character |  (Optional)
#' var_to <- "to_example" # character | End of the window. A date-only value such as 2026-09-01 covers that whole day. Pass a full timestamp to end the window earlier. (Optional)
#' var_output <- "output_example" # character | Rectangular output for BI tools (Tableau, Excel, Sheets, ELT). Omit for the default nested JSON. 'flat' returns the same metadata plus 'columns' and 'rows'; 'csv' returns those rows as text/csv. Errors are always returned as JSON. (Optional)
#'
#' #List all citations (brand + competitor)
#' api_instance <- MentionsCitationsApi$new()
#'
#' # Configure HTTP bearer authorization: BearerAuth
#' api_instance$api_client$bearer_token <- Sys.getenv("BEARER_TOKEN")
#'
#' api_instance$ListAllCitations(var_project_id, competitors = var_competitors, page = var_page, per_page = var_per_page, model = var_model, collection_id = var_collection_id, prompt = var_prompt, from = var_from, to = var_to, output = var_output)
#'
#'
#' ####################  ListAllMentions  ####################
#'
#' library(llmpulse)
#' var_project_id <- 56 # integer | Project ID
#' var_competitors <- "competitors_example" # character | Comma-separated competitor IDs (unknown IDs return ERR_INVALID_PARAM) (Optional)
#' var_page <- 1 # integer |  (Optional)
#' var_per_page <- 20 # integer |  (Optional)
#' var_model <- "model_example" # character | Filter by AI model. Models the API key's user has not enabled are silently dropped. (Optional)
#' var_collection_id <- "12,34" # character | One collection/tag ID or a comma-separated list of IDs. A query value is always a string on the wire, so it is typed as one: the previous integer-or-string union made generators emit a wrapper type they could not serialize. (Optional)
#' var_prompt <- 56 # integer | Filter by prompt ID (Optional)
#' var_from <- "from_example" # character |  (Optional)
#' var_to <- "to_example" # character | End of the window. A date-only value such as 2026-09-01 covers that whole day. Pass a full timestamp to end the window earlier. (Optional)
#' var_output <- "output_example" # character | Rectangular output for BI tools (Tableau, Excel, Sheets, ELT). Omit for the default nested JSON. 'flat' returns the same metadata plus 'columns' and 'rows'; 'csv' returns those rows as text/csv. Errors are always returned as JSON. (Optional)
#'
#' #List all mentions (brand + competitor)
#' api_instance <- MentionsCitationsApi$new()
#'
#' # Configure HTTP bearer authorization: BearerAuth
#' api_instance$api_client$bearer_token <- Sys.getenv("BEARER_TOKEN")
#'
#' api_instance$ListAllMentions(var_project_id, competitors = var_competitors, page = var_page, per_page = var_per_page, model = var_model, collection_id = var_collection_id, prompt = var_prompt, from = var_from, to = var_to, output = var_output)
#'
#'
#' ####################  ListCitations  ####################
#'
#' library(llmpulse)
#' var_project_id <- 56 # integer | Project ID
#' var_page <- 1 # integer |  (Optional)
#' var_per_page <- 20 # integer |  (Optional)
#' var_model <- "model_example" # character | Filter by AI model. Models the API key's user has not enabled are silently dropped. (Optional)
#' var_collection_id <- "12,34" # character | One collection/tag ID or a comma-separated list of IDs. A query value is always a string on the wire, so it is typed as one: the previous integer-or-string union made generators emit a wrapper type they could not serialize. (Optional)
#' var_country_code <- "country_code_example" # character | One ISO country code or a comma-separated list (e.g. US,GB,DE) (Optional)
#' var_language_code <- "language_code_example" # character | One ISO language code or a comma-separated list (e.g. en,es,de) (Optional)
#' var_prompt <- 56 # integer | Filter by prompt ID (Optional)
#' var_from <- "from_example" # character |  (Optional)
#' var_to <- "to_example" # character | End of the window. A date-only value such as 2026-09-01 covers that whole day. Pass a full timestamp to end the window earlier. (Optional)
#' var_output <- "output_example" # character | Rectangular output for BI tools (Tableau, Excel, Sheets, ELT). Omit for the default nested JSON. 'flat' returns the same metadata plus 'columns' and 'rows'; 'csv' returns those rows as text/csv. Errors are always returned as JSON. (Optional)
#'
#' #List brand citations
#' api_instance <- MentionsCitationsApi$new()
#'
#' # Configure HTTP bearer authorization: BearerAuth
#' api_instance$api_client$bearer_token <- Sys.getenv("BEARER_TOKEN")
#'
#' api_instance$ListCitations(var_project_id, page = var_page, per_page = var_per_page, model = var_model, collection_id = var_collection_id, country_code = var_country_code, language_code = var_language_code, prompt = var_prompt, from = var_from, to = var_to, output = var_output)
#'
#'
#' ####################  ListCompetitorCitations  ####################
#'
#' library(llmpulse)
#' var_project_id <- 56 # integer | Project ID
#' var_competitors <- "competitors_example" # character | Comma-separated competitor IDs (unknown IDs return ERR_INVALID_PARAM) (Optional)
#' var_page <- 1 # integer |  (Optional)
#' var_per_page <- 20 # integer |  (Optional)
#' var_model <- "model_example" # character | Filter by AI model. Models the API key's user has not enabled are silently dropped. (Optional)
#' var_collection_id <- "12,34" # character | One collection/tag ID or a comma-separated list of IDs. A query value is always a string on the wire, so it is typed as one: the previous integer-or-string union made generators emit a wrapper type they could not serialize. (Optional)
#' var_prompt <- 56 # integer | Filter by prompt ID (Optional)
#' var_from <- "from_example" # character |  (Optional)
#' var_to <- "to_example" # character | End of the window. A date-only value such as 2026-09-01 covers that whole day. Pass a full timestamp to end the window earlier. (Optional)
#' var_output <- "output_example" # character | Rectangular output for BI tools (Tableau, Excel, Sheets, ELT). Omit for the default nested JSON. 'flat' returns the same metadata plus 'columns' and 'rows'; 'csv' returns those rows as text/csv. Errors are always returned as JSON. (Optional)
#'
#' #List competitor citations
#' api_instance <- MentionsCitationsApi$new()
#'
#' # Configure HTTP bearer authorization: BearerAuth
#' api_instance$api_client$bearer_token <- Sys.getenv("BEARER_TOKEN")
#'
#' api_instance$ListCompetitorCitations(var_project_id, competitors = var_competitors, page = var_page, per_page = var_per_page, model = var_model, collection_id = var_collection_id, prompt = var_prompt, from = var_from, to = var_to, output = var_output)
#'
#'
#' ####################  ListCompetitorMentions  ####################
#'
#' library(llmpulse)
#' var_project_id <- 56 # integer | Project ID
#' var_competitors <- "competitors_example" # character | Comma-separated competitor IDs (unknown IDs return ERR_INVALID_PARAM) (Optional)
#' var_page <- 1 # integer |  (Optional)
#' var_per_page <- 20 # integer |  (Optional)
#' var_model <- "model_example" # character | Filter by AI model. Models the API key's user has not enabled are silently dropped. (Optional)
#' var_collection_id <- "12,34" # character | One collection/tag ID or a comma-separated list of IDs. A query value is always a string on the wire, so it is typed as one: the previous integer-or-string union made generators emit a wrapper type they could not serialize. (Optional)
#' var_prompt <- 56 # integer | Filter by prompt ID (Optional)
#' var_from <- "from_example" # character |  (Optional)
#' var_to <- "to_example" # character | End of the window. A date-only value such as 2026-09-01 covers that whole day. Pass a full timestamp to end the window earlier. (Optional)
#' var_output <- "output_example" # character | Rectangular output for BI tools (Tableau, Excel, Sheets, ELT). Omit for the default nested JSON. 'flat' returns the same metadata plus 'columns' and 'rows'; 'csv' returns those rows as text/csv. Errors are always returned as JSON. (Optional)
#'
#' #List competitor mentions
#' api_instance <- MentionsCitationsApi$new()
#'
#' # Configure HTTP bearer authorization: BearerAuth
#' api_instance$api_client$bearer_token <- Sys.getenv("BEARER_TOKEN")
#'
#' api_instance$ListCompetitorMentions(var_project_id, competitors = var_competitors, page = var_page, per_page = var_per_page, model = var_model, collection_id = var_collection_id, prompt = var_prompt, from = var_from, to = var_to, output = var_output)
#'
#'
#' ####################  ListMentions  ####################
#'
#' library(llmpulse)
#' var_project_id <- 56 # integer | Project ID
#' var_page <- 1 # integer |  (Optional)
#' var_per_page <- 20 # integer |  (Optional)
#' var_model <- "model_example" # character | Filter by AI model. Models the API key's user has not enabled are silently dropped. (Optional)
#' var_collection_id <- "12,34" # character | One collection/tag ID or a comma-separated list of IDs. A query value is always a string on the wire, so it is typed as one: the previous integer-or-string union made generators emit a wrapper type they could not serialize. (Optional)
#' var_country_code <- "country_code_example" # character | One ISO country code or a comma-separated list (e.g. US,GB,DE) (Optional)
#' var_language_code <- "language_code_example" # character | One ISO language code or a comma-separated list (e.g. en,es,de) (Optional)
#' var_prompt <- 56 # integer | Filter by prompt ID (Optional)
#' var_from <- "from_example" # character |  (Optional)
#' var_to <- "to_example" # character | End of the window. A date-only value such as 2026-09-01 covers that whole day. Pass a full timestamp to end the window earlier. (Optional)
#' var_output <- "output_example" # character | Rectangular output for BI tools (Tableau, Excel, Sheets, ELT). Omit for the default nested JSON. 'flat' returns the same metadata plus 'columns' and 'rows'; 'csv' returns those rows as text/csv. Errors are always returned as JSON. (Optional)
#'
#' #List brand mentions
#' api_instance <- MentionsCitationsApi$new()
#'
#' # Configure HTTP bearer authorization: BearerAuth
#' api_instance$api_client$bearer_token <- Sys.getenv("BEARER_TOKEN")
#'
#' api_instance$ListMentions(var_project_id, page = var_page, per_page = var_per_page, model = var_model, collection_id = var_collection_id, country_code = var_country_code, language_code = var_language_code, prompt = var_prompt, from = var_from, to = var_to, output = var_output)
#'
#'
#' }
#' @importFrom R6 R6Class
#' @importFrom base64enc base64encode
#' @export
MentionsCitationsApi <- R6::R6Class(
  "MentionsCitationsApi",
  public = list(
    api_client = NULL,

    #' @description
    #' Initialize a new MentionsCitationsApi.
    #'
    #' @param api_client An instance of API client.
    initialize = function(api_client) {
      if (!missing(api_client)) {
        self$api_client <- api_client
      } else {
        self$api_client <- ApiClient$new()
      }
    },

    #' @description
    #' List all citations (brand + competitor)
    #'
    #' @param project_id Project ID
    #' @param competitors (optional) Comma-separated competitor IDs (unknown IDs return ERR_INVALID_PARAM)
    #' @param page (optional) No description (default value: 1)
    #' @param per_page (optional) No description (default value: 20)
    #' @param model (optional) Filter by AI model. Models the API key's user has not enabled are silently dropped.
    #' @param collection_id (optional) One collection/tag ID or a comma-separated list of IDs. A query value is always a string on the wire, so it is typed as one: the previous integer-or-string union made generators emit a wrapper type they could not serialize.
    #' @param prompt (optional) Filter by prompt ID
    #' @param from (optional) No description
    #' @param to (optional) End of the window. A date-only value such as 2026-09-01 covers that whole day. Pass a full timestamp to end the window earlier.
    #' @param output (optional) Rectangular output for BI tools (Tableau, Excel, Sheets, ELT). Omit for the default nested JSON. 'flat' returns the same metadata plus 'columns' and 'rows'; 'csv' returns those rows as text/csv. Errors are always returned as JSON.
    #' @param ... Other optional arguments
    #'
    #' @return void
    ListAllCitations = function(project_id, competitors = NULL, page = 1, per_page = 20, model = NULL, collection_id = NULL, prompt = NULL, from = NULL, to = NULL, output = NULL, ...) {
      local_var_response <- self$ListAllCitationsWithHttpInfo(project_id, competitors, page, per_page, model, collection_id, prompt, from, to, output, ...)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        return(local_var_response$content)
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        return(local_var_response)
      }
    },

    #' @description
    #' List all citations (brand + competitor)
    #'
    #' @param project_id Project ID
    #' @param competitors (optional) Comma-separated competitor IDs (unknown IDs return ERR_INVALID_PARAM)
    #' @param page (optional) No description (default value: 1)
    #' @param per_page (optional) No description (default value: 20)
    #' @param model (optional) Filter by AI model. Models the API key's user has not enabled are silently dropped.
    #' @param collection_id (optional) One collection/tag ID or a comma-separated list of IDs. A query value is always a string on the wire, so it is typed as one: the previous integer-or-string union made generators emit a wrapper type they could not serialize.
    #' @param prompt (optional) Filter by prompt ID
    #' @param from (optional) No description
    #' @param to (optional) End of the window. A date-only value such as 2026-09-01 covers that whole day. Pass a full timestamp to end the window earlier.
    #' @param output (optional) Rectangular output for BI tools (Tableau, Excel, Sheets, ELT). Omit for the default nested JSON. 'flat' returns the same metadata plus 'columns' and 'rows'; 'csv' returns those rows as text/csv. Errors are always returned as JSON.
    #' @param ... Other optional arguments
    #'
    #' @return API response (void) with additional information such as HTTP status code, headers
    ListAllCitationsWithHttpInfo = function(project_id, competitors = NULL, page = 1, per_page = 20, model = NULL, collection_id = NULL, prompt = NULL, from = NULL, to = NULL, output = NULL, ...) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE

      if (missing(`project_id`)) {
        stop("Missing required parameter `project_id`.")
      }

      if (!missing(`project_id`) && is.null(`project_id`)) {
        stop("Invalid value for `project_id` when calling MentionsCitationsApi$ListAllCitations, `project_id` is not nullable")
      }

      if (!missing(`competitors`) && is.null(`competitors`)) {
        stop("Invalid value for `competitors` when calling MentionsCitationsApi$ListAllCitations, `competitors` is not nullable")
      }

      if (!missing(`page`) && is.null(`page`)) {
        stop("Invalid value for `page` when calling MentionsCitationsApi$ListAllCitations, `page` is not nullable")
      }
      if (!is.null(`page`) && `page` <  1) {
        stop("Invalid value for `page` when calling MentionsCitationsApi$ListAllCitations, must be bigger than or equal to 1.")
      }

      if (!missing(`per_page`) && is.null(`per_page`)) {
        stop("Invalid value for `per_page` when calling MentionsCitationsApi$ListAllCitations, `per_page` is not nullable")
      }
      if (!is.null(`per_page`) && `per_page` >  100) {
        stop("Invalid value for `per_page` when calling MentionsCitationsApi$ListAllCitations, must be smaller than or equal to 100.")
      }
      if (!is.null(`per_page`) && `per_page` <  1) {
        stop("Invalid value for `per_page` when calling MentionsCitationsApi$ListAllCitations, must be bigger than or equal to 1.")
      }

      if (!missing(`model`) && is.null(`model`)) {
        stop("Invalid value for `model` when calling MentionsCitationsApi$ListAllCitations, `model` is not nullable")
      }

      if (!missing(`collection_id`) && is.null(`collection_id`)) {
        stop("Invalid value for `collection_id` when calling MentionsCitationsApi$ListAllCitations, `collection_id` is not nullable")
      }
      if (!is.null(`collection_id`) && !stringr::str_detect(`collection_id`, "^\\d+(,\\d+)*$")) {
        stop("Invalid value for `collection_id` when calling MentionsCitationsApi$ListAllCitations, must conform to the pattern ^\\d+(,\\d+)*$.")
      }

      if (!missing(`prompt`) && is.null(`prompt`)) {
        stop("Invalid value for `prompt` when calling MentionsCitationsApi$ListAllCitations, `prompt` is not nullable")
      }

      if (!missing(`from`) && is.null(`from`)) {
        stop("Invalid value for `from` when calling MentionsCitationsApi$ListAllCitations, `from` is not nullable")
      }

      if (!missing(`to`) && is.null(`to`)) {
        stop("Invalid value for `to` when calling MentionsCitationsApi$ListAllCitations, `to` is not nullable")
      }

      if (!missing(`output`) && is.null(`output`)) {
        stop("Invalid value for `output` when calling MentionsCitationsApi$ListAllCitations, `output` is not nullable")
      }

      query_params[["project_id"]] <- `project_id`

      query_params[["competitors"]] <- `competitors`

      query_params[["page"]] <- `page`

      query_params[["per_page"]] <- `per_page`

      if (!is.null(`model`) && !(`model` %in% c("chatgpt", "perplexity", "gemini", "ai_overview", "ai_mode", "copilot", "claude", "grok", "deepseek", "meta_ai", "amazon_rufus", "naver_ai", "baidu_ai"))) {
        stop("Invalid value for model when calling MentionsCitationsApi$ListAllCitations. Must be [chatgpt, perplexity, gemini, ai_overview, ai_mode, copilot, claude, grok, deepseek, meta_ai, amazon_rufus, naver_ai, baidu_ai].")
      }
      query_params[["model"]] <- `model`

      query_params[["collection_id"]] <- `collection_id`

      query_params[["prompt"]] <- `prompt`

      query_params[["from"]] <- `from`

      query_params[["to"]] <- `to`

      if (!is.null(`output`) && !(`output` %in% c("flat", "csv"))) {
        stop("Invalid value for output when calling MentionsCitationsApi$ListAllCitations. Must be [flat, csv].")
      }
      query_params[["output"]] <- `output`

      local_var_url_path <- "/dimensions/all_citations"
      # Bearer token
      if (!is.null(self$api_client$bearer_token)) {
        header_params["Authorization"] <- paste("Bearer", self$api_client$bearer_token, sep = " ")
      }

      # The Accept request HTTP header
      local_var_accepts <- list()

      # The Content-Type representation header
      local_var_content_types <- list()

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "GET",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        local_var_resp$content <- NULL
        return(local_var_resp)
      } 
      
      local_var_error_msg <- local_var_resp$response_as_text()      
      if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        ApiResponse$new(content = paste("Server returned ", local_var_resp$status_code, " response status code."),
                        response = local_var_resp,
                        status_code = local_var_resp$status_code)
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        ApiResponse$new(content = "API client error",
                        response = local_var_resp,
                        status_code = local_var_resp$status_code)
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        if (is.null(local_var_resp$response) || all(local_var_resp$response == "")) {
          local_var_resp$response <- "API server error"
        }
        return(local_var_resp)
      }
    },

    #' @description
    #' List all mentions (brand + competitor)
    #'
    #' @param project_id Project ID
    #' @param competitors (optional) Comma-separated competitor IDs (unknown IDs return ERR_INVALID_PARAM)
    #' @param page (optional) No description (default value: 1)
    #' @param per_page (optional) No description (default value: 20)
    #' @param model (optional) Filter by AI model. Models the API key's user has not enabled are silently dropped.
    #' @param collection_id (optional) One collection/tag ID or a comma-separated list of IDs. A query value is always a string on the wire, so it is typed as one: the previous integer-or-string union made generators emit a wrapper type they could not serialize.
    #' @param prompt (optional) Filter by prompt ID
    #' @param from (optional) No description
    #' @param to (optional) End of the window. A date-only value such as 2026-09-01 covers that whole day. Pass a full timestamp to end the window earlier.
    #' @param output (optional) Rectangular output for BI tools (Tableau, Excel, Sheets, ELT). Omit for the default nested JSON. 'flat' returns the same metadata plus 'columns' and 'rows'; 'csv' returns those rows as text/csv. Errors are always returned as JSON.
    #' @param ... Other optional arguments
    #'
    #' @return void
    ListAllMentions = function(project_id, competitors = NULL, page = 1, per_page = 20, model = NULL, collection_id = NULL, prompt = NULL, from = NULL, to = NULL, output = NULL, ...) {
      local_var_response <- self$ListAllMentionsWithHttpInfo(project_id, competitors, page, per_page, model, collection_id, prompt, from, to, output, ...)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        return(local_var_response$content)
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        return(local_var_response)
      }
    },

    #' @description
    #' List all mentions (brand + competitor)
    #'
    #' @param project_id Project ID
    #' @param competitors (optional) Comma-separated competitor IDs (unknown IDs return ERR_INVALID_PARAM)
    #' @param page (optional) No description (default value: 1)
    #' @param per_page (optional) No description (default value: 20)
    #' @param model (optional) Filter by AI model. Models the API key's user has not enabled are silently dropped.
    #' @param collection_id (optional) One collection/tag ID or a comma-separated list of IDs. A query value is always a string on the wire, so it is typed as one: the previous integer-or-string union made generators emit a wrapper type they could not serialize.
    #' @param prompt (optional) Filter by prompt ID
    #' @param from (optional) No description
    #' @param to (optional) End of the window. A date-only value such as 2026-09-01 covers that whole day. Pass a full timestamp to end the window earlier.
    #' @param output (optional) Rectangular output for BI tools (Tableau, Excel, Sheets, ELT). Omit for the default nested JSON. 'flat' returns the same metadata plus 'columns' and 'rows'; 'csv' returns those rows as text/csv. Errors are always returned as JSON.
    #' @param ... Other optional arguments
    #'
    #' @return API response (void) with additional information such as HTTP status code, headers
    ListAllMentionsWithHttpInfo = function(project_id, competitors = NULL, page = 1, per_page = 20, model = NULL, collection_id = NULL, prompt = NULL, from = NULL, to = NULL, output = NULL, ...) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE

      if (missing(`project_id`)) {
        stop("Missing required parameter `project_id`.")
      }

      if (!missing(`project_id`) && is.null(`project_id`)) {
        stop("Invalid value for `project_id` when calling MentionsCitationsApi$ListAllMentions, `project_id` is not nullable")
      }

      if (!missing(`competitors`) && is.null(`competitors`)) {
        stop("Invalid value for `competitors` when calling MentionsCitationsApi$ListAllMentions, `competitors` is not nullable")
      }

      if (!missing(`page`) && is.null(`page`)) {
        stop("Invalid value for `page` when calling MentionsCitationsApi$ListAllMentions, `page` is not nullable")
      }
      if (!is.null(`page`) && `page` <  1) {
        stop("Invalid value for `page` when calling MentionsCitationsApi$ListAllMentions, must be bigger than or equal to 1.")
      }

      if (!missing(`per_page`) && is.null(`per_page`)) {
        stop("Invalid value for `per_page` when calling MentionsCitationsApi$ListAllMentions, `per_page` is not nullable")
      }
      if (!is.null(`per_page`) && `per_page` >  100) {
        stop("Invalid value for `per_page` when calling MentionsCitationsApi$ListAllMentions, must be smaller than or equal to 100.")
      }
      if (!is.null(`per_page`) && `per_page` <  1) {
        stop("Invalid value for `per_page` when calling MentionsCitationsApi$ListAllMentions, must be bigger than or equal to 1.")
      }

      if (!missing(`model`) && is.null(`model`)) {
        stop("Invalid value for `model` when calling MentionsCitationsApi$ListAllMentions, `model` is not nullable")
      }

      if (!missing(`collection_id`) && is.null(`collection_id`)) {
        stop("Invalid value for `collection_id` when calling MentionsCitationsApi$ListAllMentions, `collection_id` is not nullable")
      }
      if (!is.null(`collection_id`) && !stringr::str_detect(`collection_id`, "^\\d+(,\\d+)*$")) {
        stop("Invalid value for `collection_id` when calling MentionsCitationsApi$ListAllMentions, must conform to the pattern ^\\d+(,\\d+)*$.")
      }

      if (!missing(`prompt`) && is.null(`prompt`)) {
        stop("Invalid value for `prompt` when calling MentionsCitationsApi$ListAllMentions, `prompt` is not nullable")
      }

      if (!missing(`from`) && is.null(`from`)) {
        stop("Invalid value for `from` when calling MentionsCitationsApi$ListAllMentions, `from` is not nullable")
      }

      if (!missing(`to`) && is.null(`to`)) {
        stop("Invalid value for `to` when calling MentionsCitationsApi$ListAllMentions, `to` is not nullable")
      }

      if (!missing(`output`) && is.null(`output`)) {
        stop("Invalid value for `output` when calling MentionsCitationsApi$ListAllMentions, `output` is not nullable")
      }

      query_params[["project_id"]] <- `project_id`

      query_params[["competitors"]] <- `competitors`

      query_params[["page"]] <- `page`

      query_params[["per_page"]] <- `per_page`

      if (!is.null(`model`) && !(`model` %in% c("chatgpt", "perplexity", "gemini", "ai_overview", "ai_mode", "copilot", "claude", "grok", "deepseek", "meta_ai", "amazon_rufus", "naver_ai", "baidu_ai"))) {
        stop("Invalid value for model when calling MentionsCitationsApi$ListAllMentions. Must be [chatgpt, perplexity, gemini, ai_overview, ai_mode, copilot, claude, grok, deepseek, meta_ai, amazon_rufus, naver_ai, baidu_ai].")
      }
      query_params[["model"]] <- `model`

      query_params[["collection_id"]] <- `collection_id`

      query_params[["prompt"]] <- `prompt`

      query_params[["from"]] <- `from`

      query_params[["to"]] <- `to`

      if (!is.null(`output`) && !(`output` %in% c("flat", "csv"))) {
        stop("Invalid value for output when calling MentionsCitationsApi$ListAllMentions. Must be [flat, csv].")
      }
      query_params[["output"]] <- `output`

      local_var_url_path <- "/dimensions/all_mentions"
      # Bearer token
      if (!is.null(self$api_client$bearer_token)) {
        header_params["Authorization"] <- paste("Bearer", self$api_client$bearer_token, sep = " ")
      }

      # The Accept request HTTP header
      local_var_accepts <- list()

      # The Content-Type representation header
      local_var_content_types <- list()

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "GET",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        local_var_resp$content <- NULL
        return(local_var_resp)
      } 
      
      local_var_error_msg <- local_var_resp$response_as_text()      
      if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        ApiResponse$new(content = paste("Server returned ", local_var_resp$status_code, " response status code."),
                        response = local_var_resp,
                        status_code = local_var_resp$status_code)
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        ApiResponse$new(content = "API client error",
                        response = local_var_resp,
                        status_code = local_var_resp$status_code)
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        if (is.null(local_var_resp$response) || all(local_var_resp$response == "")) {
          local_var_resp$response <- "API server error"
        }
        return(local_var_resp)
      }
    },

    #' @description
    #' List brand citations
    #'
    #' @param project_id Project ID
    #' @param page (optional) No description (default value: 1)
    #' @param per_page (optional) No description (default value: 20)
    #' @param model (optional) Filter by AI model. Models the API key's user has not enabled are silently dropped.
    #' @param collection_id (optional) One collection/tag ID or a comma-separated list of IDs. A query value is always a string on the wire, so it is typed as one: the previous integer-or-string union made generators emit a wrapper type they could not serialize.
    #' @param country_code (optional) One ISO country code or a comma-separated list (e.g. US,GB,DE)
    #' @param language_code (optional) One ISO language code or a comma-separated list (e.g. en,es,de)
    #' @param prompt (optional) Filter by prompt ID
    #' @param from (optional) No description
    #' @param to (optional) End of the window. A date-only value such as 2026-09-01 covers that whole day. Pass a full timestamp to end the window earlier.
    #' @param output (optional) Rectangular output for BI tools (Tableau, Excel, Sheets, ELT). Omit for the default nested JSON. 'flat' returns the same metadata plus 'columns' and 'rows'; 'csv' returns those rows as text/csv. Errors are always returned as JSON.
    #' @param ... Other optional arguments
    #'
    #' @return void
    ListCitations = function(project_id, page = 1, per_page = 20, model = NULL, collection_id = NULL, country_code = NULL, language_code = NULL, prompt = NULL, from = NULL, to = NULL, output = NULL, ...) {
      local_var_response <- self$ListCitationsWithHttpInfo(project_id, page, per_page, model, collection_id, country_code, language_code, prompt, from, to, output, ...)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        return(local_var_response$content)
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        return(local_var_response)
      }
    },

    #' @description
    #' List brand citations
    #'
    #' @param project_id Project ID
    #' @param page (optional) No description (default value: 1)
    #' @param per_page (optional) No description (default value: 20)
    #' @param model (optional) Filter by AI model. Models the API key's user has not enabled are silently dropped.
    #' @param collection_id (optional) One collection/tag ID or a comma-separated list of IDs. A query value is always a string on the wire, so it is typed as one: the previous integer-or-string union made generators emit a wrapper type they could not serialize.
    #' @param country_code (optional) One ISO country code or a comma-separated list (e.g. US,GB,DE)
    #' @param language_code (optional) One ISO language code or a comma-separated list (e.g. en,es,de)
    #' @param prompt (optional) Filter by prompt ID
    #' @param from (optional) No description
    #' @param to (optional) End of the window. A date-only value such as 2026-09-01 covers that whole day. Pass a full timestamp to end the window earlier.
    #' @param output (optional) Rectangular output for BI tools (Tableau, Excel, Sheets, ELT). Omit for the default nested JSON. 'flat' returns the same metadata plus 'columns' and 'rows'; 'csv' returns those rows as text/csv. Errors are always returned as JSON.
    #' @param ... Other optional arguments
    #'
    #' @return API response (void) with additional information such as HTTP status code, headers
    ListCitationsWithHttpInfo = function(project_id, page = 1, per_page = 20, model = NULL, collection_id = NULL, country_code = NULL, language_code = NULL, prompt = NULL, from = NULL, to = NULL, output = NULL, ...) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE

      if (missing(`project_id`)) {
        stop("Missing required parameter `project_id`.")
      }

      if (!missing(`project_id`) && is.null(`project_id`)) {
        stop("Invalid value for `project_id` when calling MentionsCitationsApi$ListCitations, `project_id` is not nullable")
      }

      if (!missing(`page`) && is.null(`page`)) {
        stop("Invalid value for `page` when calling MentionsCitationsApi$ListCitations, `page` is not nullable")
      }
      if (!is.null(`page`) && `page` <  1) {
        stop("Invalid value for `page` when calling MentionsCitationsApi$ListCitations, must be bigger than or equal to 1.")
      }

      if (!missing(`per_page`) && is.null(`per_page`)) {
        stop("Invalid value for `per_page` when calling MentionsCitationsApi$ListCitations, `per_page` is not nullable")
      }
      if (!is.null(`per_page`) && `per_page` >  100) {
        stop("Invalid value for `per_page` when calling MentionsCitationsApi$ListCitations, must be smaller than or equal to 100.")
      }
      if (!is.null(`per_page`) && `per_page` <  1) {
        stop("Invalid value for `per_page` when calling MentionsCitationsApi$ListCitations, must be bigger than or equal to 1.")
      }

      if (!missing(`model`) && is.null(`model`)) {
        stop("Invalid value for `model` when calling MentionsCitationsApi$ListCitations, `model` is not nullable")
      }

      if (!missing(`collection_id`) && is.null(`collection_id`)) {
        stop("Invalid value for `collection_id` when calling MentionsCitationsApi$ListCitations, `collection_id` is not nullable")
      }
      if (!is.null(`collection_id`) && !stringr::str_detect(`collection_id`, "^\\d+(,\\d+)*$")) {
        stop("Invalid value for `collection_id` when calling MentionsCitationsApi$ListCitations, must conform to the pattern ^\\d+(,\\d+)*$.")
      }

      if (!missing(`country_code`) && is.null(`country_code`)) {
        stop("Invalid value for `country_code` when calling MentionsCitationsApi$ListCitations, `country_code` is not nullable")
      }

      if (!missing(`language_code`) && is.null(`language_code`)) {
        stop("Invalid value for `language_code` when calling MentionsCitationsApi$ListCitations, `language_code` is not nullable")
      }

      if (!missing(`prompt`) && is.null(`prompt`)) {
        stop("Invalid value for `prompt` when calling MentionsCitationsApi$ListCitations, `prompt` is not nullable")
      }

      if (!missing(`from`) && is.null(`from`)) {
        stop("Invalid value for `from` when calling MentionsCitationsApi$ListCitations, `from` is not nullable")
      }

      if (!missing(`to`) && is.null(`to`)) {
        stop("Invalid value for `to` when calling MentionsCitationsApi$ListCitations, `to` is not nullable")
      }

      if (!missing(`output`) && is.null(`output`)) {
        stop("Invalid value for `output` when calling MentionsCitationsApi$ListCitations, `output` is not nullable")
      }

      query_params[["project_id"]] <- `project_id`

      query_params[["page"]] <- `page`

      query_params[["per_page"]] <- `per_page`

      if (!is.null(`model`) && !(`model` %in% c("chatgpt", "perplexity", "gemini", "ai_overview", "ai_mode", "copilot", "claude", "grok", "deepseek", "meta_ai", "amazon_rufus", "naver_ai", "baidu_ai"))) {
        stop("Invalid value for model when calling MentionsCitationsApi$ListCitations. Must be [chatgpt, perplexity, gemini, ai_overview, ai_mode, copilot, claude, grok, deepseek, meta_ai, amazon_rufus, naver_ai, baidu_ai].")
      }
      query_params[["model"]] <- `model`

      query_params[["collection_id"]] <- `collection_id`

      query_params[["country_code"]] <- `country_code`

      query_params[["language_code"]] <- `language_code`

      query_params[["prompt"]] <- `prompt`

      query_params[["from"]] <- `from`

      query_params[["to"]] <- `to`

      if (!is.null(`output`) && !(`output` %in% c("flat", "csv"))) {
        stop("Invalid value for output when calling MentionsCitationsApi$ListCitations. Must be [flat, csv].")
      }
      query_params[["output"]] <- `output`

      local_var_url_path <- "/dimensions/citations"
      # Bearer token
      if (!is.null(self$api_client$bearer_token)) {
        header_params["Authorization"] <- paste("Bearer", self$api_client$bearer_token, sep = " ")
      }

      # The Accept request HTTP header
      local_var_accepts <- list()

      # The Content-Type representation header
      local_var_content_types <- list()

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "GET",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        local_var_resp$content <- NULL
        return(local_var_resp)
      } 
      
      local_var_error_msg <- local_var_resp$response_as_text()      
      if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        ApiResponse$new(content = paste("Server returned ", local_var_resp$status_code, " response status code."),
                        response = local_var_resp,
                        status_code = local_var_resp$status_code)
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        ApiResponse$new(content = "API client error",
                        response = local_var_resp,
                        status_code = local_var_resp$status_code)
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        if (is.null(local_var_resp$response) || all(local_var_resp$response == "")) {
          local_var_resp$response <- "API server error"
        }
        return(local_var_resp)
      }
    },

    #' @description
    #' List competitor citations
    #'
    #' @param project_id Project ID
    #' @param competitors (optional) Comma-separated competitor IDs (unknown IDs return ERR_INVALID_PARAM)
    #' @param page (optional) No description (default value: 1)
    #' @param per_page (optional) No description (default value: 20)
    #' @param model (optional) Filter by AI model. Models the API key's user has not enabled are silently dropped.
    #' @param collection_id (optional) One collection/tag ID or a comma-separated list of IDs. A query value is always a string on the wire, so it is typed as one: the previous integer-or-string union made generators emit a wrapper type they could not serialize.
    #' @param prompt (optional) Filter by prompt ID
    #' @param from (optional) No description
    #' @param to (optional) End of the window. A date-only value such as 2026-09-01 covers that whole day. Pass a full timestamp to end the window earlier.
    #' @param output (optional) Rectangular output for BI tools (Tableau, Excel, Sheets, ELT). Omit for the default nested JSON. 'flat' returns the same metadata plus 'columns' and 'rows'; 'csv' returns those rows as text/csv. Errors are always returned as JSON.
    #' @param ... Other optional arguments
    #'
    #' @return void
    ListCompetitorCitations = function(project_id, competitors = NULL, page = 1, per_page = 20, model = NULL, collection_id = NULL, prompt = NULL, from = NULL, to = NULL, output = NULL, ...) {
      local_var_response <- self$ListCompetitorCitationsWithHttpInfo(project_id, competitors, page, per_page, model, collection_id, prompt, from, to, output, ...)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        return(local_var_response$content)
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        return(local_var_response)
      }
    },

    #' @description
    #' List competitor citations
    #'
    #' @param project_id Project ID
    #' @param competitors (optional) Comma-separated competitor IDs (unknown IDs return ERR_INVALID_PARAM)
    #' @param page (optional) No description (default value: 1)
    #' @param per_page (optional) No description (default value: 20)
    #' @param model (optional) Filter by AI model. Models the API key's user has not enabled are silently dropped.
    #' @param collection_id (optional) One collection/tag ID or a comma-separated list of IDs. A query value is always a string on the wire, so it is typed as one: the previous integer-or-string union made generators emit a wrapper type they could not serialize.
    #' @param prompt (optional) Filter by prompt ID
    #' @param from (optional) No description
    #' @param to (optional) End of the window. A date-only value such as 2026-09-01 covers that whole day. Pass a full timestamp to end the window earlier.
    #' @param output (optional) Rectangular output for BI tools (Tableau, Excel, Sheets, ELT). Omit for the default nested JSON. 'flat' returns the same metadata plus 'columns' and 'rows'; 'csv' returns those rows as text/csv. Errors are always returned as JSON.
    #' @param ... Other optional arguments
    #'
    #' @return API response (void) with additional information such as HTTP status code, headers
    ListCompetitorCitationsWithHttpInfo = function(project_id, competitors = NULL, page = 1, per_page = 20, model = NULL, collection_id = NULL, prompt = NULL, from = NULL, to = NULL, output = NULL, ...) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE

      if (missing(`project_id`)) {
        stop("Missing required parameter `project_id`.")
      }

      if (!missing(`project_id`) && is.null(`project_id`)) {
        stop("Invalid value for `project_id` when calling MentionsCitationsApi$ListCompetitorCitations, `project_id` is not nullable")
      }

      if (!missing(`competitors`) && is.null(`competitors`)) {
        stop("Invalid value for `competitors` when calling MentionsCitationsApi$ListCompetitorCitations, `competitors` is not nullable")
      }

      if (!missing(`page`) && is.null(`page`)) {
        stop("Invalid value for `page` when calling MentionsCitationsApi$ListCompetitorCitations, `page` is not nullable")
      }
      if (!is.null(`page`) && `page` <  1) {
        stop("Invalid value for `page` when calling MentionsCitationsApi$ListCompetitorCitations, must be bigger than or equal to 1.")
      }

      if (!missing(`per_page`) && is.null(`per_page`)) {
        stop("Invalid value for `per_page` when calling MentionsCitationsApi$ListCompetitorCitations, `per_page` is not nullable")
      }
      if (!is.null(`per_page`) && `per_page` >  100) {
        stop("Invalid value for `per_page` when calling MentionsCitationsApi$ListCompetitorCitations, must be smaller than or equal to 100.")
      }
      if (!is.null(`per_page`) && `per_page` <  1) {
        stop("Invalid value for `per_page` when calling MentionsCitationsApi$ListCompetitorCitations, must be bigger than or equal to 1.")
      }

      if (!missing(`model`) && is.null(`model`)) {
        stop("Invalid value for `model` when calling MentionsCitationsApi$ListCompetitorCitations, `model` is not nullable")
      }

      if (!missing(`collection_id`) && is.null(`collection_id`)) {
        stop("Invalid value for `collection_id` when calling MentionsCitationsApi$ListCompetitorCitations, `collection_id` is not nullable")
      }
      if (!is.null(`collection_id`) && !stringr::str_detect(`collection_id`, "^\\d+(,\\d+)*$")) {
        stop("Invalid value for `collection_id` when calling MentionsCitationsApi$ListCompetitorCitations, must conform to the pattern ^\\d+(,\\d+)*$.")
      }

      if (!missing(`prompt`) && is.null(`prompt`)) {
        stop("Invalid value for `prompt` when calling MentionsCitationsApi$ListCompetitorCitations, `prompt` is not nullable")
      }

      if (!missing(`from`) && is.null(`from`)) {
        stop("Invalid value for `from` when calling MentionsCitationsApi$ListCompetitorCitations, `from` is not nullable")
      }

      if (!missing(`to`) && is.null(`to`)) {
        stop("Invalid value for `to` when calling MentionsCitationsApi$ListCompetitorCitations, `to` is not nullable")
      }

      if (!missing(`output`) && is.null(`output`)) {
        stop("Invalid value for `output` when calling MentionsCitationsApi$ListCompetitorCitations, `output` is not nullable")
      }

      query_params[["project_id"]] <- `project_id`

      query_params[["competitors"]] <- `competitors`

      query_params[["page"]] <- `page`

      query_params[["per_page"]] <- `per_page`

      if (!is.null(`model`) && !(`model` %in% c("chatgpt", "perplexity", "gemini", "ai_overview", "ai_mode", "copilot", "claude", "grok", "deepseek", "meta_ai", "amazon_rufus", "naver_ai", "baidu_ai"))) {
        stop("Invalid value for model when calling MentionsCitationsApi$ListCompetitorCitations. Must be [chatgpt, perplexity, gemini, ai_overview, ai_mode, copilot, claude, grok, deepseek, meta_ai, amazon_rufus, naver_ai, baidu_ai].")
      }
      query_params[["model"]] <- `model`

      query_params[["collection_id"]] <- `collection_id`

      query_params[["prompt"]] <- `prompt`

      query_params[["from"]] <- `from`

      query_params[["to"]] <- `to`

      if (!is.null(`output`) && !(`output` %in% c("flat", "csv"))) {
        stop("Invalid value for output when calling MentionsCitationsApi$ListCompetitorCitations. Must be [flat, csv].")
      }
      query_params[["output"]] <- `output`

      local_var_url_path <- "/dimensions/competitor_citations"
      # Bearer token
      if (!is.null(self$api_client$bearer_token)) {
        header_params["Authorization"] <- paste("Bearer", self$api_client$bearer_token, sep = " ")
      }

      # The Accept request HTTP header
      local_var_accepts <- list()

      # The Content-Type representation header
      local_var_content_types <- list()

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "GET",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        local_var_resp$content <- NULL
        return(local_var_resp)
      } 
      
      local_var_error_msg <- local_var_resp$response_as_text()      
      if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        ApiResponse$new(content = paste("Server returned ", local_var_resp$status_code, " response status code."),
                        response = local_var_resp,
                        status_code = local_var_resp$status_code)
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        ApiResponse$new(content = "API client error",
                        response = local_var_resp,
                        status_code = local_var_resp$status_code)
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        if (is.null(local_var_resp$response) || all(local_var_resp$response == "")) {
          local_var_resp$response <- "API server error"
        }
        return(local_var_resp)
      }
    },

    #' @description
    #' List competitor mentions
    #'
    #' @param project_id Project ID
    #' @param competitors (optional) Comma-separated competitor IDs (unknown IDs return ERR_INVALID_PARAM)
    #' @param page (optional) No description (default value: 1)
    #' @param per_page (optional) No description (default value: 20)
    #' @param model (optional) Filter by AI model. Models the API key's user has not enabled are silently dropped.
    #' @param collection_id (optional) One collection/tag ID or a comma-separated list of IDs. A query value is always a string on the wire, so it is typed as one: the previous integer-or-string union made generators emit a wrapper type they could not serialize.
    #' @param prompt (optional) Filter by prompt ID
    #' @param from (optional) No description
    #' @param to (optional) End of the window. A date-only value such as 2026-09-01 covers that whole day. Pass a full timestamp to end the window earlier.
    #' @param output (optional) Rectangular output for BI tools (Tableau, Excel, Sheets, ELT). Omit for the default nested JSON. 'flat' returns the same metadata plus 'columns' and 'rows'; 'csv' returns those rows as text/csv. Errors are always returned as JSON.
    #' @param ... Other optional arguments
    #'
    #' @return void
    ListCompetitorMentions = function(project_id, competitors = NULL, page = 1, per_page = 20, model = NULL, collection_id = NULL, prompt = NULL, from = NULL, to = NULL, output = NULL, ...) {
      local_var_response <- self$ListCompetitorMentionsWithHttpInfo(project_id, competitors, page, per_page, model, collection_id, prompt, from, to, output, ...)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        return(local_var_response$content)
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        return(local_var_response)
      }
    },

    #' @description
    #' List competitor mentions
    #'
    #' @param project_id Project ID
    #' @param competitors (optional) Comma-separated competitor IDs (unknown IDs return ERR_INVALID_PARAM)
    #' @param page (optional) No description (default value: 1)
    #' @param per_page (optional) No description (default value: 20)
    #' @param model (optional) Filter by AI model. Models the API key's user has not enabled are silently dropped.
    #' @param collection_id (optional) One collection/tag ID or a comma-separated list of IDs. A query value is always a string on the wire, so it is typed as one: the previous integer-or-string union made generators emit a wrapper type they could not serialize.
    #' @param prompt (optional) Filter by prompt ID
    #' @param from (optional) No description
    #' @param to (optional) End of the window. A date-only value such as 2026-09-01 covers that whole day. Pass a full timestamp to end the window earlier.
    #' @param output (optional) Rectangular output for BI tools (Tableau, Excel, Sheets, ELT). Omit for the default nested JSON. 'flat' returns the same metadata plus 'columns' and 'rows'; 'csv' returns those rows as text/csv. Errors are always returned as JSON.
    #' @param ... Other optional arguments
    #'
    #' @return API response (void) with additional information such as HTTP status code, headers
    ListCompetitorMentionsWithHttpInfo = function(project_id, competitors = NULL, page = 1, per_page = 20, model = NULL, collection_id = NULL, prompt = NULL, from = NULL, to = NULL, output = NULL, ...) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE

      if (missing(`project_id`)) {
        stop("Missing required parameter `project_id`.")
      }

      if (!missing(`project_id`) && is.null(`project_id`)) {
        stop("Invalid value for `project_id` when calling MentionsCitationsApi$ListCompetitorMentions, `project_id` is not nullable")
      }

      if (!missing(`competitors`) && is.null(`competitors`)) {
        stop("Invalid value for `competitors` when calling MentionsCitationsApi$ListCompetitorMentions, `competitors` is not nullable")
      }

      if (!missing(`page`) && is.null(`page`)) {
        stop("Invalid value for `page` when calling MentionsCitationsApi$ListCompetitorMentions, `page` is not nullable")
      }
      if (!is.null(`page`) && `page` <  1) {
        stop("Invalid value for `page` when calling MentionsCitationsApi$ListCompetitorMentions, must be bigger than or equal to 1.")
      }

      if (!missing(`per_page`) && is.null(`per_page`)) {
        stop("Invalid value for `per_page` when calling MentionsCitationsApi$ListCompetitorMentions, `per_page` is not nullable")
      }
      if (!is.null(`per_page`) && `per_page` >  100) {
        stop("Invalid value for `per_page` when calling MentionsCitationsApi$ListCompetitorMentions, must be smaller than or equal to 100.")
      }
      if (!is.null(`per_page`) && `per_page` <  1) {
        stop("Invalid value for `per_page` when calling MentionsCitationsApi$ListCompetitorMentions, must be bigger than or equal to 1.")
      }

      if (!missing(`model`) && is.null(`model`)) {
        stop("Invalid value for `model` when calling MentionsCitationsApi$ListCompetitorMentions, `model` is not nullable")
      }

      if (!missing(`collection_id`) && is.null(`collection_id`)) {
        stop("Invalid value for `collection_id` when calling MentionsCitationsApi$ListCompetitorMentions, `collection_id` is not nullable")
      }
      if (!is.null(`collection_id`) && !stringr::str_detect(`collection_id`, "^\\d+(,\\d+)*$")) {
        stop("Invalid value for `collection_id` when calling MentionsCitationsApi$ListCompetitorMentions, must conform to the pattern ^\\d+(,\\d+)*$.")
      }

      if (!missing(`prompt`) && is.null(`prompt`)) {
        stop("Invalid value for `prompt` when calling MentionsCitationsApi$ListCompetitorMentions, `prompt` is not nullable")
      }

      if (!missing(`from`) && is.null(`from`)) {
        stop("Invalid value for `from` when calling MentionsCitationsApi$ListCompetitorMentions, `from` is not nullable")
      }

      if (!missing(`to`) && is.null(`to`)) {
        stop("Invalid value for `to` when calling MentionsCitationsApi$ListCompetitorMentions, `to` is not nullable")
      }

      if (!missing(`output`) && is.null(`output`)) {
        stop("Invalid value for `output` when calling MentionsCitationsApi$ListCompetitorMentions, `output` is not nullable")
      }

      query_params[["project_id"]] <- `project_id`

      query_params[["competitors"]] <- `competitors`

      query_params[["page"]] <- `page`

      query_params[["per_page"]] <- `per_page`

      if (!is.null(`model`) && !(`model` %in% c("chatgpt", "perplexity", "gemini", "ai_overview", "ai_mode", "copilot", "claude", "grok", "deepseek", "meta_ai", "amazon_rufus", "naver_ai", "baidu_ai"))) {
        stop("Invalid value for model when calling MentionsCitationsApi$ListCompetitorMentions. Must be [chatgpt, perplexity, gemini, ai_overview, ai_mode, copilot, claude, grok, deepseek, meta_ai, amazon_rufus, naver_ai, baidu_ai].")
      }
      query_params[["model"]] <- `model`

      query_params[["collection_id"]] <- `collection_id`

      query_params[["prompt"]] <- `prompt`

      query_params[["from"]] <- `from`

      query_params[["to"]] <- `to`

      if (!is.null(`output`) && !(`output` %in% c("flat", "csv"))) {
        stop("Invalid value for output when calling MentionsCitationsApi$ListCompetitorMentions. Must be [flat, csv].")
      }
      query_params[["output"]] <- `output`

      local_var_url_path <- "/dimensions/competitor_mentions"
      # Bearer token
      if (!is.null(self$api_client$bearer_token)) {
        header_params["Authorization"] <- paste("Bearer", self$api_client$bearer_token, sep = " ")
      }

      # The Accept request HTTP header
      local_var_accepts <- list()

      # The Content-Type representation header
      local_var_content_types <- list()

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "GET",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        local_var_resp$content <- NULL
        return(local_var_resp)
      } 
      
      local_var_error_msg <- local_var_resp$response_as_text()      
      if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        ApiResponse$new(content = paste("Server returned ", local_var_resp$status_code, " response status code."),
                        response = local_var_resp,
                        status_code = local_var_resp$status_code)
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        ApiResponse$new(content = "API client error",
                        response = local_var_resp,
                        status_code = local_var_resp$status_code)
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        if (is.null(local_var_resp$response) || all(local_var_resp$response == "")) {
          local_var_resp$response <- "API server error"
        }
        return(local_var_resp)
      }
    },

    #' @description
    #' List brand mentions
    #'
    #' @param project_id Project ID
    #' @param page (optional) No description (default value: 1)
    #' @param per_page (optional) No description (default value: 20)
    #' @param model (optional) Filter by AI model. Models the API key's user has not enabled are silently dropped.
    #' @param collection_id (optional) One collection/tag ID or a comma-separated list of IDs. A query value is always a string on the wire, so it is typed as one: the previous integer-or-string union made generators emit a wrapper type they could not serialize.
    #' @param country_code (optional) One ISO country code or a comma-separated list (e.g. US,GB,DE)
    #' @param language_code (optional) One ISO language code or a comma-separated list (e.g. en,es,de)
    #' @param prompt (optional) Filter by prompt ID
    #' @param from (optional) No description
    #' @param to (optional) End of the window. A date-only value such as 2026-09-01 covers that whole day. Pass a full timestamp to end the window earlier.
    #' @param output (optional) Rectangular output for BI tools (Tableau, Excel, Sheets, ELT). Omit for the default nested JSON. 'flat' returns the same metadata plus 'columns' and 'rows'; 'csv' returns those rows as text/csv. Errors are always returned as JSON.
    #' @param ... Other optional arguments
    #'
    #' @return void
    ListMentions = function(project_id, page = 1, per_page = 20, model = NULL, collection_id = NULL, country_code = NULL, language_code = NULL, prompt = NULL, from = NULL, to = NULL, output = NULL, ...) {
      local_var_response <- self$ListMentionsWithHttpInfo(project_id, page, per_page, model, collection_id, country_code, language_code, prompt, from, to, output, ...)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        return(local_var_response$content)
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        return(local_var_response)
      }
    },

    #' @description
    #' List brand mentions
    #'
    #' @param project_id Project ID
    #' @param page (optional) No description (default value: 1)
    #' @param per_page (optional) No description (default value: 20)
    #' @param model (optional) Filter by AI model. Models the API key's user has not enabled are silently dropped.
    #' @param collection_id (optional) One collection/tag ID or a comma-separated list of IDs. A query value is always a string on the wire, so it is typed as one: the previous integer-or-string union made generators emit a wrapper type they could not serialize.
    #' @param country_code (optional) One ISO country code or a comma-separated list (e.g. US,GB,DE)
    #' @param language_code (optional) One ISO language code or a comma-separated list (e.g. en,es,de)
    #' @param prompt (optional) Filter by prompt ID
    #' @param from (optional) No description
    #' @param to (optional) End of the window. A date-only value such as 2026-09-01 covers that whole day. Pass a full timestamp to end the window earlier.
    #' @param output (optional) Rectangular output for BI tools (Tableau, Excel, Sheets, ELT). Omit for the default nested JSON. 'flat' returns the same metadata plus 'columns' and 'rows'; 'csv' returns those rows as text/csv. Errors are always returned as JSON.
    #' @param ... Other optional arguments
    #'
    #' @return API response (void) with additional information such as HTTP status code, headers
    ListMentionsWithHttpInfo = function(project_id, page = 1, per_page = 20, model = NULL, collection_id = NULL, country_code = NULL, language_code = NULL, prompt = NULL, from = NULL, to = NULL, output = NULL, ...) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE

      if (missing(`project_id`)) {
        stop("Missing required parameter `project_id`.")
      }

      if (!missing(`project_id`) && is.null(`project_id`)) {
        stop("Invalid value for `project_id` when calling MentionsCitationsApi$ListMentions, `project_id` is not nullable")
      }

      if (!missing(`page`) && is.null(`page`)) {
        stop("Invalid value for `page` when calling MentionsCitationsApi$ListMentions, `page` is not nullable")
      }
      if (!is.null(`page`) && `page` <  1) {
        stop("Invalid value for `page` when calling MentionsCitationsApi$ListMentions, must be bigger than or equal to 1.")
      }

      if (!missing(`per_page`) && is.null(`per_page`)) {
        stop("Invalid value for `per_page` when calling MentionsCitationsApi$ListMentions, `per_page` is not nullable")
      }
      if (!is.null(`per_page`) && `per_page` >  100) {
        stop("Invalid value for `per_page` when calling MentionsCitationsApi$ListMentions, must be smaller than or equal to 100.")
      }
      if (!is.null(`per_page`) && `per_page` <  1) {
        stop("Invalid value for `per_page` when calling MentionsCitationsApi$ListMentions, must be bigger than or equal to 1.")
      }

      if (!missing(`model`) && is.null(`model`)) {
        stop("Invalid value for `model` when calling MentionsCitationsApi$ListMentions, `model` is not nullable")
      }

      if (!missing(`collection_id`) && is.null(`collection_id`)) {
        stop("Invalid value for `collection_id` when calling MentionsCitationsApi$ListMentions, `collection_id` is not nullable")
      }
      if (!is.null(`collection_id`) && !stringr::str_detect(`collection_id`, "^\\d+(,\\d+)*$")) {
        stop("Invalid value for `collection_id` when calling MentionsCitationsApi$ListMentions, must conform to the pattern ^\\d+(,\\d+)*$.")
      }

      if (!missing(`country_code`) && is.null(`country_code`)) {
        stop("Invalid value for `country_code` when calling MentionsCitationsApi$ListMentions, `country_code` is not nullable")
      }

      if (!missing(`language_code`) && is.null(`language_code`)) {
        stop("Invalid value for `language_code` when calling MentionsCitationsApi$ListMentions, `language_code` is not nullable")
      }

      if (!missing(`prompt`) && is.null(`prompt`)) {
        stop("Invalid value for `prompt` when calling MentionsCitationsApi$ListMentions, `prompt` is not nullable")
      }

      if (!missing(`from`) && is.null(`from`)) {
        stop("Invalid value for `from` when calling MentionsCitationsApi$ListMentions, `from` is not nullable")
      }

      if (!missing(`to`) && is.null(`to`)) {
        stop("Invalid value for `to` when calling MentionsCitationsApi$ListMentions, `to` is not nullable")
      }

      if (!missing(`output`) && is.null(`output`)) {
        stop("Invalid value for `output` when calling MentionsCitationsApi$ListMentions, `output` is not nullable")
      }

      query_params[["project_id"]] <- `project_id`

      query_params[["page"]] <- `page`

      query_params[["per_page"]] <- `per_page`

      if (!is.null(`model`) && !(`model` %in% c("chatgpt", "perplexity", "gemini", "ai_overview", "ai_mode", "copilot", "claude", "grok", "deepseek", "meta_ai", "amazon_rufus", "naver_ai", "baidu_ai"))) {
        stop("Invalid value for model when calling MentionsCitationsApi$ListMentions. Must be [chatgpt, perplexity, gemini, ai_overview, ai_mode, copilot, claude, grok, deepseek, meta_ai, amazon_rufus, naver_ai, baidu_ai].")
      }
      query_params[["model"]] <- `model`

      query_params[["collection_id"]] <- `collection_id`

      query_params[["country_code"]] <- `country_code`

      query_params[["language_code"]] <- `language_code`

      query_params[["prompt"]] <- `prompt`

      query_params[["from"]] <- `from`

      query_params[["to"]] <- `to`

      if (!is.null(`output`) && !(`output` %in% c("flat", "csv"))) {
        stop("Invalid value for output when calling MentionsCitationsApi$ListMentions. Must be [flat, csv].")
      }
      query_params[["output"]] <- `output`

      local_var_url_path <- "/dimensions/mentions"
      # Bearer token
      if (!is.null(self$api_client$bearer_token)) {
        header_params["Authorization"] <- paste("Bearer", self$api_client$bearer_token, sep = " ")
      }

      # The Accept request HTTP header
      local_var_accepts <- list()

      # The Content-Type representation header
      local_var_content_types <- list()

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "GET",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        local_var_resp$content <- NULL
        return(local_var_resp)
      } 
      
      local_var_error_msg <- local_var_resp$response_as_text()      
      if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        ApiResponse$new(content = paste("Server returned ", local_var_resp$status_code, " response status code."),
                        response = local_var_resp,
                        status_code = local_var_resp$status_code)
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        ApiResponse$new(content = "API client error",
                        response = local_var_resp,
                        status_code = local_var_resp$status_code)
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        if (is.null(local_var_resp$response) || all(local_var_resp$response == "")) {
          local_var_resp$response <- "API server error"
        }
        return(local_var_resp)
      }
    }
  )
)
