#' LLM Pulse API
#'
#' REST API client for LLM Pulse AI visibility analytics.
#'
#' The version of the OpenAPI document: 1.55.0
#' Contact: info@llmpulse.ai
#' Generated by: https://openapi-generator.tech
#'
#' @docType class
#' @title StoreIntegrations operations
#' @description StoreIntegrationsApi
#' @format An \code{R6Class} generator object
#' @field api_client Handles the client-server communication.
#'
#' @examples
#' \dontrun{
#' ####################  AcceptCatalogPromptSuggestions  ####################
#'
#' library(llmpulse)
#' var_catalog_prompt_suggestion_ids_request <- CatalogPromptSuggestionIdsRequest$new(123, c(123)) # CatalogPromptSuggestionIdsRequest | 
#'
#' #Accept catalog prompt suggestions
#' api_instance <- StoreIntegrationsApi$new()
#'
#' # Configure HTTP bearer authorization: BearerAuth
#' api_instance$api_client$bearer_token <- Sys.getenv("BEARER_TOKEN")
#'
#' # to save the result into a file, simply add the optional `data_file` parameter, e.g.
#' # result <- api_instance$AcceptCatalogPromptSuggestions(var_catalog_prompt_suggestion_ids_requestdata_file = "result.txt")
#' result <- api_instance$AcceptCatalogPromptSuggestions(var_catalog_prompt_suggestion_ids_request)
#' dput(result)
#'
#'
#' ####################  CreateCatalogPromptSuggestions  ####################
#'
#' library(llmpulse)
#' var_catalog_prompt_suggestions_create_request <- CatalogPromptSuggestionsCreateRequest$new(123, "shopify", c(CatalogProduct$new("external_id_example", "title_example", "handle_example", "product_type_example", "vendor_example", c("tags_example"), c("collections_example"), "url_example")), "country_code_example", "language_code_example") # CatalogPromptSuggestionsCreateRequest | 
#'
#' #Suggest buyer prompts from catalog products
#' api_instance <- StoreIntegrationsApi$new()
#'
#' # Configure HTTP bearer authorization: BearerAuth
#' api_instance$api_client$bearer_token <- Sys.getenv("BEARER_TOKEN")
#'
#' # to save the result into a file, simply add the optional `data_file` parameter, e.g.
#' # result <- api_instance$CreateCatalogPromptSuggestions(var_catalog_prompt_suggestions_create_requestdata_file = "result.txt")
#' result <- api_instance$CreateCatalogPromptSuggestions(var_catalog_prompt_suggestions_create_request)
#' dput(result)
#'
#'
#' ####################  GetStoreConnection  ####################
#'
#' library(llmpulse)
#' var_platform <- "platform_example" # character | Store platform
#' var_domain <- "domain_example" # character | Store domain, with or without scheme, e.g. acme-store.com
#'
#' #Match a store to a project
#' api_instance <- StoreIntegrationsApi$new()
#'
#' # Configure HTTP bearer authorization: BearerAuth
#' api_instance$api_client$bearer_token <- Sys.getenv("BEARER_TOKEN")
#'
#' # to save the result into a file, simply add the optional `data_file` parameter, e.g.
#' # result <- api_instance$GetStoreConnection(var_platform, var_domaindata_file = "result.txt")
#' result <- api_instance$GetStoreConnection(var_platform, var_domain)
#' dput(result)
#'
#'
#' ####################  ListAiOrders  ####################
#'
#' library(llmpulse)
#' var_project_id <- 56 # integer | Project ID
#' var_platform <- "shopify" # character | Store platform (Optional)
#' var_from <- "from_example" # character | First day (YYYY-MM-DD). Defaults to 89 days before to (Optional)
#' var_to <- "to_example" # character | Last day (YYYY-MM-DD). Defaults to today; the window is at most 400 days (Optional)
#'
#' #Read AI-referred store orders
#' api_instance <- StoreIntegrationsApi$new()
#'
#' # Configure HTTP bearer authorization: BearerAuth
#' api_instance$api_client$bearer_token <- Sys.getenv("BEARER_TOKEN")
#'
#' # to save the result into a file, simply add the optional `data_file` parameter, e.g.
#' # result <- api_instance$ListAiOrders(var_project_id, platform = var_platform, from = var_from, to = var_todata_file = "result.txt")
#' result <- api_instance$ListAiOrders(var_project_id, platform = var_platform, from = var_from, to = var_to)
#' dput(result)
#'
#'
#' ####################  ListCatalogPromptSuggestions  ####################
#'
#' library(llmpulse)
#' var_project_id <- 56 # integer | Project ID
#' var_status <- "status_example" # character | Only suggestions in this status (Optional)
#' var_product_external_id <- "product_external_id_example" # character | Only suggestions for this store product id (Optional)
#' var_page <- 1 # integer |  (Optional)
#' var_per_page <- 50 # integer |  (Optional)
#'
#' #List catalog prompt suggestions
#' api_instance <- StoreIntegrationsApi$new()
#'
#' # Configure HTTP bearer authorization: BearerAuth
#' api_instance$api_client$bearer_token <- Sys.getenv("BEARER_TOKEN")
#'
#' # to save the result into a file, simply add the optional `data_file` parameter, e.g.
#' # result <- api_instance$ListCatalogPromptSuggestions(var_project_id, status = var_status, product_external_id = var_product_external_id, page = var_page, per_page = var_per_pagedata_file = "result.txt")
#' result <- api_instance$ListCatalogPromptSuggestions(var_project_id, status = var_status, product_external_id = var_product_external_id, page = var_page, per_page = var_per_page)
#' dput(result)
#'
#'
#' ####################  RejectCatalogPromptSuggestions  ####################
#'
#' library(llmpulse)
#' var_catalog_prompt_suggestion_ids_request <- CatalogPromptSuggestionIdsRequest$new(123, c(123)) # CatalogPromptSuggestionIdsRequest | 
#'
#' #Reject catalog prompt suggestions
#' api_instance <- StoreIntegrationsApi$new()
#'
#' # Configure HTTP bearer authorization: BearerAuth
#' api_instance$api_client$bearer_token <- Sys.getenv("BEARER_TOKEN")
#'
#' # to save the result into a file, simply add the optional `data_file` parameter, e.g.
#' # result <- api_instance$RejectCatalogPromptSuggestions(var_catalog_prompt_suggestion_ids_requestdata_file = "result.txt")
#' result <- api_instance$RejectCatalogPromptSuggestions(var_catalog_prompt_suggestion_ids_request)
#' dput(result)
#'
#'
#' ####################  ReplaceAiOrders  ####################
#'
#' library(llmpulse)
#' var_ai_orders_update_request <- AiOrdersUpdateRequest$new(123, "shopify", "currency_example", "from_example", "to_example", c(AiOrdersUpdateRequest_days_inner$new("day_example", "referrer_example", 123, "revenue_example"))) # AiOrdersUpdateRequest | 
#'
#' #Replace AI-referred store orders for a window
#' api_instance <- StoreIntegrationsApi$new()
#'
#' # Configure HTTP bearer authorization: BearerAuth
#' api_instance$api_client$bearer_token <- Sys.getenv("BEARER_TOKEN")
#'
#' # to save the result into a file, simply add the optional `data_file` parameter, e.g.
#' # result <- api_instance$ReplaceAiOrders(var_ai_orders_update_requestdata_file = "result.txt")
#' result <- api_instance$ReplaceAiOrders(var_ai_orders_update_request)
#' dput(result)
#'
#'
#' }
#' @importFrom R6 R6Class
#' @importFrom base64enc base64encode
#' @export
StoreIntegrationsApi <- R6::R6Class(
  "StoreIntegrationsApi",
  public = list(
    api_client = NULL,

    #' @description
    #' Initialize a new StoreIntegrationsApi.
    #'
    #' @param api_client An instance of API client.
    initialize = function(api_client) {
      if (!missing(api_client)) {
        self$api_client <- api_client
      } else {
        self$api_client <- ApiClient$new()
      }
    },

    #' @description
    #' Accept catalog prompt suggestions
    #'
    #' @param catalog_prompt_suggestion_ids_request 
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @param .parse Logical. If \code{TRUE} then the response will be parsed to a generated type. If \code{FALSE} the response will be returned as unparsed text.
    #'
    #' @return CatalogPromptSuggestionsAcceptResponse
    AcceptCatalogPromptSuggestions = function(catalog_prompt_suggestion_ids_request, data_file = NULL, ..., .parse = TRUE) {
      local_var_response <- self$AcceptCatalogPromptSuggestionsWithHttpInfo(catalog_prompt_suggestion_ids_request, data_file = data_file, ..., .parse = .parse)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        return(local_var_response$content)
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        return(local_var_response)
      }
    },

    #' @description
    #' Accept catalog prompt suggestions
    #'
    #' @param catalog_prompt_suggestion_ids_request 
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @param .parse Logical. If \code{TRUE} then the response will be parsed to a generated type. If \code{FALSE} the response will be returned as unparsed text.
    #'
    #' @return API response (CatalogPromptSuggestionsAcceptResponse) with additional information such as HTTP status code, headers
    AcceptCatalogPromptSuggestionsWithHttpInfo = function(catalog_prompt_suggestion_ids_request, data_file = NULL, ..., .parse = TRUE) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE

      if (missing(`catalog_prompt_suggestion_ids_request`)) {
        stop("Missing required parameter `catalog_prompt_suggestion_ids_request`.")
      }

      if (!missing(`catalog_prompt_suggestion_ids_request`) && is.null(`catalog_prompt_suggestion_ids_request`)) {
        stop("Invalid value for `catalog_prompt_suggestion_ids_request` when calling StoreIntegrationsApi$AcceptCatalogPromptSuggestions, `catalog_prompt_suggestion_ids_request` is not nullable")
      }

      if (!is.null(`catalog_prompt_suggestion_ids_request`)) {
        local_var_body <- `catalog_prompt_suggestion_ids_request`$toJSONString()
      } else {
        local_var_body <- NULL
      }

      local_var_url_path <- "/catalog_prompt_suggestions/accept"
      # Bearer token
      if (!is.null(self$api_client$bearer_token)) {
        header_params["Authorization"] <- paste("Bearer", self$api_client$bearer_token, sep = " ")
      }

      # The Accept request HTTP header
      local_var_accepts <- list("application/json")

      # The Content-Type representation header
      local_var_content_types <- list("application/json")

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "POST",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        # save response in a file
        if (!is.null(data_file)) {
          self$api_client$WriteFile(local_var_resp, data_file)
        }
        if (!.parse) {
          local_var_resp$content <- local_var_resp$response_as_text()
          return(local_var_resp)
        }

        deserialized_resp_obj <- tryCatch(
          self$api_client$DeserializeResponse(local_var_resp, "CatalogPromptSuggestionsAcceptResponse"),
          error = function(e) {
            stop("Failed to deserialize response")
          }
        )
        local_var_resp$content <- deserialized_resp_obj
        return(local_var_resp)
      } 
      
      local_var_error_msg <- local_var_resp$response_as_text()      
      if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        ApiResponse$new(content = paste("Server returned ", local_var_resp$status_code, " response status code."),
                        response = local_var_resp,
                        status_code = local_var_resp$status_code)
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        ApiResponse$new(content = "API client error",
                        response = local_var_resp,
                        status_code = local_var_resp$status_code)
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        if (is.null(local_var_resp$response) || all(local_var_resp$response == "")) {
          local_var_resp$response <- "API server error"
        }
        return(local_var_resp)
      }
    },

    #' @description
    #' Suggest buyer prompts from catalog products
    #'
    #' @param catalog_prompt_suggestions_create_request 
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @param .parse Logical. If \code{TRUE} then the response will be parsed to a generated type. If \code{FALSE} the response will be returned as unparsed text.
    #'
    #' @return CatalogPromptSuggestionsCreateResponse
    CreateCatalogPromptSuggestions = function(catalog_prompt_suggestions_create_request, data_file = NULL, ..., .parse = TRUE) {
      local_var_response <- self$CreateCatalogPromptSuggestionsWithHttpInfo(catalog_prompt_suggestions_create_request, data_file = data_file, ..., .parse = .parse)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        return(local_var_response$content)
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        return(local_var_response)
      }
    },

    #' @description
    #' Suggest buyer prompts from catalog products
    #'
    #' @param catalog_prompt_suggestions_create_request 
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @param .parse Logical. If \code{TRUE} then the response will be parsed to a generated type. If \code{FALSE} the response will be returned as unparsed text.
    #'
    #' @return API response (CatalogPromptSuggestionsCreateResponse) with additional information such as HTTP status code, headers
    CreateCatalogPromptSuggestionsWithHttpInfo = function(catalog_prompt_suggestions_create_request, data_file = NULL, ..., .parse = TRUE) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE

      if (missing(`catalog_prompt_suggestions_create_request`)) {
        stop("Missing required parameter `catalog_prompt_suggestions_create_request`.")
      }

      if (!missing(`catalog_prompt_suggestions_create_request`) && is.null(`catalog_prompt_suggestions_create_request`)) {
        stop("Invalid value for `catalog_prompt_suggestions_create_request` when calling StoreIntegrationsApi$CreateCatalogPromptSuggestions, `catalog_prompt_suggestions_create_request` is not nullable")
      }

      if (!is.null(`catalog_prompt_suggestions_create_request`)) {
        local_var_body <- `catalog_prompt_suggestions_create_request`$toJSONString()
      } else {
        local_var_body <- NULL
      }

      local_var_url_path <- "/catalog_prompt_suggestions"
      # Bearer token
      if (!is.null(self$api_client$bearer_token)) {
        header_params["Authorization"] <- paste("Bearer", self$api_client$bearer_token, sep = " ")
      }

      # The Accept request HTTP header
      local_var_accepts <- list("application/json")

      # The Content-Type representation header
      local_var_content_types <- list("application/json")

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "POST",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        # save response in a file
        if (!is.null(data_file)) {
          self$api_client$WriteFile(local_var_resp, data_file)
        }
        if (!.parse) {
          local_var_resp$content <- local_var_resp$response_as_text()
          return(local_var_resp)
        }

        deserialized_resp_obj <- tryCatch(
          self$api_client$DeserializeResponse(local_var_resp, "CatalogPromptSuggestionsCreateResponse"),
          error = function(e) {
            stop("Failed to deserialize response")
          }
        )
        local_var_resp$content <- deserialized_resp_obj
        return(local_var_resp)
      } 
      
      local_var_error_msg <- local_var_resp$response_as_text()      
      if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        ApiResponse$new(content = paste("Server returned ", local_var_resp$status_code, " response status code."),
                        response = local_var_resp,
                        status_code = local_var_resp$status_code)
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        ApiResponse$new(content = "API client error",
                        response = local_var_resp,
                        status_code = local_var_resp$status_code)
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        if (is.null(local_var_resp$response) || all(local_var_resp$response == "")) {
          local_var_resp$response <- "API server error"
        }
        return(local_var_resp)
      }
    },

    #' @description
    #' Match a store to a project
    #'
    #' @param platform Store platform
    #' @param domain Store domain, with or without scheme, e.g. acme-store.com
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @param .parse Logical. If \code{TRUE} then the response will be parsed to a generated type. If \code{FALSE} the response will be returned as unparsed text.
    #'
    #' @return StoreConnectionResponse
    GetStoreConnection = function(platform, domain, data_file = NULL, ..., .parse = TRUE) {
      local_var_response <- self$GetStoreConnectionWithHttpInfo(platform, domain, data_file = data_file, ..., .parse = .parse)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        return(local_var_response$content)
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        return(local_var_response)
      }
    },

    #' @description
    #' Match a store to a project
    #'
    #' @param platform Store platform
    #' @param domain Store domain, with or without scheme, e.g. acme-store.com
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @param .parse Logical. If \code{TRUE} then the response will be parsed to a generated type. If \code{FALSE} the response will be returned as unparsed text.
    #'
    #' @return API response (StoreConnectionResponse) with additional information such as HTTP status code, headers
    GetStoreConnectionWithHttpInfo = function(platform, domain, data_file = NULL, ..., .parse = TRUE) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE

      if (missing(`platform`)) {
        stop("Missing required parameter `platform`.")
      }

      if (missing(`domain`)) {
        stop("Missing required parameter `domain`.")
      }

      if (!missing(`platform`) && is.null(`platform`)) {
        stop("Invalid value for `platform` when calling StoreIntegrationsApi$GetStoreConnection, `platform` is not nullable")
      }

      if (!missing(`domain`) && is.null(`domain`)) {
        stop("Invalid value for `domain` when calling StoreIntegrationsApi$GetStoreConnection, `domain` is not nullable")
      }

      if (!is.null(`platform`) && !(`platform` %in% c("shopify"))) {
        stop("Invalid value for platform when calling StoreIntegrationsApi$GetStoreConnection. Must be [shopify].")
      }
      query_params[["platform"]] <- `platform`

      query_params[["domain"]] <- `domain`

      local_var_url_path <- "/store_connection"
      # Bearer token
      if (!is.null(self$api_client$bearer_token)) {
        header_params["Authorization"] <- paste("Bearer", self$api_client$bearer_token, sep = " ")
      }

      # The Accept request HTTP header
      local_var_accepts <- list("application/json")

      # The Content-Type representation header
      local_var_content_types <- list()

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "GET",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        # save response in a file
        if (!is.null(data_file)) {
          self$api_client$WriteFile(local_var_resp, data_file)
        }
        if (!.parse) {
          local_var_resp$content <- local_var_resp$response_as_text()
          return(local_var_resp)
        }

        deserialized_resp_obj <- tryCatch(
          self$api_client$DeserializeResponse(local_var_resp, "StoreConnectionResponse"),
          error = function(e) {
            stop("Failed to deserialize response")
          }
        )
        local_var_resp$content <- deserialized_resp_obj
        return(local_var_resp)
      } 
      
      local_var_error_msg <- local_var_resp$response_as_text()      
      if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        ApiResponse$new(content = paste("Server returned ", local_var_resp$status_code, " response status code."),
                        response = local_var_resp,
                        status_code = local_var_resp$status_code)
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        ApiResponse$new(content = "API client error",
                        response = local_var_resp,
                        status_code = local_var_resp$status_code)
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        if (is.null(local_var_resp$response) || all(local_var_resp$response == "")) {
          local_var_resp$response <- "API server error"
        }
        return(local_var_resp)
      }
    },

    #' @description
    #' Read AI-referred store orders
    #'
    #' @param project_id Project ID
    #' @param platform (optional) Store platform (default value: "shopify")
    #' @param from (optional) First day (YYYY-MM-DD). Defaults to 89 days before to
    #' @param to (optional) Last day (YYYY-MM-DD). Defaults to today; the window is at most 400 days
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @param .parse Logical. If \code{TRUE} then the response will be parsed to a generated type. If \code{FALSE} the response will be returned as unparsed text.
    #'
    #' @return AiOrdersResponse
    ListAiOrders = function(project_id, platform = "shopify", from = NULL, to = NULL, data_file = NULL, ..., .parse = TRUE) {
      local_var_response <- self$ListAiOrdersWithHttpInfo(project_id, platform, from, to, data_file = data_file, ..., .parse = .parse)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        return(local_var_response$content)
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        return(local_var_response)
      }
    },

    #' @description
    #' Read AI-referred store orders
    #'
    #' @param project_id Project ID
    #' @param platform (optional) Store platform (default value: "shopify")
    #' @param from (optional) First day (YYYY-MM-DD). Defaults to 89 days before to
    #' @param to (optional) Last day (YYYY-MM-DD). Defaults to today; the window is at most 400 days
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @param .parse Logical. If \code{TRUE} then the response will be parsed to a generated type. If \code{FALSE} the response will be returned as unparsed text.
    #'
    #' @return API response (AiOrdersResponse) with additional information such as HTTP status code, headers
    ListAiOrdersWithHttpInfo = function(project_id, platform = "shopify", from = NULL, to = NULL, data_file = NULL, ..., .parse = TRUE) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE

      if (missing(`project_id`)) {
        stop("Missing required parameter `project_id`.")
      }

      if (!missing(`project_id`) && is.null(`project_id`)) {
        stop("Invalid value for `project_id` when calling StoreIntegrationsApi$ListAiOrders, `project_id` is not nullable")
      }

      if (!missing(`platform`) && is.null(`platform`)) {
        stop("Invalid value for `platform` when calling StoreIntegrationsApi$ListAiOrders, `platform` is not nullable")
      }

      if (!missing(`from`) && is.null(`from`)) {
        stop("Invalid value for `from` when calling StoreIntegrationsApi$ListAiOrders, `from` is not nullable")
      }

      if (!missing(`to`) && is.null(`to`)) {
        stop("Invalid value for `to` when calling StoreIntegrationsApi$ListAiOrders, `to` is not nullable")
      }

      query_params[["project_id"]] <- `project_id`

      if (!is.null(`platform`) && !(`platform` %in% c("shopify"))) {
        stop("Invalid value for platform when calling StoreIntegrationsApi$ListAiOrders. Must be [shopify].")
      }
      query_params[["platform"]] <- `platform`

      query_params[["from"]] <- `from`

      query_params[["to"]] <- `to`

      local_var_url_path <- "/ai_orders"
      # Bearer token
      if (!is.null(self$api_client$bearer_token)) {
        header_params["Authorization"] <- paste("Bearer", self$api_client$bearer_token, sep = " ")
      }

      # The Accept request HTTP header
      local_var_accepts <- list("application/json")

      # The Content-Type representation header
      local_var_content_types <- list()

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "GET",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        # save response in a file
        if (!is.null(data_file)) {
          self$api_client$WriteFile(local_var_resp, data_file)
        }
        if (!.parse) {
          local_var_resp$content <- local_var_resp$response_as_text()
          return(local_var_resp)
        }

        deserialized_resp_obj <- tryCatch(
          self$api_client$DeserializeResponse(local_var_resp, "AiOrdersResponse"),
          error = function(e) {
            stop("Failed to deserialize response")
          }
        )
        local_var_resp$content <- deserialized_resp_obj
        return(local_var_resp)
      } 
      
      local_var_error_msg <- local_var_resp$response_as_text()      
      if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        ApiResponse$new(content = paste("Server returned ", local_var_resp$status_code, " response status code."),
                        response = local_var_resp,
                        status_code = local_var_resp$status_code)
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        ApiResponse$new(content = "API client error",
                        response = local_var_resp,
                        status_code = local_var_resp$status_code)
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        if (is.null(local_var_resp$response) || all(local_var_resp$response == "")) {
          local_var_resp$response <- "API server error"
        }
        return(local_var_resp)
      }
    },

    #' @description
    #' List catalog prompt suggestions
    #'
    #' @param project_id Project ID
    #' @param status (optional) Only suggestions in this status
    #' @param product_external_id (optional) Only suggestions for this store product id
    #' @param page (optional) No description (default value: 1)
    #' @param per_page (optional) No description (default value: 50)
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @param .parse Logical. If \code{TRUE} then the response will be parsed to a generated type. If \code{FALSE} the response will be returned as unparsed text.
    #'
    #' @return CatalogPromptSuggestionsResponse
    ListCatalogPromptSuggestions = function(project_id, status = NULL, product_external_id = NULL, page = 1, per_page = 50, data_file = NULL, ..., .parse = TRUE) {
      local_var_response <- self$ListCatalogPromptSuggestionsWithHttpInfo(project_id, status, product_external_id, page, per_page, data_file = data_file, ..., .parse = .parse)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        return(local_var_response$content)
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        return(local_var_response)
      }
    },

    #' @description
    #' List catalog prompt suggestions
    #'
    #' @param project_id Project ID
    #' @param status (optional) Only suggestions in this status
    #' @param product_external_id (optional) Only suggestions for this store product id
    #' @param page (optional) No description (default value: 1)
    #' @param per_page (optional) No description (default value: 50)
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @param .parse Logical. If \code{TRUE} then the response will be parsed to a generated type. If \code{FALSE} the response will be returned as unparsed text.
    #'
    #' @return API response (CatalogPromptSuggestionsResponse) with additional information such as HTTP status code, headers
    ListCatalogPromptSuggestionsWithHttpInfo = function(project_id, status = NULL, product_external_id = NULL, page = 1, per_page = 50, data_file = NULL, ..., .parse = TRUE) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE

      if (missing(`project_id`)) {
        stop("Missing required parameter `project_id`.")
      }

      if (!missing(`project_id`) && is.null(`project_id`)) {
        stop("Invalid value for `project_id` when calling StoreIntegrationsApi$ListCatalogPromptSuggestions, `project_id` is not nullable")
      }

      if (!missing(`status`) && is.null(`status`)) {
        stop("Invalid value for `status` when calling StoreIntegrationsApi$ListCatalogPromptSuggestions, `status` is not nullable")
      }

      if (!missing(`product_external_id`) && is.null(`product_external_id`)) {
        stop("Invalid value for `product_external_id` when calling StoreIntegrationsApi$ListCatalogPromptSuggestions, `product_external_id` is not nullable")
      }

      if (!missing(`page`) && is.null(`page`)) {
        stop("Invalid value for `page` when calling StoreIntegrationsApi$ListCatalogPromptSuggestions, `page` is not nullable")
      }
      if (!is.null(`page`) && `page` <  1) {
        stop("Invalid value for `page` when calling StoreIntegrationsApi$ListCatalogPromptSuggestions, must be bigger than or equal to 1.")
      }

      if (!missing(`per_page`) && is.null(`per_page`)) {
        stop("Invalid value for `per_page` when calling StoreIntegrationsApi$ListCatalogPromptSuggestions, `per_page` is not nullable")
      }
      if (!is.null(`per_page`) && `per_page` >  100) {
        stop("Invalid value for `per_page` when calling StoreIntegrationsApi$ListCatalogPromptSuggestions, must be smaller than or equal to 100.")
      }
      if (!is.null(`per_page`) && `per_page` <  1) {
        stop("Invalid value for `per_page` when calling StoreIntegrationsApi$ListCatalogPromptSuggestions, must be bigger than or equal to 1.")
      }

      query_params[["project_id"]] <- `project_id`

      if (!is.null(`status`) && !(`status` %in% c("pending", "accepted", "rejected"))) {
        stop("Invalid value for status when calling StoreIntegrationsApi$ListCatalogPromptSuggestions. Must be [pending, accepted, rejected].")
      }
      query_params[["status"]] <- `status`

      query_params[["product_external_id"]] <- `product_external_id`

      query_params[["page"]] <- `page`

      query_params[["per_page"]] <- `per_page`

      local_var_url_path <- "/catalog_prompt_suggestions"
      # Bearer token
      if (!is.null(self$api_client$bearer_token)) {
        header_params["Authorization"] <- paste("Bearer", self$api_client$bearer_token, sep = " ")
      }

      # The Accept request HTTP header
      local_var_accepts <- list("application/json")

      # The Content-Type representation header
      local_var_content_types <- list()

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "GET",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        # save response in a file
        if (!is.null(data_file)) {
          self$api_client$WriteFile(local_var_resp, data_file)
        }
        if (!.parse) {
          local_var_resp$content <- local_var_resp$response_as_text()
          return(local_var_resp)
        }

        deserialized_resp_obj <- tryCatch(
          self$api_client$DeserializeResponse(local_var_resp, "CatalogPromptSuggestionsResponse"),
          error = function(e) {
            stop("Failed to deserialize response")
          }
        )
        local_var_resp$content <- deserialized_resp_obj
        return(local_var_resp)
      } 
      
      local_var_error_msg <- local_var_resp$response_as_text()      
      if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        ApiResponse$new(content = paste("Server returned ", local_var_resp$status_code, " response status code."),
                        response = local_var_resp,
                        status_code = local_var_resp$status_code)
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        ApiResponse$new(content = "API client error",
                        response = local_var_resp,
                        status_code = local_var_resp$status_code)
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        if (is.null(local_var_resp$response) || all(local_var_resp$response == "")) {
          local_var_resp$response <- "API server error"
        }
        return(local_var_resp)
      }
    },

    #' @description
    #' Reject catalog prompt suggestions
    #'
    #' @param catalog_prompt_suggestion_ids_request 
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @param .parse Logical. If \code{TRUE} then the response will be parsed to a generated type. If \code{FALSE} the response will be returned as unparsed text.
    #'
    #' @return CatalogPromptSuggestionsRejectResponse
    RejectCatalogPromptSuggestions = function(catalog_prompt_suggestion_ids_request, data_file = NULL, ..., .parse = TRUE) {
      local_var_response <- self$RejectCatalogPromptSuggestionsWithHttpInfo(catalog_prompt_suggestion_ids_request, data_file = data_file, ..., .parse = .parse)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        return(local_var_response$content)
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        return(local_var_response)
      }
    },

    #' @description
    #' Reject catalog prompt suggestions
    #'
    #' @param catalog_prompt_suggestion_ids_request 
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @param .parse Logical. If \code{TRUE} then the response will be parsed to a generated type. If \code{FALSE} the response will be returned as unparsed text.
    #'
    #' @return API response (CatalogPromptSuggestionsRejectResponse) with additional information such as HTTP status code, headers
    RejectCatalogPromptSuggestionsWithHttpInfo = function(catalog_prompt_suggestion_ids_request, data_file = NULL, ..., .parse = TRUE) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE

      if (missing(`catalog_prompt_suggestion_ids_request`)) {
        stop("Missing required parameter `catalog_prompt_suggestion_ids_request`.")
      }

      if (!missing(`catalog_prompt_suggestion_ids_request`) && is.null(`catalog_prompt_suggestion_ids_request`)) {
        stop("Invalid value for `catalog_prompt_suggestion_ids_request` when calling StoreIntegrationsApi$RejectCatalogPromptSuggestions, `catalog_prompt_suggestion_ids_request` is not nullable")
      }

      if (!is.null(`catalog_prompt_suggestion_ids_request`)) {
        local_var_body <- `catalog_prompt_suggestion_ids_request`$toJSONString()
      } else {
        local_var_body <- NULL
      }

      local_var_url_path <- "/catalog_prompt_suggestions/reject"
      # Bearer token
      if (!is.null(self$api_client$bearer_token)) {
        header_params["Authorization"] <- paste("Bearer", self$api_client$bearer_token, sep = " ")
      }

      # The Accept request HTTP header
      local_var_accepts <- list("application/json")

      # The Content-Type representation header
      local_var_content_types <- list("application/json")

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "POST",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        # save response in a file
        if (!is.null(data_file)) {
          self$api_client$WriteFile(local_var_resp, data_file)
        }
        if (!.parse) {
          local_var_resp$content <- local_var_resp$response_as_text()
          return(local_var_resp)
        }

        deserialized_resp_obj <- tryCatch(
          self$api_client$DeserializeResponse(local_var_resp, "CatalogPromptSuggestionsRejectResponse"),
          error = function(e) {
            stop("Failed to deserialize response")
          }
        )
        local_var_resp$content <- deserialized_resp_obj
        return(local_var_resp)
      } 
      
      local_var_error_msg <- local_var_resp$response_as_text()      
      if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        ApiResponse$new(content = paste("Server returned ", local_var_resp$status_code, " response status code."),
                        response = local_var_resp,
                        status_code = local_var_resp$status_code)
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        ApiResponse$new(content = "API client error",
                        response = local_var_resp,
                        status_code = local_var_resp$status_code)
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        if (is.null(local_var_resp$response) || all(local_var_resp$response == "")) {
          local_var_resp$response <- "API server error"
        }
        return(local_var_resp)
      }
    },

    #' @description
    #' Replace AI-referred store orders for a window
    #'
    #' @param ai_orders_update_request 
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @param .parse Logical. If \code{TRUE} then the response will be parsed to a generated type. If \code{FALSE} the response will be returned as unparsed text.
    #'
    #' @return AiOrdersUpdateResponse
    ReplaceAiOrders = function(ai_orders_update_request, data_file = NULL, ..., .parse = TRUE) {
      local_var_response <- self$ReplaceAiOrdersWithHttpInfo(ai_orders_update_request, data_file = data_file, ..., .parse = .parse)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        return(local_var_response$content)
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        return(local_var_response)
      }
    },

    #' @description
    #' Replace AI-referred store orders for a window
    #'
    #' @param ai_orders_update_request 
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @param .parse Logical. If \code{TRUE} then the response will be parsed to a generated type. If \code{FALSE} the response will be returned as unparsed text.
    #'
    #' @return API response (AiOrdersUpdateResponse) with additional information such as HTTP status code, headers
    ReplaceAiOrdersWithHttpInfo = function(ai_orders_update_request, data_file = NULL, ..., .parse = TRUE) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE

      if (missing(`ai_orders_update_request`)) {
        stop("Missing required parameter `ai_orders_update_request`.")
      }

      if (!missing(`ai_orders_update_request`) && is.null(`ai_orders_update_request`)) {
        stop("Invalid value for `ai_orders_update_request` when calling StoreIntegrationsApi$ReplaceAiOrders, `ai_orders_update_request` is not nullable")
      }

      if (!is.null(`ai_orders_update_request`)) {
        local_var_body <- `ai_orders_update_request`$toJSONString()
      } else {
        local_var_body <- NULL
      }

      local_var_url_path <- "/ai_orders"
      # Bearer token
      if (!is.null(self$api_client$bearer_token)) {
        header_params["Authorization"] <- paste("Bearer", self$api_client$bearer_token, sep = " ")
      }

      # The Accept request HTTP header
      local_var_accepts <- list("application/json")

      # The Content-Type representation header
      local_var_content_types <- list("application/json")

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "PUT",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        # save response in a file
        if (!is.null(data_file)) {
          self$api_client$WriteFile(local_var_resp, data_file)
        }
        if (!.parse) {
          local_var_resp$content <- local_var_resp$response_as_text()
          return(local_var_resp)
        }

        deserialized_resp_obj <- tryCatch(
          self$api_client$DeserializeResponse(local_var_resp, "AiOrdersUpdateResponse"),
          error = function(e) {
            stop("Failed to deserialize response")
          }
        )
        local_var_resp$content <- deserialized_resp_obj
        return(local_var_resp)
      } 
      
      local_var_error_msg <- local_var_resp$response_as_text()      
      if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        ApiResponse$new(content = paste("Server returned ", local_var_resp$status_code, " response status code."),
                        response = local_var_resp,
                        status_code = local_var_resp$status_code)
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        ApiResponse$new(content = "API client error",
                        response = local_var_resp,
                        status_code = local_var_resp$status_code)
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        if (is.null(local_var_resp$response) || all(local_var_resp$response == "")) {
          local_var_resp$response <- "API server error"
        }
        return(local_var_resp)
      }
    }
  )
)
